### ISSUE TITLE
java.lang.IllegalStateException: Cannot resolve type description for 

### ISSUE THREAD

**Issue by WassimDhib** [elastic/apm-agent-java#1037]
## Describe the bug
I have an issue when starting Jboss server

## Steps to reproduce
Whe have on this linux server an other commercial apm which is deactivated and stopped, but it is still have a part loaded with linux LD_PRELOAD

## Debug logs
```
12/02/2020 12:41:52-239 | INFO  | stdout | 2020-02-12 12:41:52.239 [ServerService Thread Pool -- 41] INFO co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - com.another.commercial.apm.agent.introspection.uem.impl.CacheHookingRequestWrapper refers to a missing class
12/02/2020 12:41:52-240 | INFO  | stdout | java.lang.IllegalStateException: Cannot resolve type description for com.another.commercial.apm.agent.introspection.uem.apiobjects.UemServletRequestWrapperInterface
12/02/2020 12:41:52-241 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:159)
12/02/2020 12:41:52-242 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:914)
12/02/2020 12:41:52-242 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:8122)
12/02/2020 12:41:52-242 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:618)
12/02/2020 12:41:52-243 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:336)
12/02/2020 12:41:52-243 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:7631)
12/02/2020 12:41:52-244 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:48)
12/02/2020 12:41:52-244 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:27)
12/02/2020 12:41:52-244 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:46)
12/02/2020 12:41:52-245 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:50)
12/02/2020 12:41:52-245 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:29)
12/02/2020 12:41:52-246 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:48)
12/02/2020 12:41:52-246 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:27)
12/02/2020 12:41:52-246 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:48)
12/02/2020 12:41:52-249 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:26)
12/02/2020 12:41:52-250 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:46)
12/02/2020 12:41:52-250 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:49)
12/02/2020 12:41:52-251 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:28)
12/02/2020 12:41:52-251 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
12/02/2020 12:41:52-251 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
12/02/2020 12:41:52-252 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:122)
12/02/2020 12:41:52-252 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.matcher.FilterableList$AbstractBase.filter(FilterableList.java:125)
12/02/2020 12:41:52-253 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:505)
12/02/2020 12:41:52-253 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:198)
12/02/2020 12:41:52-253 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$Transformation$Simple$Resolution.apply(AgentBuilder.java:10123)
12/02/2020 12:41:52-254 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10494)
12/02/2020 12:41:52-254 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10457)
12/02/2020 12:41:52-254 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1500(AgentBuilder.java:10223)
12/02/2020 12:41:52-255 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10833)
12/02/2020 12:41:52-255 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10780)
12/02/2020 12:41:52-256 | INFO  | stdout |      at java.security.AccessController.doPrivileged(Native Method)
12/02/2020 12:41:52-256 | INFO  | stdout |      at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10380)
12/02/2020 12:41:52-257 | INFO  | stdout |      at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
12/02/2020 12:41:52-257 | INFO  | org.wildfly.extension.undertow | WFLYUT0003: Démarrage 1.3.21.Final-redhat-1 d'Undertow
12/02/2020 12:41:52-257 | INFO  | stdout |      at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
12/02/2020 12:41:52-257 | INFO  | stdout |      at java.lang.ClassLoader.defineClass1(Native Method)
12/02/2020 12:41:52-258 | INFO  | stdout |      at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
12/02/2020 12:41:52-258 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:358)
12/02/2020 12:41:52-259 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:437)
12/02/2020 12:41:52-259 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:274)
12/02/2020 12:41:52-259 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:78)
12/02/2020 12:41:52-260 | INFO  | stdout |      at org.jboss.modules.Module.loadModuleClass(Module.java:605)
12/02/2020 12:41:52-260 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
12/02/2020 12:41:52-261 | INFO  | stdout |      at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
12/02/2020 12:41:52-261 | INFO  | stdout |      at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
12/02/2020 12:41:52-261 | INFO  | stdout |      at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
12/02/2020 12:41:52-261 | INFO  | org.wildfly.extension.undertow | WFLYUT0003: Démarrage 1.3.21.Final-redhat-1 d'Undertow
12/02/2020 12:41:52-262 | INFO  | stdout |      at java.lang.Class.forName0(Native Method)
12/02/2020 12:41:52-262 | INFO  | stdout |      at java.lang.Class.forName(Class.java:348)
12/02/2020 12:41:52-262 | INFO  | stdout |      at java.lang.ClassLoader.defineClass1(Native Method)
12/02/2020 12:41:52-263 | INFO  | stdout |      at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
12/02/2020 12:41:52-263 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:358)
12/02/2020 12:41:52-264 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:437)
12/02/2020 12:41:52-264 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:274)
12/02/2020 12:41:52-265 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:78)
12/02/2020 12:41:52-265 | INFO  | stdout |      at org.jboss.modules.Module.loadModuleClass(Module.java:605)
12/02/2020 12:41:52-265 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
12/02/2020 12:41:52-266 | INFO  | stdout |      at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
12/02/2020 12:41:52-266 | INFO  | stdout |      at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
12/02/2020 12:41:52-266 | INFO  | stdout |      at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
12/02/2020 12:41:52-267 | INFO  | stdout |      at java.lang.Class.forName0(Native Method)
12/02/2020 12:41:52-267 | INFO  | stdout |      at java.lang.Class.forName(Class.java:348)
12/02/2020 12:41:52-268 | INFO  | stdout |      at java.lang.ClassLoader.defineClass1(Native Method)
12/02/2020 12:41:52-268 | INFO  | stdout |      at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
12/02/2020 12:41:52-268 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:358)
12/02/2020 12:41:52-269 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:437)
12/02/2020 12:41:52-270 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:274)
12/02/2020 12:41:52-270 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:78)
12/02/2020 12:41:52-270 | INFO  | stdout |      at org.jboss.modules.Module.loadModuleClass(Module.java:605)
12/02/2020 12:41:52-271 | INFO  | stdout |      at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:190)
12/02/2020 12:41:52-271 | INFO  | stdout |      at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
12/02/2020 12:41:52-271 | INFO  | stdout |      at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
12/02/2020 12:41:52-272 | INFO  | stdout |      at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
12/02/2020 12:41:52-272 | INFO  | stdout |      at org.jboss.resteasy.plugins.server.servlet.ResteasyBootstrapClasses.<clinit>(ResteasyBootstrapClasses.java:11)
12/02/2020 12:41:52-273 | INFO  | stdout |      at org.jboss.as.jaxrs.deployment.JaxrsScanningProcessor.<clinit>(JaxrsScanningProcessor.java:121)
12/02/2020 12:41:52-273 | INFO  | stdout |      at org.jboss.as.jaxrs.JaxrsSubsystemAdd$1.execute(JaxrsSubsystemAdd.java:63)
12/02/2020 12:41:52-273 | INFO  | stdout |      at org.jboss.as.server.AbstractDeploymentChainStep.execute(AbstractDeploymentChainStep.java:50)
12/02/2020 12:41:52-274 | INFO  | stdout |      at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:890)
12/02/2020 12:41:52-280 | INFO  | stdout |      at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:659)
12/02/2020 12:41:52-281 | INFO  | stdout |      at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
12/02/2020 12:41:52-281 | INFO  | stdout |      at org.jboss.as.controller.ParallelBootOperationStepHandler$ParallelBootTask.run(ParallelBootOperationStepHandler.java:359)
12/02/2020 12:41:52-281 | INFO  | stdout |      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
12/02/2020 12:41:52-282 | INFO  | stdout |      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
12/02/2020 12:41:52-282 | INFO  | stdout |      at java.lang.Thread.run(Thread.java:745)
12/02/2020 12:41:52-283 | INFO  | stdout |      at org.jboss.threads.JBossThread.run(JBossThread.java:320)
12/02/2020 12:41:52-415 | INFO  | org.jboss.as.connector.subsystems.datasources | WFLYJCA0004: Déploiement du pilote compatible JDCB class oracle.jdbc.OracleDriver (version 12.1)
12/02/2020 12:41:52-415 | INFO  | org.jboss.as.connector.subsystems.datasources | WFLYJCA0004: Déploiement du pilote compatible JDCB class oracle.jdbc.OracleDriver (version 12.1)
12/02/2020 12:41:52-420 | INFO  | org.jboss.as.connector.deployers.jdbc | WFLYJCA0018: Démarrage du service de pilote avec le nom de pilote  = oraclexa
12/02/2020 12:41:52-420 | INFO  | org.jboss.as.connector.deployers.jdbc | WFLYJCA0018: Démarrage du service de pilote avec le nom de pilote  = oraclexa
12/02/2020 12:41:52-470 | INFO  | stdout | 2020-02-12 12:41:52.469 [ServerService Thread Pool -- 59] INFO co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - com.another.commercial.apm.agent.introspection.uem.impl.CacheHookingRequestWrapper refers to a missing class
12/02/2020 12:41:52-471 | INFO  | stdout | java.lang.IllegalStateException: Cannot resolve type description for com.another.commercial.apm.agent.introspection.uem.apiobjects.UemServletRequestWrapperInterface

```

**Comment by SylvainJuge** [comment]
Hi, thanks for reporting this.

This error message means that our agent is not able to properly to load some classes, which happens sometimes with non-standard classloaders.

Apart from this kind of verbose error message in the logs, was there any other side effects on the application ?

Because the classes that are involved here are part of another agent, that's unlikely that our agent will need to instrument them. But, seeing those classes during class-loading means that this agent is not completely disabled and causes side-effects.

Could you try again with removing this other agent to see if the issue still happens ?

**Comment by SylvainJuge** [comment]
While discussing this internally @felixbarny suggested that we just ignore other APM vendors classes by default, could you just confirm that the class that triggered this would be covered ? 

https://github.com/elastic/apm-agent-java/pull/1038/files

**Comment by WassimDhib** [comment]
you should add this one :  com.compuware

Full class names was : 
com.compuware.apm.agent.introspection.uem.impl.CacheHookingRequestWrapper
com.compuware.apm.agent.introspection.uem.apiobjects.UemServletRequestWrapperInterface

it's a part of dynatrace oneagent, it seems to be loaded with /etc/ld.so.preload

Removing this prelaod command solved the problem, no more log message.

**Comment by SylvainJuge** [comment]
Thanks, will add this to the pull-request then. We might have a snapshot version of the agent that will ignore those classes soon.
