### ISSUE TITLE
Using the agent with spring boot and Jesque results in java.lang.NullPointerException

### ISSUE THREAD

**Issue by oofdog** [elastic/apm-agent-java#1039]
## Describe the bug
An exception is thrown repeatedly when using this agent with Jesque.

## Steps to reproduce
1. Create a simple spring boot 2.2 application
2. Include this Jesque starter https://github.com/IceMimosa/spring-boot-starter-jesque
3. Launch the app with the APM java agent attached, and the console will be spammed with this error

## Expected behavior
No Jedis errors

## Debug logs

<details>
<summary>Click to expand</summary>

```
java.lang.NullPointerException
	at redis.clients.jedis.BinaryJedis.quit(BinaryJedis.java:256)
	at redis.clients.jedis.JedisFactory.destroyObject(JedisFactory.java:120)
	at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:928)
	at org.apache.commons.pool2.impl.GenericObjectPool.returnObject(GenericObjectPool.java:575)
	at redis.clients.util.Pool.returnResourceObject(Pool.java:73)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:262)
	at redis.clients.jedis.JedisPool.returnResource(JedisPool.java:16)
	at redis.clients.jedis.Jedis.close(Jedis.java:3637)
	at net.greghaines.jesque.utils.PoolUtils.doWorkInPool(PoolUtils.java:54)
	at net.greghaines.jesque.utils.PoolUtils.doWorkInPoolNicely(PoolUtils.java:71)
	at net.greghaines.jesque.worker.WorkerPoolImpl.pop(WorkerPoolImpl.java:530)
	at net.greghaines.jesque.worker.WorkerPoolImpl.poll(WorkerPoolImpl.java:457)
	at net.greghaines.jesque.worker.WorkerPoolImpl.run(WorkerPoolImpl.java:218)
	at java.lang.Thread.run(Thread.java:748)
```
</details>

**Comment by felixbarny** [comment]
Thanks for reporting! I can reproduce this and started investigating. That should not affect your application, only the tracing. In the mean time, you can disable Jedis instrumentation by setting `disable_instrumentations=incubating,jedis`.
