### ISSUE TITLE
Flaky gRPC test

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#1178]
## Test method
`co.elastic.apm.agent.grpc.latest.GrpcClientInstrumentationTest.simpleCall`

## Test logs

<details>
<summary>Click to expand</summary>

```
[main] INFO co.elastic.apm.agent.grpc.testapp.HelloServer - starting grpc server on port 50051
[main] INFO co.elastic.apm.agent.grpc.testapp.HelloServer - grpc server start complete
[main] DEBUG co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool - creating pooled object: '' 00-00000000000000000000000000000000-0000000000000000-00 (596830cd)
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to '' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd) (1)
[main] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - startTransaction '' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd) {
[main] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating 'Test gRPC client' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd) on thread 1
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to 'Test gRPC client' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd) (2)
[main] DEBUG co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool - creating pooled object: '' 00-00000000000000000000000000000000-0000000000000000-00 (579e30b7)
[main] DEBUG co.elastic.apm.agent.impl.transaction.Span - startSpan '' 00-0577b86a813f4e74bdd06839416283e1-232dfe1c2078c2aa-01 (579e30b7) {
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to 'Test gRPC client' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd) (3)
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to '' 00-0577b86a813f4e74bdd06839416283e1-232dfe1c2078c2aa-01 (579e30b7) (1)
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to 'Test gRPC client' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd) (4)
[main] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-232dfe1c2078c2aa-01 (579e30b7) on thread 1
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to 'Test gRPC client' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd) (5)
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-232dfe1c2078c2aa-01 (579e30b7) (2)
[main] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-232dfe1c2078c2aa-01 (579e30b7) on thread 1
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'Test gRPC client' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd) (4)
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-232dfe1c2078c2aa-01 (579e30b7) (1)
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.grpc.ClientCallImplInstrumentation$ListenerClose
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.grpc.ClientCallImplInstrumentation$ListenerReady
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.grpc.ClientCallImplInstrumentation$ListenerMessage
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Applying instrumentation co.elastic.apm.agent.grpc.ClientCallImplInstrumentation$ListenerHeaders
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation ListenerClose: ((is(class io.grpc.ClientCall$Listener) or (is(class io.grpc.stub.ClientCalls$UnaryStreamToFuture) or false)) and true) matches class io.grpc.stub.ClientCalls$UnaryStreamToFuture
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation ListenerClose: ((is(class io.grpc.ClientCall$Listener) or (is(class io.grpc.stub.ClientCalls$UnaryStreamToFuture) or false)) and true) matches class io.grpc.ClientCall$Listener
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation ListenerClose: ((is(class io.grpc.ClientCall$Listener) or (is(class io.grpc.stub.ClientCalls$UnaryStreamToFuture) or false)) and true) matches class io.grpc.stub.ClientCalls$UnaryStreamToFuture
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation ListenerMessage: ((is(class io.grpc.ClientCall$Listener) or (is(class io.grpc.stub.ClientCalls$UnaryStreamToFuture) or false)) and true) matches class io.grpc.stub.ClientCalls$UnaryStreamToFuture
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation ListenerHeaders: ((is(class io.grpc.ClientCall$Listener) or (is(class io.grpc.stub.ClientCalls$UnaryStreamToFuture) or false)) and true) matches class io.grpc.stub.ClientCalls$UnaryStreamToFuture
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method match for instrumentation ListenerClose: name(equals(onClose)) matches public void io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(io.grpc.Status,io.grpc.Metadata)
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method match for instrumentation ListenerMessage: name(equals(onMessage)) matches public void io.grpc.stub.ClientCalls$UnaryStreamToFuture.onMessage(java.lang.Object)
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method match for instrumentation ListenerHeaders: name(equals(onHeaders)) matches public void io.grpc.stub.ClientCalls$UnaryStreamToFuture.onHeaders(io.grpc.Metadata)
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation ListenerClose: ((is(class io.grpc.ClientCall$Listener) or (is(class io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter) or false)) and true) matches class io.grpc.ClientCall$Listener
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation ListenerReady: ((is(class io.grpc.ClientCall$Listener) or (is(class io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter) or false)) and true) matches class io.grpc.ClientCall$Listener
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation ListenerMessage: ((is(class io.grpc.ClientCall$Listener) or (is(class io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter) or false)) and true) matches class io.grpc.ClientCall$Listener
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation ListenerHeaders: ((is(class io.grpc.ClientCall$Listener) or (is(class io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter) or false)) and true) matches class io.grpc.ClientCall$Listener
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method match for instrumentation ListenerClose: name(equals(onClose)) matches public void io.grpc.ClientCall$Listener.onClose(io.grpc.Status,io.grpc.Metadata)
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method match for instrumentation ListenerMessage: name(equals(onMessage)) matches public void io.grpc.ClientCall$Listener.onMessage(java.lang.Object)
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method match for instrumentation ListenerReady: name(equals(onReady)) matches public void io.grpc.ClientCall$Listener.onReady()
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method match for instrumentation ListenerHeaders: name(equals(onHeaders)) matches public void io.grpc.ClientCall$Listener.onHeaders(io.grpc.Metadata)
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation ListenerClose: ((is(class io.grpc.ClientCall$Listener) or (is(class io.grpc.stub.ClientCalls$UnaryStreamToFuture) or false)) and true) matches class io.grpc.ClientCall$Listener
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation ListenerReady: ((is(class io.grpc.ClientCall$Listener) or false) and true) matches class io.grpc.ClientCall$Listener
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation ListenerMessage: ((is(class io.grpc.ClientCall$Listener) or (is(class io.grpc.stub.ClientCalls$UnaryStreamToFuture) or false)) and true) matches class io.grpc.ClientCall$Listener
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation ListenerHeaders: ((is(class io.grpc.ClientCall$Listener) or (is(class io.grpc.stub.ClientCalls$UnaryStreamToFuture) or false)) and true) matches class io.grpc.ClientCall$Listener
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method match for instrumentation ListenerClose: name(equals(onClose)) matches public void io.grpc.ClientCall$Listener.onClose(io.grpc.Status,io.grpc.Metadata)
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method match for instrumentation ListenerMessage: name(equals(onMessage)) matches public void io.grpc.ClientCall$Listener.onMessage(java.lang.Object)
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method match for instrumentation ListenerReady: name(equals(onReady)) matches public void io.grpc.ClientCall$Listener.onReady()
[main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method match for instrumentation ListenerHeaders: name(equals(onHeaders)) matches public void io.grpc.ClientCall$Listener.onHeaders(io.grpc.Metadata)
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool - creating pooled object: '' 00-00000000000000000000000000000000-0000000000000000-00 (17656576)
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to '' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) (1)
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - startTransaction '' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) {
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) on thread 40
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) (2)
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) on thread 40
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) (1)
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) on thread 40
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) (2)
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) on thread 40
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) (1)
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) on thread 40
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) (2)
[grpc-default-executor-1] INFO co.elastic.apm.agent.grpc.testapp.HelloServer - start processing
[grpc-default-executor-1] INFO co.elastic.apm.agent.grpc.testapp.HelloServer - end of processing, response not sent yet
[grpc-default-executor-1] INFO co.elastic.apm.agent.grpc.testapp.HelloServer - start sending response
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - endTransaction 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576)
[main] DEBUG co.elastic.apm.agent.impl.transaction.Span - endSpan 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-232dfe1c2078c2aa-01 (579e30b7)
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'Test gRPC client' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd) (3)
[grpc-default-executor-1] INFO co.elastic.apm.agent.grpc.testapp.HelloServer - end of sending response
[main] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 'Test gRPC client' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd) on thread 1
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'Test gRPC client' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd) (2)
[main] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - endTransaction 'Test gRPC client' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd)
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) (1)
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'Test gRPC client' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd) (1)
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'Test gRPC client' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd) (0)
[main] DEBUG co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool - recycling pooled object: 'Test gRPC client' 00-0577b86a813f4e74bdd06839416283e1-761abc56406d64ed-01 (596830cd)
[main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-232dfe1c2078c2aa-01 (579e30b7) (0)
[main] DEBUG co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool - recycling pooled object: 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-232dfe1c2078c2aa-01 (579e30b7)
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) on thread 40
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576) (0)
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool - recycling pooled object: 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576)
[main] INFO co.elastic.apm.agent.grpc.testapp.HelloClient - client channel has been properly shut down
[main] INFO co.elastic.apm.agent.grpc.testapp.HelloServer - stopping grpc server
[main] INFO co.elastic.apm.agent.grpc.testapp.HelloServer - grpc server shutdown complete

org.opentest4j.AssertionFailedError: 
[should have empty trace context : '' 00-00000000000000000000000000000000-0000000000000000-00 (17656576)] 
Expecting:
 <false>
to be equal to:
 <true>
but was not.
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at co.elastic.apm.agent.MockReporter.lambda$assertRecycledAfterDecrementingReferences$5(MockReporter.java:358)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at co.elastic.apm.agent.MockReporter.assertRecycledAfterDecrementingReferences(MockReporter.java:355)
	at co.elastic.apm.agent.grpc.AbstractGrpcClientInstrumentationTest.afterEach(AbstractGrpcClientInstrumentationTest.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeMethodInExtensionContext(ClassTestDescriptor.java:439)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$synthesizeAfterEachMethodAdapter$16(ClassTestDescriptor.java:431)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachMethods$10(TestMethodTestDescriptor.java:227)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:245)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:243)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachMethods(TestMethodTestDescriptor.java:226)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:132)
	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Standard Error
```
</details>

## Additional context

This fails more often than not lately.

Interestingly, the object does get recycled and even the error message contains an empty id:
```
[grpc-default-executor-1] DEBUG co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool - recycling pooled object: 'helloworld.Hello/SayHello' 00-0577b86a813f4e74bdd06839416283e1-8e2c5b9408aade3b-01 (17656576)
org.opentest4j.AssertionFailedError: 
[should have empty trace context : '' 00-00000000000000000000000000000000-0000000000000000-00 (17656576)] 
```

To me, this seems like a visibility issue. The object is recycled on thread `grpc-default-executor-1` but we check on the main thread. Looking at the `MockReporter`, the list that holds the transaction is not thread-safe. Only the `report(Transaction)` and `getTransactions()` methods are synchronized. But `assertRecycledAfterDecrementingReferences` accesses the non-thread-safe `transactions` list directly so visibility is not guaranteed.

**Comment by felixbarny** [comment]
Seems like #1179 didn't fix it: https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/master/366/testReport/
