### ISSUE TITLE
Enable instrumentation at runtime triggers exception

### ISSUE THREAD

**Issue by SylvainJuge** [elastic/apm-agent-java#1186]
## Describe the bug

Reported intially in our forums:
https://discuss.elastic.co/t/unable-to-dynamically-update-instrumentation-true/232645

Reproducible with tomcat9 and same java version (11.0.5), agent version is 1.15.0.

```
java.lang.IllegalStateException: The Byte Buddy agent is not installed or not accessible
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default.patchOnByteBuddyAgent(AgentBuilder.java:9435)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$Delegator.patchOnByteBuddyAgent(AgentBuilder.java:11007)
	at co.elastic.apm.agent.bci.ElasticApmAgent.doReInitInstrumentation(ElasticApmAgent.java:196)
	at co.elastic.apm.agent.bci.ElasticApmAgent$3.run(ElasticApmAgent.java:183)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: co.elastic.apm.agent.shaded.bytebuddy.agent.Installer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default.patchOnByteBuddyAgent(AgentBuilder.java:9429)
	... 8 more
```

## Steps to reproduce
- start with `recording=false` and `instrument=false` within `elasticapm.properties`
- switch those properties to `true` and wait for configuration reload

Seems likely to be only related to the `instrument` property, as it's the one that controls bytecode modification through Byte Buddy.

## Expected behavior

- no exception thrown, should work as when the value is set to `true` on startup (which is the default).

**Comment by SylvainJuge** [comment]
After further investigation:
- exception is also thrown when trying to change from `true` to `false`.
- is not reproducible with latest agent version `1.16.0`
- transition from `false` to `true` with both properties works as expected with `1.16.0` (transactions properly instrumented, metrics properly sent)

Thus maybe the changes done around configuration might have fixed this by accident.
As there is little we can do to properly test this scenario, I'll just close this issue for now.
