### ISSUE TITLE
Deploy a WAR in Tomcat 8.5.38, but starting deadlock 

### ISSUE THREAD

**Issue by pengpj** [elastic/apm-agent-java#1277]
## Describe the bug

Deploy a WAR package in Tomcat 8.5.38, inject ES APM Agent, but starting deadlock.

OS Version:            4.9.184-linuxkit
Java Home:             /jdk8/jre
Server version:        Apache Tomcat/8.5.38

## Steps to reproduce

1. package a war
2. cp to webapps path
3. start , 

```shell
+ exec /jdk8/bin/java -Xms956M -Xmx956M \
    -Xloggc:/usr/local/tomcat/logs/gc.log \
    -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties \
    -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager \
    -Djdk.tls.ephemeralDHKeySize=2048 \
    -Djava.protocol.handler.pkgs=org.apache.catalina.webresources \
    -server -XX:+AggressiveOpts -XX:+UseBiasedLocking \
    -XX:+DisableExplicitGC \
    -XX:+UseConcMarkSweepGC \
    -XX:+UseParNewGC \
    -XX:+CMSParallelRemarkEnabled \
    -XX:LargePageSizeInBytes=128m \
    -XX:+UseFastAccessorMethods \
    -XX:+UseCMSInitiatingOccupancyOnly \
    -Djava.awt.headless=true \
    -XX:+PrintGCDetails \
    -XX:+PrintGCDateStamps \
    -XX:+PrintHeapAtGC \
    -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 \
    -classpath /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar \
    -Djava.security.egd=file:/dev/./urandom \
    -Dcatalina.base=/usr/local/tomcat \
    -Dcatalina.home=/usr/local/tomcat \
    -Djava.io.tmpdir=/usr/local/tomcat/temp \
    -javaagent:/app/elastic-apm-agent.jar \
    -Delastic.apm.environment=TEST \
    -Delastic.apm.service_name=test \
    -Delastic.apm.server_urls=http://es-apm.gz.cvte.cn \
    org.apache.catalina.startup.Bootstrap start

```
4. see error

ps : cancel  `-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager` ，start and run success.

## Expected behavior

`-Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager` as a default param in the cataline.sh , hope support it normally.

## Debug logs

starting logs

<details> 
<summary>Click to expand</summary>

```
+ exec /jdk8/bin/java -Xms956M -Xmx956M -Xloggc:/usr/local/tomcat/logs/gc.log -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -server -XX:+AggressiveOpts -XX:+UseBiasedLocking -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:LargePageSizeInBytes=128m -XX:+UseFastAccessorMethods -XX:+UseCMSInitiatingOccupancyOnly -Djava.awt.headless=true -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintHeapAtGC -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -classpath /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar -Djava.security.egd=file:/dev/./urandom -Dcatalina.base=/usr/local/tomcat -Dcatalina.home=/usr/local/tomcat -Djava.io.tmpdir=/usr/local/tomcat/temp -javaagent:/app/elastic-apm-agent.jar -Delastic.apm.environment=TEST -Delastic.apm.global_labels=appId= -Delastic.apm.service_name=test -Delastic.apm.server_urls=http://es-apm.gz.cvte.cn -Xms725M -Xmx725M org.apache.catalina.startup.Bootstrap start
2020-07-08 17:04:34,744 [main] WARN  co.elastic.apm.agent.shaded.stagemonitor.configuration.ConfigurationOption - Error in Java System Properties: Error while parsing map. Expected format <regex>: <name>[, <regex>: <name>]. Actual value: 'appId=.' Default value '' for 'global_labels' will be applied.
2020-07-08 17:04:34,832 [main] INFO  co.elastic.apm.agent.util.JmxUtils - Found JVM-specific OperatingSystemMXBean interface: com.sun.management.OperatingSystemMXBean
2020-07-08 17:04:37,246 [main] INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.17.1-SNAPSHOT as test on Java 1.8.0_192 (Oracle Corporation) Linux 4.9.184-linuxkit
2020-07-08 17:04:37,247 [main] WARN  co.elastic.apm.agent.configuration.StartupInfo - To enable all features and to increase startup times, please configure application_packages
2020-07-08 17:04:37,313 [main] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Tracer switched to RUNNING sta
```
</details>

jstack for deadlock

<details> 
<summary>Click to expand</summary>

```
2020-07-08 17:17:14
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.192-b12 mixed mode):

"Attach Listener" #25 daemon prio=9 os_prio=0 tid=0x00007fa074001000 nid=0x60 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"AsyncFileHandlerWriter-1527953000" #24 daemon prio=5 os_prio=0 tid=0x00007fa0a48eb800 nid=0x1f waiting on condition [0x00007fa08c1f2000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d842c610> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingDeque.pollFirst(LinkedBlockingDeque.java:522)
	at java.util.concurrent.LinkedBlockingDeque.poll(LinkedBlockingDeque.java:684)
	at org.apache.juli.AsyncFileHandler$LoggerThread.run(AsyncFileHandler.java:160)

"Service Thread" #21 daemon prio=9 os_prio=0 tid=0x00007fa0a489c800 nid=0x1d runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread1" #20 daemon prio=9 os_prio=0 tid=0x00007fa0a489a000 nid=0x1c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #19 daemon prio=9 os_prio=0 tid=0x00007fa0a4897800 nid=0x1b waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"elastic-apm-sampling-profiler" #18 daemon prio=5 os_prio=0 tid=0x00007fa0a4895800 nid=0x1a waiting on condition [0x00007fa08c6f7000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d45dd178> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"elastic-apm-weak-map-cleaner" #17 daemon prio=5 os_prio=0 tid=0x00007fa0a4860000 nid=0x19 waiting on condition [0x00007fa08c7f8000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d45cc3a8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"elastic-apm-circuit-breaker" #16 daemon prio=5 os_prio=0 tid=0x00007fa0a485e000 nid=0x18 waiting on condition [0x00007fa08c8f9000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at co.elastic.apm.agent.impl.circuitbreaker.CircuitBreaker.pollStressMonitors(CircuitBreaker.java:115)
	at co.elastic.apm.agent.impl.circuitbreaker.CircuitBreaker.access$000(CircuitBreaker.java:38)
	at co.elastic.apm.agent.impl.circuitbreaker.CircuitBreaker$1.run(CircuitBreaker.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"elastic-apm-remote-config-poller" #15 daemon prio=5 os_prio=0 tid=0x00007fa0a488d800 nid=0x17 waiting on condition [0x00007fa08c9fa000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d71ff8f8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at co.elastic.apm.agent.report.ApmServerClient.openUrlConnectionThreadSafely(ApmServerClient.java:161)
	at co.elastic.apm.agent.report.ApmServerClient.startRequestToUrl(ApmServerClient.java:124)
	at co.elastic.apm.agent.report.ApmServerClient.execute(ApmServerClient.java:241)
	at co.elastic.apm.agent.configuration.ApmServerConfigurationSource.fetchConfig(ApmServerConfigurationSource.java:163)
	at co.elastic.apm.agent.configuration.ApmServerConfigurationSource.pollConfig(ApmServerConfigurationSource.java:131)
	at co.elastic.apm.agent.configuration.ApmServerConfigurationSource.access$000(ApmServerConfigurationSource.java:53)
	at co.elastic.apm.agent.configuration.ApmServerConfigurationSource$1.run(ApmServerConfigurationSource.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"elastic-apm-server-reporter" #14 daemon prio=5 os_prio=0 tid=0x00007fa0a488c000 nid=0x16 waiting on condition [0x00007fa08cafb000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d71ff8f8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at co.elastic.apm.agent.report.ApmServerClient.openUrlConnectionThreadSafely(ApmServerClient.java:161)
	at co.elastic.apm.agent.report.ApmServerClient.startRequestToUrl(ApmServerClient.java:124)
	at co.elastic.apm.agent.report.ApmServerClient.startRequest(ApmServerClient.java:119)
	at co.elastic.apm.agent.report.AbstractIntakeApiHandler.startRequest(AbstractIntakeApiHandler.java:103)
	at co.elastic.apm.agent.report.IntakeV2ReportingEventHandler.startRequest(IntakeV2ReportingEventHandler.java:145)
	at co.elastic.apm.agent.report.IntakeV2ReportingEventHandler.handleEvent(IntakeV2ReportingEventHandler.java:95)
	at co.elastic.apm.agent.report.IntakeV2ReportingEventHandler.onEvent(IntakeV2ReportingEventHandler.java:73)
	at co.elastic.apm.agent.report.IntakeV2ReportingEventHandler.onEvent(IntakeV2ReportingEventHandler.java:44)
	at co.elastic.apm.agent.shaded.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
	at co.elastic.apm.agent.shaded.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
	at java.lang.Thread.run(Thread.java:748)

"elastic-apm-server-healthcheck" #13 daemon prio=5 os_prio=0 tid=0x00007fa0a487e800 nid=0x15 waiting for monitor entry [0x00007fa08cbfb000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:317)
	- waiting to lock <0x00000000d789deb8> (a org.apache.juli.ClassLoaderLogManager)
	at java.util.logging.LogManager.getLogManager(LogManager.java:378)
	at java.util.logging.Logger.getPlatformLogger(Logger.java:572)
	at java.util.logging.LoggingProxyImpl.getLogger(LoggingProxyImpl.java:41)
	at sun.util.logging.LoggingSupport.getLogger(LoggingSupport.java:100)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.<init>(PlatformLogger.java:602)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.<init>(PlatformLogger.java:597)
	at sun.util.logging.PlatformLogger.<init>(PlatformLogger.java:239)
	at sun.util.logging.PlatformLogger.getLogger(PlatformLogger.java:198)
	- locked <0x00000000d7e963d8> (a java.lang.Class for sun.util.logging.PlatformLogger)
	at sun.net.www.protocol.http.HttpURLConnection.<clinit>(HttpURLConnection.java:431)
	at sun.net.www.protocol.http.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.http.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:979)
	at co.elastic.apm.agent.report.ApmServerClient.openUrlConnectionThreadSafely(ApmServerClient.java:163)
	at co.elastic.apm.agent.report.ApmServerClient.startRequestToUrl(ApmServerClient.java:124)
	at co.elastic.apm.agent.report.ApmServerClient.executeForAllUrls(ApmServerClient.java:266)
	at co.elastic.apm.agent.report.ApmServerHealthChecker.call(ApmServerHealthChecker.java:69)
	at co.elastic.apm.agent.report.ApmServerHealthChecker.call(ApmServerHealthChecker.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"elastic-apm-type-cache-pool-cleaner" #12 daemon prio=5 os_prio=0 tid=0x00007fa0a46fc800 nid=0x14 waiting on condition [0x00007fa08cefd000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d48d60b0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"elastic-apm-metrics-reporter" #9 daemon prio=5 os_prio=0 tid=0x00007fa0a45ed800 nid=0x13 waiting on condition [0x00007fa08d267000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d4595058> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"elastic-apm-request-timeout-timer" #8 daemon prio=5 os_prio=0 tid=0x00007fa0a4551800 nid=0x12 in Object.wait() [0x00007fa08d568000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000d41bf6c8> (a java.util.TaskQueue)
	at java.lang.Object.wait(Object.java:502)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	- locked <0x00000000d41bf6c8> (a java.util.TaskQueue)
	at java.util.TimerThread.run(Timer.java:505)

"elastic-apm-configuration-reloader" #7 daemon prio=5 os_prio=0 tid=0x00007fa0a4527000 nid=0x11 waiting on condition [0x00007fa08d669000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d40e5138> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"Signal Dispatcher" #5 daemon prio=9 os_prio=0 tid=0x00007fa0a415b800 nid=0x10 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Surrogate Locker Thread (Concurrent GC)" #4 daemon prio=9 os_prio=0 tid=0x00007fa0a415a000 nid=0xf waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=0 tid=0x00007fa0a4127800 nid=0xe in Object.wait() [0x00007fa094523000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000d2a08ed0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	- locked <0x00000000d2a08ed0> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=0 tid=0x00007fa0a4124800 nid=0xd in Object.wait() [0x00007fa094624000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000d2a06bf8> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	- locked <0x00000000d2a06bf8> (a java.lang.ref.Reference$Lock)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=0 tid=0x00007fa0a400c000 nid=0x8 waiting for monitor entry [0x00007fa0ac336000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at sun.util.logging.PlatformLogger.redirectPlatformLoggers(PlatformLogger.java:209)
	- waiting to lock <0x00000000d7e963d8> (a java.lang.Class for sun.util.logging.PlatformLogger)
	at java.util.logging.LogManager$3.run(LogManager.java:402)
	at java.util.logging.LogManager$3.run(LogManager.java:396)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
	- locked <0x00000000d789deb8> (a org.apache.juli.ClassLoaderLogManager)
	at java.util.logging.LogManager.access$800(LogManager.java:145)
	at java.util.logging.LogManager$2.run(LogManager.java:345)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
	- locked <0x00000000d789deb8> (a org.apache.juli.ClassLoaderLogManager)
	at java.util.logging.LogManager.getLogManager(LogManager.java:378)
	at java.util.logging.Logger.demandLogger(Logger.java:448)
	at java.util.logging.Logger.getLogger(Logger.java:502)
	at org.apache.juli.logging.DirectJDKLog.<init>(DirectJDKLog.java:68)
	at org.apache.juli.logging.DirectJDKLog.getInstance(DirectJDKLog.java:188)
	at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:117)
	at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:141)
	at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:196)
	at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:52)

"VM Thread" os_prio=0 tid=0x00007fa0a411b000 nid=0xc runnable 

"Gang worker#0 (Parallel GC Threads)" os_prio=0 tid=0x00007fa0a401d000 nid=0x9 runnable 

"Gang worker#1 (Parallel GC Threads)" os_prio=0 tid=0x00007fa0a401f000 nid=0xa runnable 

"Concurrent Mark-Sweep GC Thread" os_prio=0 tid=0x00007fa0a404c800 nid=0xb runnable 

"VM Periodic Task Thread" os_prio=0 tid=0x00007fa0a489f800 nid=0x1e waiting on condition 

JNI global references: 321


Found one Java-level deadlock:
=============================
"elastic-apm-remote-config-poller":
  waiting for ownable synchronizer 0x00000000d71ff8f8, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "elastic-apm-server-healthcheck"
"elastic-apm-server-healthcheck":
  waiting to lock monitor 0x00007fa078004d78 (object 0x00000000d789deb8, a org.apache.juli.ClassLoaderLogManager),
  which is held by "main"
"main":
  waiting to lock monitor 0x00007fa078004118 (object 0x00000000d7e963d8, a java.lang.Class),
  which is held by "elastic-apm-server-healthcheck"

Java stack information for the threads listed above:
===================================================
"elastic-apm-remote-config-poller":
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000d71ff8f8> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at co.elastic.apm.agent.report.ApmServerClient.openUrlConnectionThreadSafely(ApmServerClient.java:161)
	at co.elastic.apm.agent.report.ApmServerClient.startRequestToUrl(ApmServerClient.java:124)
	at co.elastic.apm.agent.report.ApmServerClient.execute(ApmServerClient.java:241)
	at co.elastic.apm.agent.configuration.ApmServerConfigurationSource.fetchConfig(ApmServerConfigurationSource.java:163)
	at co.elastic.apm.agent.configuration.ApmServerConfigurationSource.pollConfig(ApmServerConfigurationSource.java:131)
	at co.elastic.apm.agent.configuration.ApmServerConfigurationSource.access$000(ApmServerConfigurationSource.java:53)
	at co.elastic.apm.agent.configuration.ApmServerConfigurationSource$1.run(ApmServerConfigurationSource.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"elastic-apm-server-healthcheck":
	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:317)
	- waiting to lock <0x00000000d789deb8> (a org.apache.juli.ClassLoaderLogManager)
	at java.util.logging.LogManager.getLogManager(LogManager.java:378)
	at java.util.logging.Logger.getPlatformLogger(Logger.java:572)
	at java.util.logging.LoggingProxyImpl.getLogger(LoggingProxyImpl.java:41)
	at sun.util.logging.LoggingSupport.getLogger(LoggingSupport.java:100)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.<init>(PlatformLogger.java:602)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.<init>(PlatformLogger.java:597)
	at sun.util.logging.PlatformLogger.<init>(PlatformLogger.java:239)
	at sun.util.logging.PlatformLogger.getLogger(PlatformLogger.java:198)
	- locked <0x00000000d7e963d8> (a java.lang.Class for sun.util.logging.PlatformLogger)
	at sun.net.www.protocol.http.HttpURLConnection.<clinit>(HttpURLConnection.java:431)
	at sun.net.www.protocol.http.Handler.openConnection(Handler.java:62)
	at sun.net.www.protocol.http.Handler.openConnection(Handler.java:57)
	at java.net.URL.openConnection(URL.java:979)
	at co.elastic.apm.agent.report.ApmServerClient.openUrlConnectionThreadSafely(ApmServerClient.java:163)
	at co.elastic.apm.agent.report.ApmServerClient.startRequestToUrl(ApmServerClient.java:124)
	at co.elastic.apm.agent.report.ApmServerClient.executeForAllUrls(ApmServerClient.java:266)
	at co.elastic.apm.agent.report.ApmServerHealthChecker.call(ApmServerHealthChecker.java:69)
	at co.elastic.apm.agent.report.ApmServerHealthChecker.call(ApmServerHealthChecker.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"main":
	at sun.util.logging.PlatformLogger.redirectPlatformLoggers(PlatformLogger.java:209)
	- waiting to lock <0x00000000d7e963d8> (a java.lang.Class for sun.util.logging.PlatformLogger)
	at java.util.logging.LogManager$3.run(LogManager.java:402)
	at java.util.logging.LogManager$3.run(LogManager.java:396)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:396)
	- locked <0x00000000d789deb8> (a org.apache.juli.ClassLoaderLogManager)
	at java.util.logging.LogManager.access$800(LogManager.java:145)
	at java.util.logging.LogManager$2.run(LogManager.java:345)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
	- locked <0x00000000d789deb8> (a org.apache.juli.ClassLoaderLogManager)
	at java.util.logging.LogManager.getLogManager(LogManager.java:378)
	at java.util.logging.Logger.demandLogger(Logger.java:448)
	at java.util.logging.Logger.getLogger(Logger.java:502)
	at org.apache.juli.logging.DirectJDKLog.<init>(DirectJDKLog.java:68)
	at org.apache.juli.logging.DirectJDKLog.getInstance(DirectJDKLog.java:188)
	at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:117)
	at org.apache.juli.logging.LogFactory.getInstance(LogFactory.java:141)
	at org.apache.juli.logging.LogFactory.getLog(LogFactory.java:196)
	at org.apache.catalina.startup.Bootstrap.<clinit>(Bootstrap.java:52)

Found 1 deadlock.
```
</details>

**Comment by eyalkoren** [comment]
See #1246 
Please try [this snapshot build](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-1262/5/artifacts/) and report back if this resolves the problem.

**Comment by pengpj** [comment]
efficient!  Thanks for you!
