### ISSUE TITLE
Add support for java.net.http.HttpClient

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#1278]
The new-ish built-in HTTP client that has been added in JDK 11

**Comment by vincentjames501** [comment]
This would be amazing as we've almost completely switched to this from Apache HttpClient!

**Comment by kananindzya** [comment]
hi @felixbarny, I try to implement this

**Comment by kananindzya** [comment]
@felixbarny I need advice, I try to instrument at first sync requests and getting errors bellow:
```
2020-07-22 03:40:03,208 [main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Type match for instrumentation HttpClient11Instrumentation: (name(equals(jdk.internal.net.http.HttpClientImpl)) and not(isInterface())) matches class jdk.internal.net.http.HttpClientImpl
2020-07-22 03:40:03,292 [main] DEBUG co.elastic.apm.agent.bci.ElasticApmAgent - Method match for instrumentation HttpClient11Instrumentation: ((name(equals(send)) and returns(erasure(name(equals(java.net.http.HttpResponse))))) and not(isAbstract())) matches public java.net.http.HttpResponse jdk.internal.net.http.HttpClientImpl.send(java.net.http.HttpRequest,java.net.http.HttpResponse$BodyHandler) throws java.io.IOException,java.lang.InterruptedException
2020-07-22 03:40:03,308 [main] INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - jdk.internal.net.http.HttpClientImpl refers to a missing class.
2020-07-22 03:40:03,308 [main] DEBUG co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - ByteBuddy type resolution stack trace: 
java.lang.IllegalStateException: Cannot resolve type description for co.elastic.apm.agent.impl.transaction.Span
	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:157) ~[byte-buddy-dep-1.10.12.jar:?]
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:912) ~[byte-buddy-dep-1.10.12.jar:?]
```

**Comment by felixbarny** [comment]
Could you create a draft PR for that? I'd also suggest creating this as an indy plugin `public boolean indyPlugin() { return true; }` if you haven't already.

**Comment by kananindzya** [comment]
Hi @felixbarny , thanks, this help me. 
Later I will create a draft PR.

**Comment by kananindzya** [comment]
After running tests I got exception in HttpClientRequestPropertyAccessor#setHeader, because HttpRequest headers is immutable:
```
2020-07-22 23:59:42,092 [main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to '' 00-4a513c826fe62e3063a5143c2e29ba0e-c9c6109b2a971d57-01 (1d6751e3) (5)
2020-07-22 23:59:42,092 [main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to 'GET localhost' 00-4a513c826fe62e3063a5143c2e29ba0e-27489d0819e5a66e-01 (6c075e9d) (2)
java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:72)
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.put(ImmutableCollections.java:731)
	at co.elastic.apm.agent.httpclient.HttpClientRequestPropertyAccessor.setHeader(HttpClientRequestPropertyAccessor.java:24)
	at co.elastic.apm.agent.httpclient.HttpClientRequestPropertyAccessor.setHeader(HttpClientRequestPropertyAccessor.java:11)
	at co.elastic.apm.agent.impl.transaction.TraceContext.propagateTraceContext(TraceContext.java:532)
	at co.elastic.apm.agent.impl.transaction.AbstractSpan.propagateTraceContext(AbstractSpan.java:533)
```
![image](https://user-images.githubusercontent.com/48118512/88211825-104f5d80-cc78-11ea-8632-3c1e752762dc.png)
