### ISSUE TITLE
Unable to install Elastic APM Agent

### ISSUE THREAD

**Issue by MandarGV** [elastic/apm-agent-java#1282]
Hi,
I am not able to install Elastic APM java agent on TOMCAT server.
----------------------------------------------------------------------------------------

```
Error:
Failed to start agent
java.lang.NullPointerException
        at co.elastic.apm.agent.bci.AgentMain.getAgentJarFile(AgentMain.java:160)
        at co.elastic.apm.agent.bci.AgentMain.init(AgentMain.java:91)
        at co.elastic.apm.agent.bci.AgentMain.premain(AgentMain.java:54)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Starting service Tomcat-Standalone
Apache Tomcat/4.0.6
Starting service Tomcat-Apache
Apache Tomcat/4.0.6
```

----------------------------------------------------------------------------------------
![APM Agent error](https://user-images.githubusercontent.com/68057654/87027932-7dd0a800-c1fb-11ea-9cd7-ff65732c5ccf.PNG)

![image](https://user-images.githubusercontent.com/68057654/87027760-44983800-c1fb-11ea-84c9-12b05db269f3.png)

**Comment by SylvainJuge** [comment]
Thanks for reporting this @MandarGV ,

While tomcat 4.x is really old (18 years!), the issue seems more related to running on Windows, did you tried doing the same on a Linux machine by chance ?

Also, it's quite likely that Servlet instrumentation won't work out of the box because it only supports Servlet API 3.x and beyond, however you should still be able to define transactions and spans using agent API or annotations.

I have opened a PR to get a more detailed cause, if you could try with [this snapshot ](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-1283/1/artifact/src/github.com/elastic/apm-agent-java/apm-agent-attach/target/apm-agent-attach-1.17.1-SNAPSHOT.jar) and provide us the output that would be great.

**Comment by MandarGV** [comment]
Hey SylvainJuge, I updated my Tomcat version and it worked fine.

Thanks a lot!!

Regards
Mandar

**Comment by SylvainJuge** [comment]
Just to be sure, did you updated your tomcat version or used the snapshot agent (or both) ?

**Comment by MandarGV** [comment]
I just updated the tomcat version.

**Comment by eyalkoren** [comment]
Closing this issue. Feel free to reopen if needed.
Thanks.
