### ISSUE TITLE
Null pointer exception in WeakConcurrentMap

### ISSUE THREAD

**Issue by blackat** [elastic/apm-agent-java#1309]
## Describe the bug
Just started WildFly 19 with the agent configured into `standalone.bat.conf`, then I login into the web application and I see the exception from the agent.

## Configuration

- WildFly 19.1.0.Final, Oracle JDK 11.0.7
- APM agent 1.17.0

The agent is so configured

```
set JAVA_OPTS=%JAVA_OPTS% -javaagent:elastic-apm-agent-1.17.0.jar
set JAVA_OPTS=%JAVA_OPTS% -Delastic.apm.service_name=my-app
set JAVA_OPTS=%JAVA_OPTS% -Delastic.apm.application_packages=com.blabla
set JAVA_OPTS=%JAVA_OPTS% -Delastic.apm.server_urls=http://localhost:8200
set JAVA_OPTS=%JAVA_OPTS% -Delastic.apm.disable_instrumentations=executor
```

## Expected behavior
To not see any exception.

I have also tried to add `set JAVA_OPTS=%JAVA_OPTS% -Delastic.apm.disable_instrumentations=executor` but it has not worked.

Do I have to exclude something else?

Stacktrace
```java
16:23:50,812 ERROR [stderr] (default task-9) java.lang.NullPointerException
16:23:50,813 ERROR [stderr] (default task-9) 	at co.elastic.apm.agent.shaded.weaklockfree.WeakConcurrentMap.put(WeakConcurrentMap.java:161)
16:23:50,813 ERROR [stderr] (default task-9) 	at co.elastic.apm.agent.shaded.weaklockfree.WeakConcurrentMap$WithInlinedExpunction.put(WeakConcurrentMap.java:387)
16:23:50,814 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//===omissis===
16:23:50,814 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//===omissis===$Proxy$_$$_WeldSubclass.get$$super(Unknown Source)
16:23:50,814 ERROR [stderr] (default task-9) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:23:50,814 ERROR [stderr] (default task-9) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:23:50,814 ERROR [stderr] (default task-9) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:23:50,815 ERROR [stderr] (default task-9) 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:23:50,815 ERROR [stderr] (default task-9) 	at org.jboss.weld.core@3.1.3.Final//org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
16:23:50,816 ERROR [stderr] (default task-9) 	at org.jboss.weld.core@3.1.3.Final//org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
16:23:50,816 ERROR [stderr] (default task-9) 	at org.jboss.jts//com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:174)
16:23:50,816 ERROR [stderr] (default task-9) 	at org.jboss.jts//com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:53)
16:23:50,817 ERROR [stderr] (default task-9) 	at org.jboss.jts//com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:88)
16:23:50,817 ERROR [stderr] (default task-9) 	at org.jboss.jts//com.arjuna.ats.jta.cdi.transactional.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:47)
16:23:50,819 ERROR [stderr] (default task-9) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:23:50,824 ERROR [stderr] (default task-9) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:23:50,825 ERROR [stderr] (default task-9) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:23:50,826 ERROR [stderr] (default task-9) 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:23:50,828 ERROR [stderr] (default task-9) 	at org.jboss.weld.core@3.1.3.Final//org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
16:23:50,829 ERROR [stderr] (default task-9) 	at org.jboss.weld.core@3.1.3.Final//org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
16:23:50,831 ERROR [stderr] (default task-9) 	at org.jboss.weld.core@3.1.3.Final//org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
16:23:50,837 ERROR [stderr] (default task-9) 	at org.jboss.weld.core@3.1.3.Final//org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
16:23:50,839 ERROR [stderr] (default task-9) 	at org.jboss.weld.core@3.1.3.Final//org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
16:23:50,841 ERROR [stderr] (default task-9) 	at org.jboss.weld.core@3.1.3.Final//org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
16:23:50,842 ERROR [stderr] (default task-9) 	at deployment.xxxx-xxx.war//=omissis=$Proxy$_$$_WeldSubclass.get(Unknown Source)
16:23:50,843 ERROR [stderr] (default task-9) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:23:50,844 ERROR [stderr] (default task-9) 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:23:50,844 ERROR [stderr] (default task-9) 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:23:50,845 ERROR [stderr] (default task-9) 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
16:23:50,845 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
16:23:50,846 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:535)
16:23:50,846 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:424)
16:23:50,846 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:385)
16:23:50,846 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:356)
16:23:50,847 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:387)
16:23:50,847 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:356)
16:23:50,848 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:329)
16:23:50,855 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
16:23:50,857 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
16:23:50,859 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
16:23:50,860 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:356)
16:23:50,860 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
16:23:50,861 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
16:23:50,861 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
16:23:50,862 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
16:23:50,862 ERROR [stderr] (default task-9) 	at org.jboss.resteasy.resteasy-jaxrs@3.11.2.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
16:23:50,862 ERROR [stderr] (default task-9) 	at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
16:23:50,863 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
16:23:50,863 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
16:23:50,864 ERROR [stderr] (default task-9) 	at io.opentracing.contrib.opentracing-jaxrs2//io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:52)
16:23:50,864 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
16:23:50,864 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
16:23:50,865 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
16:23:50,867 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
16:23:50,867 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
16:23:50,868 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
16:23:50,873 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
16:23:50,877 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
16:23:50,879 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
16:23:50,880 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
16:23:50,881 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
16:23:50,883 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
16:23:50,884 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
16:23:50,886 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
16:23:50,888 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
16:23:50,891 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
16:23:50,894 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
16:23:50,895 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
16:23:50,896 ERROR [stderr] (default task-9) 	at deployment.xxxxx-war.war//org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
16:23:50,897 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
16:23:50,898 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
16:23:50,898 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
16:23:50,899 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
16:23:50,899 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
16:23:50,900 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
16:23:50,901 ERROR [stderr] (default task-9) 	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
16:23:50,902 ERROR [stderr] (default task-9) 	at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:23:50,904 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
16:23:50,905 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
16:23:50,910 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
16:23:50,912 ERROR [stderr] (default task-9) 	at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:23:50,913 ERROR [stderr] (default task-9) 	at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
16:23:50,913 ERROR [stderr] (default task-9) 	at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
16:23:50,913 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
16:23:50,914 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
16:23:50,914 ERROR [stderr] (default task-9) 	at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
16:23:50,915 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
16:23:50,915 ERROR [stderr] (default task-9) 	at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
16:23:50,915 ERROR [stderr] (default task-9) 	at io.undertow.core@2.1.0.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
16:23:50,916 ERROR [stderr] (default task-9) 	at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:23:50,916 ERROR [stderr] (default task-9) 	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
16:23:50,917 ERROR [stderr] (default task-9) 	at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:23:50,919 ERROR [stderr] (default task-9) 	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
16:23:50,920 ERROR [stderr] (default task-9) 	at io.undertow.core@2.1.0.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
16:23:50,921 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
16:23:50,922 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
16:23:50,923 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
16:23:50,927 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
16:23:50,930 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
16:23:50,931 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
16:23:50,932 ERROR [stderr] (default task-9) 	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
16:23:50,933 ERROR [stderr] (default task-9) 	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
16:23:50,933 ERROR [stderr] (default task-9) 	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
16:23:50,934 ERROR [stderr] (default task-9) 	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
16:23:50,935 ERROR [stderr] (default task-9) 	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
16:23:50,936 ERROR [stderr] (default task-9) 	at org.wildfly.extension.undertow@19.1.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1541)
16:23:50,937 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
16:23:50,938 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
16:23:50,939 ERROR [stderr] (default task-9) 	at io.undertow.servlet@2.1.0.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
16:23:50,939 ERROR [stderr] (default task-9) 	at io.undertow.core@2.1.0.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:370)
16:23:50,939 ERROR [stderr] (default task-9) 	at io.undertow.core@2.1.0.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
16:23:50,940 ERROR [stderr] (default task-9) 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
16:23:50,940 ERROR [stderr] (default task-9) 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
16:23:50,941 ERROR [stderr] (default task-9) 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
16:23:50,941 ERROR [stderr] (default task-9) 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
16:23:50,941 ERROR [stderr] (default task-9) 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by felixbarny** [comment]
Hi and thanks for raising the issue.

This has been fixed already in https://github.com/elastic/apm-agent-java/pull/1249 and there's a new release with that fix: https://github.com/elastic/apm-agent-java/releases/tag/v1.18.0.RC1

**Comment by blackat** [comment]
WoW! Really thanks man 🥇
