### ISSUE TITLE
[automation] Release job error

### ISSUE THREAD

**Issue by cachedout** [elastic/apm-agent-java#1501]
The following was observed in the `Nexus Release` stage [of the release job](https://internal-ci.elastic.co/blue/organizations/jenkins/elastic%2Bapm-agent-java%2Bpost-release/detail/elastic%2Bapm-agent-java%2Bpost-release/18/pipeline/):

```
[2020-11-10T20:47:42.154Z] groovy.lang.MissingPropertyException: No such property: spid for class: groovy.lang.Binding

[2020-11-10T20:47:42.154Z] 	at groovy.lang.Binding.getVariable(Binding.java:63)

[2020-11-10T20:47:42.154Z] 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:270)

[2020-11-10T20:47:42.154Z] 	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:353)

[2020-11-10T20:47:42.154Z] 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:357)

[2020-11-10T20:47:42.154Z] 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:333)

[2020-11-10T20:47:42.154Z] 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:333)

[2020-11-10T20:47:42.154Z] 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:333)

[2020-11-10T20:47:42.154Z] 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:333)

[2020-11-10T20:47:42.154Z] 	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.getProperty(SandboxInvoker.java:29)

[2020-11-10T20:47:42.154Z] 	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)

[2020-11-10T20:47:42.154Z] 	at WorkflowScript.run(WorkflowScript:151)

[2020-11-10T20:47:42.154Z] 	at ___cps.transform___(Native Method)

[2020-11-10T20:47:42.154Z] 	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:74)

[2020-11-10T20:47:42.154Z] 	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)

[2020-11-10T20:47:42.154Z] 	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)

[2020-11-10T20:47:42.154Z] 	at sun.reflect.GeneratedMethodAccessor1359.invoke(Unknown Source)

[2020-11-10T20:47:42.154Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2020-11-10T20:47:42.154Z] 	at java.lang.reflect.Method.invoke(Method.java:498)

[2020-11-10T20:47:42.154Z] 	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)

[2020-11-10T20:47:42.154Z] 	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)

[2020-11-10T20:47:42.154Z] 	at com.cloudbees.groovy.cps.Next.step(Next.java:83)

[2020-11-10T20:47:42.154Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)

[2020-11-10T20:47:42.154Z] 	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)

[2020-11-10T20:47:42.154Z] 	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)

[2020-11-10T20:47:42.154Z] 	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)

[2020-11-10T20:47:42.154Z] 	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)

[2020-11-10T20:47:42.154Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)

[2020-11-10T20:47:42.154Z] 	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)

[2020-11-10T20:47:42.154Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)

[2020-11-10T20:47:42.154Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)

[2020-11-10T20:47:42.154Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)

[2020-11-10T20:47:42.154Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)

[2020-11-10T20:47:42.154Z] 	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)

[2020-11-10T20:47:42.154Z] 	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)

[2020-11-10T20:47:42.154Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[2020-11-10T20:47:42.154Z] 	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:136)

[2020-11-10T20:47:42.154Z] 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)

[2020-11-10T20:47:42.154Z] 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)

[2020-11-10T20:47:42.154Z] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

[2020-11-10T20:47:42.154Z] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[2020-11-10T20:47:42.154Z] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

[2020-11-10T20:47:42.154Z] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

[2020-11-10T20:47:42.154Z] 	at java.lang.Thread.run(Thread.java:748)

[2020-11-10T20:47:42.155Z] Finished: FAILURE
```

**Comment by cachedout** [comment]
Fixed via https://github.com/elastic/apm-pipeline-library/pull/852
