### ISSUE TITLE
DispatcherType is not available for libraries built for Java 5

### ISSUE THREAD

**Issue by royteeuwen** [elastic/apm-agent-java#1802]
We use a framework in Java 11 that still references a jar built in Java5. In Java 5 the DispatcherType did not exist yet: https://docs.oracle.com/javaee/5/api/javax/servlet/http/HttpServletRequest.html

Would it be possible to update the following code so that it would also work for those libraries? Our logs are getting spammed with 

```
java.lang.AbstractMethodError: Receiver class com.day.cq.contentsync.impl.handler.util.FakeRequest does not define or inherit an implementation of the resolved method abstract getDispatcherType()Ljavax/servlet/DispatcherType; of interface javax.servlet.ServletRequest.
at javax.servlet.ServletRequestWrapper.getDispatcherType(ServletRequestWrapper.java:456)
at javax.servlet.ServletRequestWrapper.getDispatcherType(ServletRequestWrapper.java:456)
at javax.servlet.ServletRequestWrapper.getDispatcherType(ServletRequestWrapper.java:456)
at javax.servlet.ServletRequestWrapper.getDispatcherType(ServletRequestWrapper.java:456)
at javax.servlet.ServletRequestWrapper.getDispatcherType(ServletRequestWrapper.java:456)
at javax.servlet.ServletRequestWrapper.getDispatcherType(ServletRequestWrapper.java:456)
at javax.servlet.ServletRequestWrapper.getDispatcherType(ServletRequestWrapper.java:456)
at co.elastic.apm.agent.servlet.ServletApiAdvice.onEnterServletService(ServletApiAdvice.java:97)
```

Line of code producing the error:

https://github.com/elastic/apm-agent-java/blob/04ae148b9e1790451cc276f8e077ac166edbfcb1/apm-agent-plugins/apm-servlet-plugin/src/main/java/co/elastic/apm/agent/servlet/ServletApiAdvice.java#L97

**Comment by eyalkoren** [comment]
It is not a problem with the Java version, it is the JavaEE version that is incompatible, more specifically, the Servlet API version in JavaEE 5, which is 2.5, while we support only [Servlet API 3 or higher](https://www.elastic.co/guide/en/apm/agent/java/current/supported-technologies-details.html#supported-web-frameworks). 
What you found is not the only place of incompatibility, it's only the first one encountered at runtime, so it is not a matter of fixing this specific reference. Unfortunately, we do not intend to add support for it.
