### ISSUE TITLE
NPE when use webflux

### ISSUE THREAD

**Issue by LeePui** [elastic/apm-agent-java#1869]
apm agent version : 1.24.0
spring cloud gateway version : 2.2.8

## Steps to reproduce

I use apm in spring cloud gateway，every time a request passes through the gateway, a npe is throw。
I found `co.elastic.apm.agent.impl.transaction.TraceContext.FROM_TRACE_CONTEXT_TEXT_HEADERS#asChildOf` has the following code , it need a request header : `tracestate`. 

                if (isValid) {
                    // as per spec, the tracestate header can be multi-valued
                    traceContextHeaderGetter.forEach(TRACESTATE_HEADER_NAME, carrier, child, TRACESTATE_HEADER_CONSUMER);
                }
I try to set the request header myself，it will not report an error。
Do I need to set up this request header myself？
## Debug logs

> java.lang.NullPointerException
	at co.elastic.apm.agent.springwebflux.HeaderGetter.forEach(HeaderGetter.java:44)
	at co.elastic.apm.agent.springwebflux.HeaderGetter.forEach(HeaderGetter.java:33)
	at co.elastic.apm.agent.impl.transaction.TraceContext$4.asChildOf(TraceContext.java:155)
	at co.elastic.apm.agent.impl.transaction.TraceContext$4.asChildOf(TraceContext.java:132)
	at co.elastic.apm.agent.impl.transaction.Transaction.start(Transaction.java:125)
	at co.elastic.apm.agent.impl.ElasticApmTracer.startChildTransaction(ElasticApmTracer.java:191)
	at co.elastic.apm.agent.impl.ElasticApmTracer.startChildTransaction(ElasticApmTracer.java:182)
	at co.elastic.apm.agent.impl.GlobalTracer.startChildTransaction(GlobalTracer.java:94)
	at co.elastic.apm.agent.springwebflux.WebfluxHelper.getOrCreateTransaction(WebfluxHelper.java:59)
	at co.elastic.apm.agent.springwebflux.DispatcherHandlerInstrumentation$HandleAdvice.onEnter(DispatcherHandlerInstrumentation.java:77)
	at org.springframework.web.reactive.DispatcherHandler.handle(DispatcherHandler.java:139)

<details>
<summary>Click to expand</summary>

```
replace this line with your debug logs
```
</details>

**Comment by SylvainJuge** [comment]
Hi @LeePui , this is definitely a bug, thanks a lot for reporting this !

**Comment by SylvainJuge** [comment]
Hi @LeePui , I've opened a bugfix PR for this issue, you can try [this snapshot](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-1871/1/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.24.1-SNAPSHOT.jar) to confirm if it properly fixes your issue.

**Comment by LeePui** [comment]
> Hi @LeePui , I've opened a bugfix PR for this issue, you can try [this snapshot](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-1871/1/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.24.1-SNAPSHOT.jar) to confirm if it properly fixes your issue.

Yes, there will be no more NPE exceptions.
But there is another problem : i found the webflux transaction name is : `POST unknown route`, I checked the documents and found that when `use_path_as_transaction_name`  it mean :
> If set to true, transaction names of unsupported Servlet API-based frameworks will be in the form of $method $path instead of just $method unknown route.
but webflux isn't already a supported framework?

**Comment by SylvainJuge** [comment]
Hi @LeePui ,

This issue has been closed as the related PR #1871 has just been merged (and will be included in next release)

Regarding your issue with `POST unknown route` transactions, could you open a separate issue so we can properly handle it ?

There are a few cases where this could happen (both with functional & annotated variants), what would really help to diagnose this is to provide a "wireframe implementation" of your application (at least the part that implements this transaction) and what is the name that you'd expect in this case.
