### ISSUE TITLE
This will lock my program and cpu over 100% 

### ISSUE THREAD

**Issue by MJorcen** [elastic/apm-agent-java#1884]
This will lock my program and cpu over 100% 
 
 jstack
`	at co.elastic.apm.agent.bci.ElasticApmAgent.ensureInstrumented(ElasticApmAgent.java:694)
	- waiting to lock <0x00000005c9a7a690> (a java.lang.Class for co.elastic.apm.agent.bci.ElasticApmAgent)` 
`	at co.elastic.apm.agent.bci.ElasticApmAgent.ensureInstrumented(ElasticApmAgent.java:694)
	- waiting to lock <0x00000005c9a7a690> (a java.lang.Class for co.elastic.apm.agent.bci.ElasticApmAgent)` 
`	at co.elastic.apm.agent.bci.ElasticApmAgent.ensureInstrumented(ElasticApmAgent.java:694)
	- waiting to lock <0x00000005c9a7a690> (a java.lang.Class for co.elastic.apm.agent.bci.ElasticApmAgent)` 

-- waiting to lock * 100+

detail:
co.elastic.apm.agent.bci.ElasticApmAgent#ensureInstrumented

![image](https://user-images.githubusercontent.com/6092758/123264354-86b1ab00-d52c-11eb-99b0-3aa8cdafb4a5.png)

is less line ? 

![image](https://user-images.githubusercontent.com/6092758/123264468-a77a0080-d52c-11eb-9850-a994ad469500.png)

**Comment by SylvainJuge** [comment]
Hi @MJorcen can you provide a bit more details on when this issue appears ?
- What is agent configuration ? Are you using `trace_methods` by any chance ?
- Can you provide agent debug logs by adding `-Dlog_level=debug` to your JVM parameters ?
- Can you provide the complete `jstack` or thread dump output ?

**Comment by MJorcen** [comment]
# java	-version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

jvm 
"-Xms6048m","-Xmn4048m","-Xmx6048m","-XX:SurvivorRatio=10","-XX:-UseAdaptiveSizePolicy","-XX:MetaspaceSize=256M","-XX:-UseAdaptiveSizePolicy","-XX:+HeapDumpOnOutOfMemoryError","-XX:HeapDumpPath=/host_tmp/,"-XX:+PrintGC","-XX:+PrintGCDetails","-XX:+PrintHeapAtGC","-XX:+PrintGCApplicationStoppedTime","-XX:+PrintGCApplicationConcurrentTime","-Xloggc:/gc.log","-Djava.security.egd=file:/dev/./urandom","-jar","/boot.jar","--spring.profiles.active=${PROFILES_ACTIVE}","-javaagent:/elastic-apm-agent.jar"

evn:
ELASTIC_APM_SERVER_URLS: http://elasticsearch-xxx.xxxx:8200
ELASTIC_APM_SECRET_TOKEN: xxxxxx
ELASTIC_APM_SERVICE_NAME: xxxxx
ELASTIC_APM_ENVIRONMENT: prod
ELASTIC_APM_APPLICATION_PACKAGES: com.xxx
ELASTIC_APM_TRANSACTION_IGNORE_URLS: /xxx/*,/xxx/*
ELASTIC_APM_STACK_TRACE_LIMIT: 0
ELASTIC_APM_CAPTURE_BODY: all
ELASTIC_APM_CAPTURE_HEADERS: false
ELASTIC_APM_TRANSACTION_SAMPLE_RATE: 0.001
ELASTIC_APM_SPAN_FRAMES_MIN_DURATION: 30ms

**Comment by MJorcen** [comment]
[smiple.log](https://github.com/elastic/apm-agent-java/files/6724819/smiple.log)
this is simple log ,

**Comment by MJorcen** [comment]
the running thread

"http-nio-10114-exec-26" #219 daemon prio=5 os_prio=0 tid=0x00007f897401b000 nid=0xdf runnable [0x00007f88a9ebe000]
   java.lang.Thread.State: RUNNABLE
    at co.elastic.apm.agent.shaded.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
    at co.elastic.apm.agent.shaded.asm.MethodWriter.visitMaxs(MethodWriter.java:1546)
    at co.elastic.apm.agent.shaded.asm.MethodVisitor.visitMaxs(MethodVisitor.java:772)
    at co.elastic.apm.agent.shaded.asm.MethodVisitor.visitMaxs(MethodVisitor.java:772)
    at co.elastic.apm.agent.shaded.bytebuddy.asm.Advice$AdviceVisitor.visitMaxs(Advice.java:9912)
    at co.elastic.apm.agent.shaded.asm.ClassReader.readCode(ClassReader.java:2636)
    at co.elastic.apm.agent.shaded.asm.ClassReader.readMethod(ClassReader.java:1488)
    at co.elastic.apm.agent.shaded.asm.ClassReader.accept(ClassReader.java:718)
    at co.elastic.apm.agent.shaded.asm.ClassReader.accept(ClassReader.java:401)
    at co.elastic.apm.agent.shaded.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForInlining.create(TypeWriter.java:3827)
    at co.elastic.apm.agent.shaded.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2166)
    at co.elastic.apm.agent.shaded.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:224)
    at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:10327)
    at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10263)
    at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1600(AgentBuilder.java:10029)
    at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10648)
    at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:10595)
    at java.security.AccessController.doPrivileged(Native Method)
    at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:10186)
    at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
    at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
    at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
    at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
    at sun.reflect.GeneratedMethodAccessor515.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Dispatcher$ForJava6CapableVm.retransformClasses(AgentBuilder.java:6869)
    at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector$ForRetransformation.doApply(AgentBuilder.java:7148)
    at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy$Collector.apply(AgentBuilder.java:6993)
    at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$RedefinitionStrategy.apply(AgentBuilder.java:4855)
    at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default.doInstall(AgentBuilder.java:9463)
    at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default.installOn(AgentBuilder.java:9384)
    at co.elastic.apm.agent.shaded.bytebuddy.agent.builder.AgentBuilder$Default$Delegator.installOn(AgentBuilder.java:10986)
    at co.elastic.apm.agent.bci.ElasticApmAgent.ensureInstrumented(ElasticApmAgent.java:725)
    - locked <0x00000005c9a7a690> (a java.lang.Class for co.elastic.apm.agent.bci.ElasticApmAgent)
    at co.elastic.apm.agent.bci.DynamicTransformerImpl.ensureInstrumented(DynamicTransformerImpl.java:36)
    at co.elastic.apm.agent.concurrent.JavaConcurrent.captureContext(JavaConcurrent.java:113)
    at co.elastic.apm.agent.concurrent.JavaConcurrent.withContext(JavaConcurrent.java:136)
    at co.elastic.apm.agent.concurrent.ExecutorInstrumentation$ExecutorCallableInstrumentation.onSubmit(ExecutorInstrumentation.java:156)
    at java.lang.invoke.LambdaForm$DMH/285377351.invokeStatic_LL_L(LambdaForm$DMH)
    at java.lang.invoke.LambdaForm$MH/1833848849.linkToTargetMethod(LambdaForm$MH)
    at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:132)
    at com.zaxxer.hikari.pool.HikariPool.addBagItem(HikariPool.java:339)
    at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:140)
    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:180)
    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
    at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:158)
    at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:116)
    at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:79)
    at org.mybatis.spring.transaction.SpringManagedTransaction.openConnection(SpringManagedTransaction.java:82)
    at org.mybatis.spring.transaction.SpringManagedTransaction.getConnection(SpringManagedTransaction.java:68)
    at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:336)
    at org.apache.ibatis.executor.SimpleExecutor.prepareStatement(SimpleExecutor.java:85)
    at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
    at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
    at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
    at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
    at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
    at sun.reflect.GeneratedMethodAccessor526.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
    at com.sun.proxy.$Proxy168.selectList(Unknown Source)
    at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
    at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
    at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
    at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:58)
    at com.sun.proxy.$Proxy231.select(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor666.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
    at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
    at com.sun.proxy.$Proxy232.select(Unknown Source)
    at com.xxxx.someBiz
    at com.xxxx.someBiz
    at com.xxxx.someBiz
    at com.xxxx.someBiz
    at com.xxxx.someBiz$$FastClassBySpringCGLIB$$fc4f7b7b.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
    at org.springframework.validation.beanvalidation.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:119)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
    at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:100)
    at com.xxxx.someBiz
    at com.xxxx.someBiz
    at sun.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:644)
    at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:633)
    at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
    at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
    at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
    at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
    at com.xxxx.someBiz$$EnhancerBySpringCGLIB$$34334e07.get(<generated>)
    at sun.reflect.GeneratedMethodAccessor641.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
    at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
    at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
    at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:645)
    at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
    at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at com.xxxx.commons.filter.RestApiFilter.safeFilter(RestApiFilter.java:62)
    at com.xxxx.commons.filter.RestApiFilter.doFilter(RestApiFilter.java:49)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
    at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    - locked <0x00000005cfbc08d0> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
    - <0x00000005d06db6e0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by MJorcen** [comment]
![image](https://user-images.githubusercontent.com/6092758/123611305-0e9cfb00-d834-11eb-9d8a-b81018e79df2.png)
Can I do this .
I try to fix it and wait for the problem to recur .

**Comment by MJorcen** [comment]
I try to fix it and add adding -Dlog_level=debug  .
Now it's waiting to happen again

If I change to this, what bad things will happen ?
![image](https://user-images.githubusercontent.com/6092758/123616585-03989980-d839-11eb-9405-83b5e3bbd5ed.png)

**Comment by SylvainJuge** [comment]
Hi @MJorcen ,

The global lock on `ElasticApmAgent.class` is here to ensure that there is at most a single concurrent execution of this method.
Relying on the class that is being instrumented (`classToInstrument`) is not enough as it might trigger classloading and thus nested calls to `ensureInstrumented`. While it could appear to reduce your issue in this case, we would not be able to apply this generally.

Just to be sure, which version of the agent are you using here ? Please note that we recently changed our OSS header, thus there might be a +5/-5 line offset between the lines in the stack dump and the current state of `master` branch.
Also, as of version 1.23.0 we avoid re-computing stack frames for Java 7+ code (see [changelog](https://github.com/elastic/apm-agent-java/blob/master/CHANGELOG.asciidoc#1230---20210422))

One possible hypothesis here is that the instrumentation of a single class within the JDK by the `concurent` plugin is taking way more time than usual.

From this part in the stack:
```
at co.elastic.apm.agent.shaded.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610)
...
at co.elastic.apm.agent.bci.ElasticApmAgent.ensureInstrumented(ElasticApmAgent.java:725)
- locked <0x00000005c9a7a690> (a java.lang.Class for co.elastic.apm.agent.bci.ElasticApmAgent)
at co.elastic.apm.agent.bci.DynamicTransformerImpl.ensureInstrumented(DynamicTransformerImpl.java:36)
at co.elastic.apm.agent.concurrent.JavaConcurrent.captureContext(JavaConcurrent.java:113)
at co.elastic.apm.agent.concurrent.JavaConcurrent.withContext(JavaConcurrent.java:136)
at co.elastic.apm.agent.concurrent.ExecutorInstrumentation$ExecutorCallableInstrumentation.onSubmit(ExecutorInstrumentation.java:156)
at java.lang.invoke.LambdaForm$DMH/285377351.invokeStatic_LL_L(LambdaForm$DMH)
at java.lang.invoke.LambdaForm$MH/1833848849.linkToTargetMethod(LambdaForm$MH)
at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:132)
at com.zaxxer.hikari.pool.HikariPool.addBagItem(HikariPool.java:339)
...
```

We see that :
- HikariCP delegates task execution to a standard `ExecutorService`
- our instrumentation calls `ensureInstrumented` on the task to propagate context
- other parts upper in the stack are related to byte-buddy/ASM recomputing frames, which is likely the most expensive part of instrumentation.

Thus here, it seems to me that it could be something that was fixed with 1.23.0 as the class that is being instrumented is within the JDK and should already be compiled to Java 8 bytecode, thus no stack-frame re-computation is required.

Could you just confirm which version of the agent you are using here ? If it's not 1.24.0, then try updating first.

Also, how frequently does this issue happens ? Does it happen on every app start ? 50% of the time or less ?

**Comment by MJorcen** [comment]
Yes, most of this is when it starts and It happened in version 1.18.0 

When I changed the code on 1.24.0, it didn't appear again. Maybe you have fixed it. Thank you.

You are great 😘

**Comment by SylvainJuge** [comment]
Thanks a lot for your feedback @MJorcen ! That definitely helps as those issues are quite hard to reproduce in the field.
