### ISSUE TITLE
CXFServletExt#doPost generate 500 when INSERT to DB2

### ISSUE THREAD

**Issue by lk95jofr** [elastic/apm-agent-java#197]
We are currently using elastic-apm-agent-0.6.2.jar which works fine, collects data from our postgres and DB2 calls.

We wanted to try a new agent and installed, elastic-apm-agent-0.7.0-20180910.093339-71.jar, which resulted in a lot off 500's

How and why I cant actually understand from reading the logs.
I just see that before and after the result is totally different

```xml
Response-Code: 500
Encoding: UTF-8
Content-Type: text/xml
Headers: {}
Payload: <env:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Header/><env:Body><env:Fault xmlns:soap="http://schemas
.xmlsoap.org/soap/envelope/">
   <faultcode xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/">ns1:Server</faultcode>
   <faultstring>Unexpected error</faultstring>
   <detail>
      <LoginExceptionData xmlns="http://our-domain.se/our-login-path/data/v1_0" xmlns:ns2="http://our-domain.se/our-common-element-1/data/v4_6" xmlns:ns3="http://our-domain.se/our-common-element-2/data/v4_6">
         <Errormessage>(class: com/ibm/db2/jcc/am/CallableStatement, method: execute signature: ()Z) Illegal type in constant pool</Errormessage>
      </LoginExceptionData>
   </detail>
</env:Fault></env:Body></env:Envelope>
```

In the APM part of elastiic we did get two new requests
MetricsStreamServlet#doGet
CXFServletExt#doPost

It is the CXFServletExt#doPost that returns 500, it seems to be at time of INSERT

/Fredrik

**Comment by felixbarny** [comment]
Thanks for the report!

This looks interesting:
> class: com/ibm/db2/jcc/am/CallableStatement, method: execute signature: ()Z) Illegal type in constant pool

That sounds like a problem in Byte Buddy. I have now updated to the most recent version. Hopefully, that fixes your issue. Here is a current snapshot: [elastic-apm-agent-0.7.0-SNAPSHOT.jar.zip](https://github.com/elastic/apm-agent-java/files/2370509/elastic-apm-agent-0.7.0-SNAPSHOT.jar.zip)


For reference, could you tell me the exact artifact and version of the class `com/ibm/db2/jcc/am/CallableStatement`?

**Comment by felixbarny** [comment]
> In the APM part of elastiic we did get two new requests
MetricsStreamServlet#doGet
CXFServletExt#doPost

Is that something you appreciate or dislike?

**Comment by lk95jofr** [comment]
At startup logs

2018-09-11 11:06:20,016 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 31) WFLYJCA0004: Deploying JDBC-compliant driver class com.ib
m.db2.jcc.DB2Driver (version 3.69)
2018-09-11 11:06:20,020 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-3) WFLYJCA0018: Started Driver service with driver-name = ibm

wildfly import some modules at startup and ibm is one of the base once
<module xmlns="urn:jboss:module:1.3" name="ibm.jdk">
    <resources>

    </resources>
    <dependencies>
        <system export="true">
            <paths>
                <path name="com/ibm"/>
                <path name="com/ibm/crypto"/>
                <path name="com/ibm/crypto/provider"/>
                <path name="com/ibm/jvm"/>
                <path name="com/ibm/jvm/io"/>
                <path name="com/ibm/jvm/util"/>
                <path name="com/ibm/math"/>
                <path name="com/ibm/misc"/>
                <path name="com/ibm/misc/resources"/>
                <path name="com/ibm/net"/>
                <path name="com/ibm/nio"/>
                <path name="com/ibm/nio/ch"/>
                <path name="com/ibm/security/auth"/>
                <path name="com/ibm/security/auth/callback"/>
                <path name="com/ibm/security/auth/login"/>
                <path name="com/ibm/security/auth/module"/>
                <path name="com/ibm/security/bootstrap"/>
                <path name="com/ibm/security/util"/>
            </paths>
        </system>
    </dependencies>
</module>


and our system import the ibm jars
db2jcc-10.5-3.69.24.jar
db2jcc_licence_cisuz-10.5-3.69.24.jar

<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.3" name="com.ibm.db2">
    <resources>
        <resource-root path="." />
        <resource-root path="db2jcc-10.5-3.69.24.jar" />
        <resource-root path="db2jcc_licence_cisuz-10.5-3.69.24.jar" />
    </resources>
    <dependencies>
        <module name="javax.api" />
        <module name="javax.transaction.api" />
        <module name="se.our-domain.utilities.database" />
        <module name="sun.jdk" export="true" />
    </dependencies>
</module>

**Comment by lk95jofr** [comment]
I don't know. I never got a chance to look at it because our test system wasn't accessible after that :)

**Comment by felixbarny** [comment]
> and our system import the ibm jars
db2jcc-10.5-3.69.24.jar
db2jcc_licence_cisuz-10.5-3.69.24.jar

Thanks, that is very useful!

Have you already had the chance to try out the snapshot build I have attached in my previous comment?

**Comment by felixbarny** [comment]
For reference, an excerpt from `com/ibm/db2/jcc/am/CallableStatement`'s constant pool:

```
   #431 = Utf8               execute
   #432 = Utf8               ()Z
```

**Comment by lk95jofr** [comment]
No I haven't yet. I don't want to disturb our developers too much
Probably tomorrow I can test it.

**Comment by felixbarny** [comment]
It might also be worth trying out the corresponding JDBC 4 compatible driver, which would be `db2jcc4-10.5-4.19.26.jar`. See http://www-01.ibm.com/support/docview.wss?uid=swg21363866.

**Comment by lk95jofr** [comment]
We tried this mornig with elastic-apm-agent-0.7.0.jar and got the same error.

I also see this at start up, which releates to -Delastic.apm.application_packages where we have specified our.domain
-Delastic.apm.application_packages=our.domain


2018-09-13 09:54:15,554 ERROR [org.jboss.as.controller.management-operation] (default task-17) WFLYCTL0013: Operation ("read-attribute") failed - address: ([
    ("subsystem" => "datasources"),
    ("xa-data-source" => "ourDS")
]) - failure description: "WFLYCTL0216: Management resource '[(\"subsystem\" => \"datasources\")]' not found"
2018-09-13 09:54:15,576 ERROR [our.domain.server.monitoring.MetricsServlet] (default task-17) Failed to register database metrics.: javax.management.AttributeNotFoundException: "WFLYCTL0216: Management resource '[(\"subsystem\" => \"datasources\")]' not found"
        at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:310)
        at org.jboss.as.jmx.model.ModelControllerMBeanHelper.getAttribute(ModelControllerMBeanHelper.java:268)
        at org.jboss.as.jmx.model.ModelControllerMBeanServerPlugin.getAttribute(ModelControllerMBeanServerPlugin.java:133)
        at org.jboss.as.jmx.PluggableMBeanServerImpl.getAttribute(PluggableMBeanServerImpl.java:388)
        at our.domain.server.monitoring.DatasourceMBeans.__AW_addDatabaseMetrics(DatasourceMBeans.java:103) [classes:]
        at our.domain.server.monitoring.DatasourceMBeans.addDatabaseMetrics(DatasourceMBeans.java) [classes:]
        at our.domain.server.monitoring.MetricsServlet.init(MetricsServlet.java:44) [classes:]
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
        at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:250) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.core.ManagedServlet.getServlet(ManagedServlet.java:171) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.ServletHandler.__AW_handleRequest(ServletHandler.java:84) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.__AW_handleRequest(AuthenticationMechanismsHandler.java:60) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.security.handlers.NotificationReceiverHandler.__AW_handleRequest(NotificationReceiverHandler.java:50) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at org.wildfly.mod_cluster.undertow.metric.RunningRequestsHttpHandler.handleRequest(RunningRequestsHttpHandler.java:69)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.__AW_handleFirstRequest(ServletInitialHandler.java:292) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104) [undertow-servlet-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:202) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.server.HttpServerExchange$1.__AW_run(HttpServerExchange.java:805) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java) [undertow-core-1.4.0.Final.jar:1.4.0.Final]
        at java.util.concurrent.ThreadPoolExecutor.__AW_runWorker(ThreadPoolExecutor.java:1149) [rt.jar:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java) [rt.jar:1.8.0_181]

**Comment by lk95jofr** [comment]
The only reason I think it relates to -Delastic.apm.application_packages is that we specify that package, so no really good reason :)
Unfortunately I can't do that kind of test now (db2jcc4), it will be to much impact on our system.
If you think that will solve it I recommend you to close this and when I get to that change I will notify you.

**Comment by felixbarny** [comment]
I was wrong when saying the db2 driver was compiled for Java 5. It is actually compiled for Java 2(!).

When trying to instrument the class, I get this error from Byte Buddy:

```
java.lang.IllegalStateException: Cannot write type to constant pool for class file version Java 2
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor$Constraint$ForClassFileVersion.assertTypeInConstantPool(TypeWriter.java:2622)
	at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ValidatingClassVisitor$Constraint$Compound.assertTypeInConstantPool(TypeWriter.java:2764)
```

Not quite sure though why that affects your application. I would have assumed that this class is just not being instrumented so there should actually be no harm besides the fact that the JDBC instrumentation does not work.

I have also tried the more recent version (`db2jcc4`), which is compiled with the byte code level 50 (Java 6) and this error did not occur. So updating your JDBC driver should fix this.
