### ISSUE TITLE
Java agent v1.25.0 fails to start with Security Manager running on Tomcat 9.x

### ISSUE THREAD

**Issue by varunphadnis** [elastic/apm-agent-java#1971]
The Java agent v1.25.0 fails to start when integrated Tomcat 9.x **with Security Manager enabled**. Have tested it with both Java 8 and Java 11. 
Fails with the following error - 
```
[main] INFO co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.25.0 as my-cool-service on Java 11.0.11 Runtime version: 11.0.11+9-Ubuntu-0ubuntu2.18.04 VM version: 11.0.11+9-Ubuntu-0ubuntu2.18.04 (Ubuntu) Linux 5.4.0-80-generic 2021-08-12 18:55:24,297 
[main] INFO co.elastic.apm.agent.configuration.StartupInfo - service_name: 'my-cool-service' (source: Java System Properties) 2021-08-12 18:55:24,297 
[main] INFO co.elastic.apm.agent.configuration.StartupInfo - application_packages: 'mypackage' (source: Java System Properties) 
[elastic-apm-agent] ERROR Failed to start agent java.lang.reflect.InvocationTargetException 
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
  at java.base/java.lang.reflect.Method.invoke(Method.java:566) 
  at co.elastic.apm.agent.premain.AgentMain.loadAndInitializeAgent(AgentMain.java:149) 
  at co.elastic.apm.agent.premain.AgentMain.init(AgentMain.java:94) 
  at co.elastic.apm.agent.premain.AgentMain.premain(AgentMain.java:50) 
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
  at java.base/java.lang.reflect.Method.invoke(Method.java:566) 
  at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513) 
  at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525) 
Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Could not access Unsafe class: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks") 
  at co.elastic.apm.agent.bci.IndyBootstrap.getIndyBootstrapMethod(IndyBootstrap.java:215) 
  at co.elastic.apm.agent.bci.ElasticApmAgent.getTransformer(ElasticApmAgent.java:431) 
  at co.elastic.apm.agent.bci.ElasticApmAgent.applyAdvice(ElasticApmAgent.java:393) 
  at co.elastic.apm.agent.bci.ElasticApmAgent.initAgentBuilder(ElasticApmAgent.java:314) 
  at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:260) 
  at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:164) 
  at co.elastic.apm.agent.bci.ElasticApmAgent.initialize(ElasticApmAgent.java:150) 
  ... 13 more 
Caused by: java.lang.UnsupportedOperationException: Could not access Unsafe class: access denied ("java.lang.reflect.ReflectPermission" "suppressAccessChecks") 
  at co.elastic.apm.agent.shaded.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe$Dispatcher$Unavailable.defineClass(ClassInjector.java:2068) 
  at co.elastic.apm.agent.shaded.bytebuddy.dynamic.loading.ClassInjector$UsingUnsafe.injectRaw(ClassInjector.java:1802) 
  at co.elastic.apm.agent.bci.IndyBootstrap.initIndyBootstrap(IndyBootstrap.java:228) 
  at co.elastic.apm.agent.bci.IndyBootstrap.getIndyBootstrapMethod(IndyBootstrap.java:209) 
  ... 19 more
```

Have added the following permissions in catalina.policy but it still fails

```
grant codeBase "file:/opt/tomcat9/apm/elastic-apm-agent-1.25.0.jar" {
    permission java.security.AllPermission;
};
```

The issue seems to be introduced as part of changes for #1415 
Downgrading to version 1.18.1 works around issue.

**Comment by eyalkoren** [comment]
It actually doesn't look like it comes from #1468 (the fix for #1415), which isn't executed unless it's J9 AND JVM version >= 9. The strange thing is that it looks related to https://github.com/elastic/apm-agent-java/blame/master/apm-agent-core/src/main/java/co/elastic/apm/agent/bci/IndyBootstrap.java#L228, which was part of 1.18.0....

We'll have to consider how we can work around this issue.

**Comment by eyalkoren** [comment]
Apparently, recent Byte Buddy versions contained a too strict security measure that may have caused this issue.
Our agent already contains the latest Byte Buddy version, which includes a fix for that, but it was not yet released.
Please try our [latest snapshot](https://github.com/elastic/apm-agent-java#snapshots) and let us know whether the problem is resolved or not.
Thanks!

**Comment by varunphadnis** [comment]
The issue seems to be resolved on the snapshot version (elastic-apm-agent-1.25.1-20210816.094409-25.jar). Tried it on Java 11.

**Comment by eyalkoren** [comment]
Thanks for confirming! 
Whenever you feel your tests are concluded without reproducing the problem, please close the issue.

**Comment by eyalkoren** [comment]
@varunphadnis do you think it's safe to close this issue?

**Comment by SylvainJuge** [comment]
Closing issue for new, feel free to re-open/comment if needed.
