### ISSUE TITLE
Using JTE with APM agent throws Exception

### ISSUE THREAD

**Issue by spinscale** [elastic/apm-agent-java#2256]
## Describe the bug

When using the [JTE](https://jte.gg/) template language (which compiles java on the fly), compilation fails, once the apm agent is attached. I have a reproducible example in the below linked repo.

## Steps to reproduce

Check out the repository at https://github.com/spinscale/jte-apm-agent-bug and run `./gradlew run`

The sample code is running the same code snippet twice, but adding the agent in between

```java
class App {

    public static void main(String[] args) {
        {
            final TemplateEngine templateEngine = TemplateEngine.create(new DirectoryCodeResolver(Paths.get("src", "main", "resources")), ContentType.Html);
            System.out.println("before precompile all");
            templateEngine.precompileAll();
            System.out.println("after precompile all");
        }
        // uncommenting this will prevent the thrown exception below
        co.elastic.apm.attach.ElasticApmAttacher.attach();
        {
            final TemplateEngine templateEngine = TemplateEngine.create(new DirectoryCodeResolver(Paths.get("src", "main", "resources")), ContentType.Html);
            System.out.println("before precompile all");
            templateEngine.precompileAll();
            System.out.println("after precompile all");
        }
    }
}
```

This returns the following exception

```
before precompile all
after precompile all

Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2021-11-11 17:53:52,564 [Attach Listener] INFO  co.elastic.apm.agent.util.JmxUtils - Found JVM-specific OperatingSystemMXBean interface: com.sun.management.OperatingSystemMXBean
2021-11-11 17:53:52,583 [Attach Listener] INFO  co.elastic.apm.agent.configuration.StartupInfo - Starting Elastic APM 1.26.0 as App on Java 17.0.1 Runtime version: 17.0.1+12-LTS-39 VM version: 17.0.1+12-LTS-39 (Oracle Corporation) Mac OS X 11.6
2021-11-11 17:53:52,583 [Attach Listener] WARN  co.elastic.apm.agent.configuration.StartupInfo - To enable all features and decrease startup time, please configure application_packages
2021-11-11 17:53:54,345 [Attach Listener] INFO  co.elastic.apm.agent.impl.ElasticApmTracer - Tracer switched to RUNNING state
before precompile all
Exception in thread "main" gg.jte.TemplateException: Failed to compile template, error at
error: Bad service configuration file, or exception thrown while constructing Processor object: javax/annotation/processing/AbstractProcessor
1 error

        at gg.jte.compiler.java.JavaClassCompiler.runCompiler(JavaClassCompiler.java:49)
        at gg.jte.compiler.java.JavaClassCompiler.compile(JavaClassCompiler.java:37)
        at gg.jte.compiler.TemplateCompiler.precompileClasses(TemplateCompiler.java:157)
        at gg.jte.compiler.TemplateCompiler.precompile(TemplateCompiler.java:137)
        at gg.jte.compiler.TemplateCompiler.precompileAll(TemplateCompiler.java:84)
        at gg.jte.TemplateEngine.precompileAll(TemplateEngine.java:354)
        at App.main(App.java:21)
2021-11-11 17:53:54,393 [elastic-apm-circuit-breaker] INFO  co.elastic.apm.agent.impl.circuitbreaker.CircuitBreaker - Stopping the Circuit Breaker thread.
2021-11-11 17:53:54,393 [elastic-apm-remote-config-poller] ERROR co.elastic.apm.agent.configuration.ApmServerConfigurationSource - null
```

**Comment by SylvainJuge** [comment]
When testing locally, I can reproduce it, however after updating the `build.gradle` file with this to make it work in an IDE:

```
plugins {
    id 'application'
}

repositories {
    mavenCentral()
}

sourceCompatibility = '17'

dependencies {

    implementation 'gg.jte:jte:1.12.1'
    implementation 'co.elastic.apm:apm-agent-attach:1.27.1'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}

application {
    mainClass = 'App'
}
```

It seems to work and behave as expected, thus it looks like a dependency issue :thinking: .

**Comment by spinscale** [comment]
Using the latest and greatest agent also makes this work with my application without any compilation error on startup. Let's close this for now and re-open if this happens again.
