### ISSUE TITLE
Some questions about ClassCastException and missing class

### ISSUE THREAD

**Issue by LeePui** [elastic/apm-agent-java#2331]
Hi, I  use two agent in my springboot appliaction , one of them is apm, and the other agent is like skywalking.

  MyAgent enhanced `com.mysql.jdbc.PreparedStatement` , if i use  JVM option: `-javaagent:/path/to/MyAgent.jar -javaagent:/path/to/elastic-apm-agent-1.19.0.jar`, when i call `com.mysql.jdbc.PreparedStatement#executeLargeUpdate` ,  I start getting the following exception:
```
Caused by: java.lang.ClassCastException: com.mysql.jdbc.PreparedStatement cannot be cast to myAgent.interceptor.enhance.EnhancedInstance
	at myAgent.interceptor.enhance.InstMethodsInter.intercept(InstMethodsInter.java:66)
	at com.mysql.jdbc.PreparedStatement.setNull(PreparedStatement.java)
	at com.mysql.jdbc.PreparedStatement.setOneBatchedParameterSet(PreparedStatement.java:3782)
	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1544)
	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1253)
	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeBatch(DruidPooledPreparedStatement.java:565)
	... 109 common frames omitted
```
After i found [issue 1606](https://github.com/elastic/apm-agent-java/issues/1606), i add `-Delastic.apm.enable_type_pool_cache=false` , the application works fine.

  After i use JVM option: `-javaagent:/path/to/MyAgent.jar -javaagent:/path/to/elastic-apm-agent-1.27.0.jar`, no ClassCastException will be thrown, but i found some log:
```
INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - com.mysql.jdbc.JDBC4Connection refers to a missing class.
INFO  co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - com.mysql.jdbc.JDBC42PreparedStatement refers to a missing class
```

and apm will not collected jdbc or http data, only collect jvm data.

If i use JVM option: `-javaagent:/path/to/MyAgent.jar -javaagent:/path/to/elastic-apm-agent-1.26.0.jar`, ClassCastException will no be thrown and apm will collected all data.

Supplementary information：

- MyAgent‘s architecture is similar to skywalking，it ehanced JDBC and Httpclient framework.
- evert time i upgrade apm version, I will keep the bytebuddy version of my agent consistent with APM.

I don't know how all this is caused. Can you give me some troubleshooting suggestions， thanks.

**Comment by LeePui** [comment]
APM debug log:
```
DEBUG co.elastic.apm.agent.bci.bytebuddy.ErrorLoggingListener - ByteBuddy type resolution stack trace: 
net.bytebuddy.pool.TypePool$Resolution$NoSuchTypeException: Cannot resolve type description for com.mysql.jdbc.JDBC4Connection$auxiliary$0jTQnVVA
	at net.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:162) ~[?:?]
	at net.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1074) ~[?:?]
	at net.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:8301) ~[?:?]
	at net.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:618) ~[?:?]
	at net.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:336) ~[?:?]
	at net.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:7781) ~[?:?]
	at net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:48) ~[?:?]
	at net.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:27) ~[?:?]
	at net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:46) ~[?:?]
	at net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:50) ~[?:?]
	at net.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:29) ~[?:?]
	at net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:48) ~[?:?]
	at net.bytebuddy.matcher.MethodParameterTypeMatcher.matches(MethodParameterTypeMatcher.java:27) ~[?:?]
	at net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:48) ~[?:?]
	at net.bytebuddy.matcher.CollectionItemMatcher.matches(CollectionItemMatcher.java:26) ~[?:?]
	at net.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:46) ~[?:?]
	at net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:49) ~[?:?]
	at net.bytebuddy.matcher.MethodParametersMatcher.matches(MethodParametersMatcher.java:28) ~[?:?]
	at net.bytebuddy.matcher.ElementMatcher$Junction$Conjunction.matches(ElementMatcher.java:144) ~[?:?]
	at net.bytebuddy.matcher.FilterableList$AbstractBase.filter(FilterableList.java:125) ~[?:?]
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:506) ~[?:?]
	at net.bytebuddy.dynamic.scaffold.inline.RedefinitionDynamicTypeBuilder.make(RedefinitionDynamicTypeBuilder.java:204) ~[?:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doTransform(AgentBuilder.java:11741) ~[?:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11677) [?:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.access$1700(AgentBuilder.java:11395) [?:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:12069) [?:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer$LegacyVmDispatcher.run(AgentBuilder.java:12016) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.doPrivileged(AgentBuilder.java) [?:?]
	at net.bytebuddy.agent.builder.AgentBuilder$Default$ExecutingTransformer.transform(AgentBuilder.java:11584) [?:?]
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188) [?:1.8.0_211]
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428) [?:1.8.0_211]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) [?:1.8.0_211]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [?:1.8.0_211]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) [?:1.8.0_211]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) [?:1.8.0_211]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) [?:1.8.0_211]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) [?:1.8.0_211]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) [?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_211]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) [?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_211]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211]
	at java.lang.Class.forName(Class.java:264) [?:1.8.0_211]
	at com.mysql.jdbc.ConnectionImpl.<clinit>(ConnectionImpl.java:307) [mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330) [mysql-connector-java-5.1.45.jar:5.1.45]
```

**Comment by felixbarny** [comment]
If you disable your agent, does the 1.27.0 work as expected? If so, the Elastic APM Java agent seems to not have access to the auxiliary types (`com.mysql.jdbc.JDBC4Connection$auxiliary$0jTQnVVA`) that your agent creates.
How are you instrumenting these classes and in which class loader are the classes of your agent and the auxiliary types loaded from?

**Comment by LeePui** [comment]
Sorry for taking so long to reply to you. In fact, I don't know much about agent or bytebuddy... I can answer some questions, but I don't know whether I answered them clearly or correctly.
> If you disable your agent, does the 1.27.0 work as expected? 

 yes. In fact, using `-javaagent:/path/to/MyAgent.jar -javaagent:/path/to/elastic-apm-agent-1.27.0.jar` or `-javaagent:/path/to/MyAgent.jar -javaagent:/path/to/elastic-apm-agent-1.26.0.jar` has this exception : `net.bytebuddy.pool.TypePool$Resolution$NoSuchTypeException` , but only 1.27.0 cannot be collected jdbc or http data.

> How are you instrumenting these classes and in which class loader are the classes of your agent and the auxiliary types loaded from?

instrumenting like：
```
new AgentBuilder().type(() -> {
        ElementMatcher.Junction judge = new AbstractJunction<NamedElement>() {
            @Override
            public boolean matches(NamedElement target) {
                return nameMatchDefine.containsKey(target.getActualName());
            }
        };
        judge = judge.and(not(isInterface()));
        for (ByteKitPlugin define : signatureMatchDefine) {
            ClassMatch match = define.enhanceClass();
            if (match instanceof IndirectMatch) {
                judge = judge.or(((IndirectMatch) match).buildJunction());
            }
        }
        return new ProtectiveShieldMatcher(judge);
    })
```
My agent has enhanced many classes and method, such as : `com.mysql.jdbc.PreparedStatement#execute, #executeQuery, #executeLargeUpdate`, but only `executelargeupdate` will have this exception.
I think my agent use BootstrapClassLoader or AppClassLoader to load classes I'm not sure about that. I'll continue to understand the details.
