### ISSUE TITLE
Elastic apm-agent-attach:1.28.1  does not work with elasticsearch-rest-high-level-client:7.15.2

### ISSUE THREAD

**Issue by paulspeijers** [elastic/apm-agent-java#2353]
## Describe the bug
After upgrading from apm-agent-attach:1.20 to prevent the log4j vulnerability we got the following exceptions within the logs below this issue.

## Steps to reproduce
Directly after staring my Tomcat.

## Expected behavior
A running Tomcat

## Details
The problem is two conflicting dependencies:

elasticsearch-rest-high-level-client uses: org.elasticsearch.jna:5.7.0-1 which is is a version of net.java.dev.jna:5.7.0 which supports less operating systems, such as MacOS.

net.java.dev.jna uses version 5.3.1:

**Tried solutions**

1. Exclude org.elasticsearch.jna:

Does not work since its a shaded jar that contains more dependencies. Logs:

`The following profiles are active: referencedata [{}]
 java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/FilterProvider
java.lang.NoClassDefFoundError: Could not initialize class co.elastic.apm.agent.micrometer.MicrometerInstrumentati
 	at co.elastic.apm.agent.micrometer.MicrometerInstrumentation$AdviceClass.onExit(MicrometerInstrumentation.java:61)`

2. Exclude java.net.jna:
Does not work since org.elasticsearch.jna excludes a number of JNA platforms such as MacOs:

 

```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ser/FilterProvider
	at org.apache.logging.log4j.core.layout.JsonLayout.<init>(JsonLayout.java:158)
	at org.apache.logging.log4j.core.layout.JsonLayout.<init>(JsonLayout.java:69)
	at org.apache.logging.log4j.core.layout.JsonLayout$Builder.build(JsonLayout.java:102)
	at org.apache.logging.log4j.core.layout.JsonLayout$Builder.build(JsonLayout.java:77)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:579)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:651)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:668)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:253)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at co.elastic.apm.agent.springwebmvc.SpringServiceNameInstrumentation$SpringServiceNameAdvice.<clinit>(SpringServiceNameInstrumentation.java:69)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:330)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:327)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:229)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:211)
	at java.lang.ClassValue.get(ClassValue.java:117)
	at java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:351)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:341)
	at java.lang.invoke.DirectMethodHandle.internalMemberNameEnsureInit(DirectMethodHandle.java:291)
	at org.springframework.web.context.support.GenericWebApplicationContext.initPropertySources(GenericWebApplicationContext.java:196)
	at org.springframework.context.support.AbstractApplicationContext.prepareRefresh(AbstractApplicationContext.java:600)
	at org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext.prepareRefresh(AnnotationConfigServletWebServerApplicationContext.java:196)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:519)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at <hidden>.configuration.Application.main(Application.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ser.FilterProvider
	at co.elastic.apm.agent.premain.ShadedClassLoader.findClass(ShadedClassLoader.java:77)
```
</details>

**Comment by SylvainJuge** [comment]
Hi @paulspeijers we just shipped a new bugfix release `1.28.2`, and it includes a fix related to log4j which might be related to this.
Could you try to do an update of the agent and report if that makes a difference ?

Also, regarding potential issues with JNA, can you tell us which setup method did you used ? Are you using runtime attach either programmatic or through CLI or are you relying on the standard `-javaagent` option ?

**Comment by paulspeijers** [comment]
Hi @SylvainJuge I have the following mvn dependency:
`        <dependency>
            <groupId>co.elastic.apm</groupId>
            <artifactId>apm-agent-attach</artifactId>
            <version>1.28.2</version>
        </dependency>`

And within the code I attach to APM as follows within our Application.java annotated with @SpringBootApplication:

`  public static void main(String[] args) {
      ElasticApmAttacher.attach();
  }`

I'm trying to update the agent, but it does not seem to be published on some Maven repository. Do you know a repository in which it's included?

**Comment by SylvainJuge** [comment]
Actually JNA is an optional dependency of the `apm-agent-attach` artifact, thus you should be able to safely exclude it from your dependencies. If you are running with a JDK (and not a JRE), this would not have been required anyway. In practice it's only used on some JVMs that require using native API to attach the agent at runtime.

Can you try excluding it from `apm-agent-attach` transitive dependencies ?

While this should solve the issue with JNA, it might not fix the reported `ClassNotFoundException` exception reported above, but tell us anyway if that allows to use the new ES client.

**Comment by paulspeijers** [comment]
I did a test with 1.28.2 and got one same exception. I will try to test excluding JNA

**Comment by paulspeijers** [comment]
Hi Sylvian. When I exclude the JNDI dependencies on my MAC it works. However, on Linux (CentOS) it gives the following Exception:

`
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:597)
Caused by: java.lang.IllegalStateException: No compatible attachment provider is available
	at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:622)
	at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:293)
	at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:154)
	at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:140)
	at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:105)
	at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:58)
	at nl.ru.rdr.frontend.Application.main(Application.java:44)
	... 8 more
`

Wouldn't a good solution be that apm agent attach alignes the version of the JNA used with the elasticsearch-rest-high-level-client?

**Comment by SylvainJuge** [comment]
I think that there are two distinct issues here:
- the first stack trace that you reported relates to Log4j initialization, and that should not happen with `1.28.2` agent release.
- there might be a conflict with JNA, but it's just an hypothesis for now.

Also, the JNDI classes are already removed from log4j that is included in the agent.

I tested locally with a [test application](https://github.com/elastic/apm-agent-java/tree/master/integration-tests/runtime-attach/runtime-attach-app) that we use for integration testing and there wasn't any issue to start the application.
However with this test application is packaged as a "fat-jar" with all the dependencies flattened in a single jar.

Few other things to check:
- How do you test your application locally, is it from a packaged Jar or directly in the IDE ?
- How is your application packaged ? Is it using Spring boot packaging with nested jars ?

**Comment by SylvainJuge** [comment]
Also, trying to do the same with a sample Spring project does not seem to have any issue, however I am trying exclusively on Linux.

You can see the changes that I've done to add the agent + ES client [in this diff](https://github.com/SylvainJuge/gs-spring-boot/compare/main...SylvainJuge:add-elastic-apm-agent)

The Spring Boot packaging does not seems to be an issue, as we can see in the packaged both JNA dependencies are included (they have different groupId/artifactId thus it's expected).
```
BOOT-INF/lib/apm-agent-attach-1.28.2.jar
BOOT-INF/lib/jna-5.3.1.jar
BOOT-INF/lib/jna-platform-5.3.1.jar
...
BOOT-INF/lib/jna-5.7.0-1.jar
```

Also, I am using a JDK to run the application, do you happen to use a JRE ?

**Comment by paulspeijers** [comment]
Yes I am using a JRE:

java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

I am using the following docker image:
[openjdk:8-jre-slim](https://hub.docker.com/layers/openjdk/library/openjdk/8-jre-slim/images/sha256-bed964f8a32a98c5abbe3565ab8a16ecae8eaacf8dbc23b2264a42e9b9f10f14?context=explore)

**Comment by paulspeijers** [comment]
@SylvainJuge Any other suggestions?

**Comment by SylvainJuge** [comment]
Another user reported a similar issue when trying to use runtime attach with a JRE : #2383 

While I start to investigate a proper fix for that, could you try to temporarily use a JDK docker image instead to see if that makes a difference ?

Meanwhile, I will also investigate how we could solve the potential conflict with multiple JNA versions.

**Comment by SylvainJuge** [comment]
After a bit more investigation this does not seem linked to #2383 at all, thus a bit more work is required here to understand what is going on and how to find a solution.

**Comment by SylvainJuge** [comment]
For the `attach` artifact, the provided JNA dependency is only required:
- when "emulated attach" is used, which is common when using a JRE
- when no other copy of JNA is present in the classpath

There are few options
- (1) exclude JNA from elasticsearch high level client: I really don't know how it's used by ES client in practice, thus it needs some experimentation and testing first. If it does not work on macOS and you never had any issue so far it means it's probably not even used when using ES.
- (2) exclude JNA from agent attacher: it is mostly used when running on a JRE, but if there is any other JNA copy in the classpath it will just use it. For your local build you might have to use a maven profile to stay compatible with your local macOS if the copy provided through ES client does not work.
- (3) exclude both JNA copies and add one that works with both ES client and the agent as a direct dependency of your application.
- (4) exclude JNA from the agent attacher + using a JDK docker image instead of a JRE, in this case the JNA dependency is not required by the attacher jar.

To me, the most simple options are (1) and (4) and I have a strong preference for (4). @paulspeijers could you validate that with your application to ensure we can make it work as expected ?

On my side, I will update documentation to ensure that the JNA dependency requirement is properly described.

**Comment by paulspeijers** [comment]
Hi @SylvainJuge. Thanks for your suggestions, I will try them today or tomorrow.

**Comment by paulspeijers** [comment]
By the way I read about the option to stop loading JNA from the system: jna.nosys
https://java-native-access.github.io/jna/4.2.1/

Would that be helpful here?

**Comment by paulspeijers** [comment]
I tested it and it works with a JDK. I can imagine option 4 is the easiest option, but it would be nice I we could keep running on the jre-slim containers because they are much smaller.

**Comment by SylvainJuge** [comment]
Hi @paulspeijers ,

There is actually another alternative when using a JRE, in your case it might be simpler to switch to using the classic `-javaagent` setup option to provide the path to the agent and remove the attacher from your application dependencies.
Using the CLI attach is also likely to not work as expected as it requires a JDK and uses the `jps` command.

We even publish a docker image `docker.elastic.co/observability/apm-agent-java:1.28.4` with the agent in it, so it would be quite easy to reuse it through a multi-stage docker build or even as a "side-car container" and you don't have to re-implement downloading the artifact from maven central through a `curl` command.

**Comment by SylvainJuge** [comment]
There hasn't had any update on this issue for a while, thus I am going to assume that you have fixed or worked-around it.
As a result I'll close it for now, feel free to comment if there is anything we can do to help on this.
