### ISSUE TITLE
 com.sun.tools.attach.AttachNotSupportedException: Unable to get pid of LinuxThreads manager thread

### ISSUE THREAD

**Issue by issamnacim** [elastic/apm-agent-java#2383]
Hello, 
i am trying de start a docker container but i get this error stack  : 

```
Exception in thread "main" java.lang.reflect.InvocationTargetExceptionj
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalStateException: Error during attachment using: co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent$AttachmentProvider$Compound@1b701da1
at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:639)
at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.attach(ByteBuddyAgent.java:299)
at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:154)
at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:140)
at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:105)
at co.elastic.apm.attach.ElasticApmAttacher.attach(ElasticApmAttacher.java:58)
at org.autolab.gateway.AutolabGatewayApplication.main(AutolabGatewayApplication.java:19)
... 8 more
Caused by: java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at co.elastic.apm.attach.bytebuddy.agent.Attacher.install(Attacher.java:102)
at co.elastic.apm.attach.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:634)
... 14 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: Unable to get pid of LinuxThreads manager thread
at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:86)
at sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)
at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
... 20 more
```

ENV : 
Spring boot 
pom : 

```xml
    <properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
		<spring-cloud.version>Finchley.RC2</spring-cloud.version>
		<spring-security-jwt>1.0.9.RELEASE</spring-security-jwt>
		<maven.surefire.plugin>2.19.1</maven.surefire.plugin>
		<logstash.logback.version>4.11</logstash.logback.version>
		<elastic-apm.version>1.28.4</elastic-apm.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-config-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-hystrix</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-zuul</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-jwt</artifactId>
			<version>${spring-security-jwt}</version>
		</dependency>
		<dependency>
			<groupId>org.keycloak</groupId>
			<artifactId>keycloak-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>${logstash.logback.version}</version>
		</dependency>
		<dependency>
			<groupId>co.elastic.apm</groupId>
			<artifactId>apm-agent-attach</artifactId>
			<version>${elastic-apm.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.keycloak.bom</groupId>
				<artifactId>keycloak-adapter-bom</artifactId>
				<version>13.0.1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${maven.surefire.plugin}</version>
			</plugin>
		</plugins>
	</build>

	<repositories>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
```

DockerFIle : 

```
FROM openjdk:8-jdk-alpine
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} gateway.jar
ENTRYPOINT ["java","-Dspring.profiles.active=dev","-jar","/gateway.jar"]
```

main starter : 
```java
 @SpringBootApplication 
 @EnableZuulProxy 
 @EnableHystrix
 @EnableDiscoveryClient
 @EnableConfigurationProperties
public class AutolabGatewayApplication {

	public static void main(String[] args) {
		ElasticApmAttacher.attach();
		SpringApplication.run(AutolabGatewayApplication.class, args);
	}
}
```

**Comment by issamnacim** [comment]
solved => i changed in dockerfile : FROM openjdk:8-jre-alpine3.9

**Comment by SylvainJuge** [comment]
Hi @issamnacim ,

I will re-open this issue as there are a few details that need investigation:
- runtime attach should be supported even when using a JRE, as byte-buddy provides an "emulated attach" feature that should allow to do that without a JDK.
- if we require to use a JDK to use this feature, we need to properly document this as it might be confusing.

**Comment by SylvainJuge** [comment]
Update, I have just opened a PR https://github.com/elastic/apm-agent-java/pull/2385 that implements a fix for this issue.

For some docker images, when the JDK is used the agent would rely on the "native" attachment provider that is provided by the JDK when it's available. However in this case this provider fails because the JDK tools do not work as expected unless the `--init` argument is added to the `docker run` command.

The issue does not happen with a JRE because the agent does not even tries to use the "native" attachment provider as it's not a JDK and only tries to use the "emulated" attachment provider. The fix just uses the "emulated" provider as a fallback when the native one fails.

**Comment by issamnacim** [comment]
@SylvainJuge  thank you for your replay, exactly when i use JRE the container start successfully  without any problem, 
but the problem when we use JDK.
thank you for you help for this PR https://github.com/elastic/apm-agent-java/pull/2385
