### ISSUE TITLE
Cannot resolve type description for java.sql.ShardingKey

### ISSUE THREAD

**Issue by doctor-q** [elastic/apm-agent-java#254]
```
2018-10-23 17:28:24.492 [main] WARN co.elastic.apm.bci.bytebuddy.ErrorLoggingListener - ERROR on transformation com.microsoft.sqlserver.jdbc.SQLServerConnection43
java.lang.IllegalStateException: Cannot resolve type description for java.sql.ShardingKey
	at co.elastic.apm.shaded.bytebuddy.pool.TypePool$Resolution$Illegal.resolve(TypePool.java:136)
	at co.elastic.apm.shaded.bytebuddy.pool.TypePool$Default$WithLazyResolution$LazyTypeDescription.delegate(TypePool.java:1254)
	at co.elastic.apm.shaded.bytebuddy.description.type.TypeDescription$AbstractBase$OfSimpleType$WithDelegation.getModifiers(TypeDescription.java:7195)
	at co.elastic.apm.shaded.bytebuddy.description.ModifierReviewable$AbstractBase.matchesMask(ModifierReviewable.java:539)
	at co.elastic.apm.shaded.bytebuddy.description.ModifierReviewable$AbstractBase.isPublic(ModifierReviewable.java:313)
	at co.elastic.apm.shaded.bytebuddy.description.type.TypeDescription$AbstractBase.isVisibleTo(TypeDescription.java:6794)
	at co.elastic.apm.shaded.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:31)
	at co.elastic.apm.shaded.bytebuddy.matcher.VisibilityMatcher.matches(VisibilityMatcher.java:12)
	at co.elastic.apm.shaded.bytebuddy.matcher.NegatingMatcher.matches(NegatingMatcher.java:29)
	at co.elastic.apm.shaded.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:33)
	at co.elastic.apm.shaded.bytebuddy.matcher.ErasureMatcher.matches(ErasureMatcher.java:14)
```
```
$ java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-0ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

SqlServer lib:
```
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>6.5.1.jre8-preview</version>
</dependency>
```

**Comment by felixbarny** [comment]
This is a warning which can show for example, when there are optional types missing. Do you actually encounter any errors because of this?

**Comment by felixbarny** [comment]
The problem is that `ShardingKey` was introduced in Java 9 and you are running on Java 8. That's why this warning is shown when the DEBUG log level is enabled. Should be nothing to worry about.

**Comment by doctor-q** [comment]
Thanks for your reply, we all use java 8, is there a way to hide the warning or log it a  DEBUG level?

**Comment by felixbarny** [comment]
I think logging as DEBUG makes sense here. If you want you can provide a PR, otherwise I'm also happy to take this over. 

You'd just need to change `logger.warn` to `logger.debug` in `co.elastic.apm.bci.bytebuddy.ErrorLoggingListener`.

**Comment by doctor-q** [comment]
Thank you very much.
