### ISSUE TITLE
@SylvainJuge Getting this error when trying to implement 1.32.1 for WebClient - Issue 1306, Reference PR#2229

### ISSUE THREAD

**Issue by anuragprakash2397** [elastic/apm-agent-java#2701]
@SylvainJuge Getting this error when trying to implement 1.32.1 for WebClient 

`2022-07-07 14:56:18.053 ERROR 60724 --- [ctor-http-nio-8] reactor.core.publisher.Operators         : Operator called default onErrorDropped

java.lang.NullPointerException: null
	at co.elastic.apm.agent.springwebclient.WebClientSubscriber.onComplete(WebClientSubscriber.java:113)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onComplete(TracedSubscriber.java:139)
	at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:136)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onComplete(TracedSubscriber.java:139)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onComplete(TracedSubscriber.java:139)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:252)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onComplete(TracedSubscriber.java:139)
	at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:96)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:77)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:104)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2071)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:143)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onSubscribe(MonoFlatMapMany.java:237)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:55)
	at reactor.core.publisher.FluxSourceMonoFuseable.subscribe(FluxSourceMonoFuseable.java:38)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7923)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:104)
	at reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onNext(FluxRetryPredicate.java:81)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:104)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)
	at reactor.netty.http.client.HttpClientConnect$HttpObserver.onStateChange(HttpClientConnect.java:405)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:470)
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:503)
	at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:442)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:521)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:313)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:427)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)`

Looks like something is breaking here

_Originally posted by @anuragprakash2397 in https://github.com/elastic/apm-agent-java/pull/2229#discussion_r915689835_

**Comment by SylvainJuge** [comment]
Thanks for testing and catching this @anuragprakash2397 , 

I've opened a PR to prevent this NPE, could you try with [this snapshot](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-2702/1/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.32.1-SNAPSHOT.jar) and see if that fixes the issue for you ?

**Comment by anuragprakash2397** [comment]
Thank you @SylvainJuge for the quick revert on this, let me test this SNAPSHOT. Will update my findings here

**Comment by anuragprakash2397** [comment]
@SylvainJuge I think it may be because rest of my services are running on apm agent 1.16.0, but the concerned webclient service is on 1.32.1-Snapshot
Are you aware of any compatibility issues on these 2 versions.
Will be trying to upgrade rest of my services to 1.32.0 (Stable release) tomorrow to verify the same.

**Comment by SylvainJuge** [comment]
Hi @anuragprakash2397 , we need to clarify a bit to make sure I properly understand the issue here, don't hesitate to correct my assumptions if they are not correct here.

You have one service A that is handling incoming HTTP requests, this service is delegating to other services (B and C) through HTTP, B and C seem to either further delegate and execute calls to the database.

Because A uses Spring Webclient to delegate to other services, you need the latest snapshot on this one + enable the experimental instrumentations, but the downstream services can use any other version (they were using 1.16.0 so far, which is quite old).

The 422 error you reported happens when the agent is deployed on service A, thus this is the place where we need to focus our investigation for now.

There are two distinct components in Spring Webflux, each of them have a distinct plugin in the agent
- the server part, which is usually called Webflux, already included in latest release agent, but still `experimental`
- the client part, which is usually called Webclient: recently added to the agent as `experimental` but not released yet.

In service A, both agent plugins will be used when you use the latest snapshot + enable experimental instrumentations.

First, I need to know which part is triggering the issue, thus the fastest way is to test the following configurations on service A and trigger the HTTP request that is captured as 422:

### First test

- replace the snapshot agent on service A with latest release [`1.32.0`](https://www.elastic.co/guide/en/apm/agent/java/master/release-notes-1.x.html#release-notes-1.32.0)
- keep the `experimental` instrumentations enabled on service A through the `ELASTIC_APM_ENABLE_EXPERIMENTAL_INSTRUMENTATIONS=true` environment variable
- restart the service and execute the HTTP request, for example with `curl -v http://my-service-a/my-transaction-url/`
- report the result that you observe on Kibana, only the "first level" transaction should be captured as delegation with Webclient is not available with this agent version.
- report any application or agent log (see [procedure for the agent logs](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html#trouble-shooting-logging-procedure)), here the application logs might contain more details and context that what is visible on Kibana.

If the transaction on Kibana is still captured with 422 status:
- does the 422 status code is consistent with what is returned by the HTTP call (the `curl -v` output will be handy to have).
- does this behavior is present when you remove the agent or disable the experimental instrumentations with `ELASTIC_APM_ENABLE_EXPERIMENTAL_INSTRUMENTATIONS=false`

If the transaction on Kibana does not have 422 status:
- does updating the agent to the latest snapshot that includes Webclient instrumentation ?

The next steps of the investigation depend on the answer to those questions.

----

The [related PR](https://github.com/elastic/apm-agent-java/pull/2702) I opened yesterday already fixes the NPE, thus we will merge it as it already provides a bugfix.

**Comment by SylvainJuge** [comment]
Thanks, what this means is that the agent instrumentation of Webflux (the server part) seems to have a side-effect on your application making it issue a 422 response where a 200 is expected, as this behavior is the same with `1.32.0` release it means that it is not a recent regression (but an issue nonetheless).

Now the challenging part will be to find how the agent can trigger such behavior on your application.
- can you reproduce the issue with a local instance for debugging ?
- can you reproduce this behavior with a simple spring-boot app ?
- if you can attach a debugger, can you add an exception breakpoint or capture a stack trace when `java.lang.UnsupportedOperationException` is thrown ? I think this error message comes from a generic spring exception handler, but we need to investigate the underlying reason we get it.

**Comment by anuragprakash2397** [comment]
@SylvainJuge  Yes, I can reproduce the issue with a local instance. Will have to try the same with a simple spring boot app.
Let me try to get the stack trace where the exception is thrown

**Comment by anuragprakash2397** [comment]
@SylvainJuge We got the stack trace for the issue. Sharing the same


` 0 = {StackTraceElement@20063} "reactor.core.publisher.FluxMapSignal$FluxMapSignalSubscriber.iterator(FluxMapSignal.java:277)"
 1 = {StackTraceElement@20064} "java.util.AbstractCollection.toString(AbstractCollection.java:454)"
 2 = {StackTraceElement@20065} "co.elastic.apm.agent.reactor.TracedSubscriber$1.apply(TracedSubscriber.java:263)"
 3 = {StackTraceElement@20066} "co.elastic.apm.agent.reactor.TracedSubscriber$1.apply(TracedSubscriber.java:241)"
 4 = {StackTraceElement@20067} "reactor.core.publisher.FluxLift.subscribe(FluxLift.java:42)"
 5 = {StackTraceElement@20068} "reactor.core.publisher.FluxMapSignal.subscribe(FluxMapSignal.java:69)"
 6 = {StackTraceElement@20069} "reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:97)"
 7 = {StackTraceElement@20070} "reactor.core.publisher.FluxLift.subscribe(FluxLift.java:46)"
 8 = {StackTraceElement@20071} "reactor.core.publisher.FluxFlatMap.subscribe(FluxFlatMap.java:97)"
 9 = {StackTraceElement@20072} "reactor.core.publisher.FluxLift.subscribe(FluxLift.java:46)"
 10 = {StackTraceElement@20073} "reactor.core.publisher.MonoSingle.subscribe(MonoSingle.java:58)"
 11 = {StackTraceElement@20074} "reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:55)"
 12 = {StackTraceElement@20075} "reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)"
 13 = {StackTraceElement@20076} "co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:104)"
 14 = {StackTraceElement@20077} "reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)"
 15 = {StackTraceElement@20078} "co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:104)"
 16 = {StackTraceElement@20079} "co.elastic.apm.agent.springwebclient.WebClientSubscriber.onNext(WebClientSubscriber.java:82)"
 17 = {StackTraceElement@20080} "co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:104)"
 18 = {StackTraceElement@20081} "reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:114)"
 19 = {StackTraceElement@20082} "co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:104)"
 20 = {StackTraceElement@20083} "reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)"
 21 = {StackTraceElement@20084} "co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:104)"
 22 = {StackTraceElement@20085} "reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:192)"
 23 = {StackTraceElement@20086} "co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:104)"
 24 = {StackTraceElement@20087} "reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)"
 25 = {StackTraceElement@20088} "co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:104)"
 26 = {StackTraceElement@20089} "reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:242)"
 27 = {StackTraceElement@20090} "reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2071)"
 28 = {StackTraceElement@20091} "reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:143)"
 29 = {StackTraceElement@20092} "reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onSubscribe(MonoFlatMapMany.java:237)"
 30 = {StackTraceElement@20093} "reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)"
 31 = {StackTraceElement@20094} "reactor.core.publisher.MonoLiftFuseable.subscribe(MonoLiftFuseable.java:55)"
 32 = {StackTraceElement@20095} "reactor.core.publisher.FluxSourceMonoFuseable.subscribe(FluxSourceMonoFuseable.java:38)"
 33 = {StackTraceElement@20096} "reactor.core.publisher.Flux.subscribe(Flux.java:7923)"
 34 = {StackTraceElement@20097} "reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:188)"
 35 = {StackTraceElement@20098} "co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:104)"
 36 = {StackTraceElement@20099} "reactor.core.publisher.FluxRetryPredicate$RetryPredicateSubscriber.onNext(FluxRetryPredicate.java:81)"
 37 = {StackTraceElement@20100} "co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:104)"
 38 = {StackTraceElement@20101} "reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:156)"
 39 = {StackTraceElement@20102} "reactor.netty.http.client.HttpClientConnect$HttpObserver.onStateChange(HttpClientConnect.java:405)"
 40 = {StackTraceElement@20103} "reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:470)"
 41 = {StackTraceElement@20104} "reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:503)"
 42 = {StackTraceElement@20105} "reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:442)"
 43 = {StackTraceElement@20106} "reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:521)"
 44 = {StackTraceElement@20107} "reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)"
 45 = {StackTraceElement@20108} "io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)"
 46 = {StackTraceElement@20109} "io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)"
 47 = {StackTraceElement@20110} "io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)"
 48 = {StackTraceElement@20111} "io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)"
 49 = {StackTraceElement@20112} "io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)"
 50 = {StackTraceElement@20113} "io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)"
 51 = {StackTraceElement@20114} "io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)"
 52 = {StackTraceElement@20115} "io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)"
 53 = {StackTraceElement@20116} "io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)"
 54 = {StackTraceElement@20117} "io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)"
 55 = {StackTraceElement@20118} "io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)"
 56 = {StackTraceElement@20119} "io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)"
 57 = {StackTraceElement@20120} "io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)"
 58 = {StackTraceElement@20121} "io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:313)"
 59 = {StackTraceElement@20122} "io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:427)"
 60 = {StackTraceElement@20123} "io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)"
 61 = {StackTraceElement@20124} "io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)"
 62 = {StackTraceElement@20125} "io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)"
 63 = {StackTraceElement@20126} "io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)"
 64 = {StackTraceElement@20127} "io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)"
 65 = {StackTraceElement@20128} "io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)"
 66 = {StackTraceElement@20129} "io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)"
 67 = {StackTraceElement@20130} "io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)"
 68 = {StackTraceElement@20131} "io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)"
 69 = {StackTraceElement@20132} "io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)"
 70 = {StackTraceElement@20133} "io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)"
 71 = {StackTraceElement@20134} "io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)"
 72 = {StackTraceElement@20135} "io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)"
 73 = {StackTraceElement@20136} "io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)"
 74 = {StackTraceElement@20137} "io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)"
 75 = {StackTraceElement@20138} "io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)"
 76 = {StackTraceElement@20139} "io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)"
 77 = {StackTraceElement@20140} "java.lang.Thread.run(Thread.java:748)"`
 
The issue seems to be at (TracedSubscriber.java:263)
https://github.com/elastic/apm-agent-java/blob/503379cd23c641f3db77ae5c38273dcfa5eab61d/apm-agent-plugins/apm-reactor-plugin/src/main/java/co/elastic/apm/agent/reactor/TracedSubscriber.java#L263

I think the issue is because the explicit toString() function being called
Because we checked the implementation of FluxMapSignal.iterator() which is currently not implemented and it throws the error.
https://github.com/reactor/reactor-core/blob/9de500c961e23ba1d64505d8cc438edfccf25742/reactor-core/src/main/java/reactor/core/publisher/FluxMapSignal.java#L290

Currently, CoreSubscriber extends FluxMapSignalSubscriber which extends AbstractQueue (Collection)

As the next steps can you try to reproduce the error on your end?
Also if it will be possible to share a SNAPSHOT with removing the line and then I will be trying the same on my end to verify it?

**Comment by anuragprakash2397** [comment]
@SylvainJuge Did you get a chance to look at it?

**Comment by SylvainJuge** [comment]
Hi @anuragprakash2397, I've just opened https://github.com/elastic/apm-agent-java/pull/2708 as an attempt to fix that.

**Comment by anuragprakash2397** [comment]
Hey Thanks @SylvainJuge , let me quickly verify the same.
Will update my findings

**Comment by anuragprakash2397** [comment]
@SylvainJuge verified it on my end, the APIs are now returning 200 OK Response.
Will be performing more tests on this agent version, but I think we have managed to solve the issue.
Thank you so much for the support :)

**Comment by SylvainJuge** [comment]
Thanks ! That's awesome !

That will allow us to review & merge https://github.com/elastic/apm-agent-java/pull/2708 to be included in the next release.

**Comment by SylvainJuge** [comment]
No we don't, we just released `1.33.0` thus it won't be within at least a few weeks for a new one, unless there an urgent bug fix or an important feature that requires us to do so. Looking at our past changelog you can see that it's usually about every 4 to 6 weeks usually.

Once we merge the fix, it will be one of the very few changes that make the snapshot differ from the `1.33.0` that we just released, thus you should be able to use the snapshot without any trouble.

**Comment by anuragprakash2397** [comment]
Ohh got it @SylvainJuge, not an issue. Will be using `1.33.1-SNAPSHOT` meanwhile.
Thank You 💯
