### ISSUE TITLE
NoClassDefFoundError software/amazon/awssdk/services/sqs/model/ReceiveMessageResponse

### ISSUE THREAD

**Issue by adrian-skybaker** [elastic/apm-agent-java#2799]
Upon upgrading to 1.34. our log is filled with a NoClassDefFoundError exceptions from APM instrumentation.

Our application uses S3 via the AWS v2 SDK, but does not use or have SQS on the classpath. Attach API is used. 

Directly referencing SQS classes in the base aws client class in https://github.com/elastic/apm-agent-java/pull/2637/files#diff-c89734e3966aad23f828908ed6162f7a4077b692a3f8f5cd25a8bbd30ab0ac85 looks like an issue. Adding `software.amazon.awssdk:sqs` to the classpath works around the issue.

Here's a dump of the relevant jars from our classpath:

```
co.elastic.apm/apm-agent-api/1.34.0/c9b96292c256a406a2bc0a53cd0eedabf8a58993/apm-agent-api-1.34.0.jar
co.elastic.apm/apm-agent-attach/1.34.0/57707d3b0f0acefd3fd269db5f5e8670ae419417/apm-agent-attach-1.34.0.jar
software.amazon.awssdk/annotations/2.17.261/e61bdda35042b0a30ba6592bab3dd5cbef3de07e/annotations-2.17.261.jar
software.amazon.awssdk/apache-client/2.17.261/943d3e08e48d04b4cd0e7a7c9892b7cac0de7cbf/apache-client-2.17.261.jar
software.amazon.awssdk/arns/2.17.261/d1b00bcffde67acd4d45c277ecb6d119adddadd1/arns-2.17.261.jar
software.amazon.awssdk/auth/2.17.261/bc75acde1c19deaf5a89a7ac7cf29018a5cace0c/auth-2.17.261.jar
software.amazon.awssdk/aws-core/2.17.261/b2d22a0ca27e1fe24bc527d94445a1a34294161/aws-core-2.17.261.jar
software.amazon.awssdk/aws-json-protocol/2.17.261/b4d0c18ed2965d0e4dbef877fecbebca20156652/aws-json-protocol-2.17.261.jar
software.amazon.awssdk/aws-query-protocol/2.17.261/e702623dbe089d172d43c503f9015c8c524ee1e7/aws-query-protocol-2.17.261.jar
software.amazon.awssdk/aws-xml-protocol/2.17.261/9a679140d2569a2c7d36f5dbf8a81fc1716e7b1c/aws-xml-protocol-2.17.261.jar
software.amazon.awssdk/dynamodb-enhanced/2.17.261/eefe69a7e2e16649fb145fade5ac29e2207a273b/dynamodb-enhanced-2.17.261.jar
software.amazon.awssdk/dynamodb/2.17.261/87936410b568ba2bfdc6eb9cfa7a2d39b6f95db7/dynamodb-2.17.261.jar
software.amazon.awssdk/eventbridge/2.17.261/8e73b1547bbdf1194b1f558d9f33ae9c2202db74/eventbridge-2.17.261.jar
software.amazon.awssdk/http-client-spi/2.17.261/e548c8fcfc6b7f899d7070f084988b600954c2da/http-client-spi-2.17.261.jar
software.amazon.awssdk/json-utils/2.17.261/ad6e06cd4cf07891044694cfd9a8d5412cab59af/json-utils-2.17.261.jar
software.amazon.awssdk/metrics-spi/2.17.261/2b5d8fffb2364c6316a5607b88d4f1de8be784b6/metrics-spi-2.17.261.jar
software.amazon.awssdk/netty-nio-client/2.17.261/1922d8085bab6c8f8b924e56460de24c48847eaa/netty-nio-client-2.17.261.jar
software.amazon.awssdk/profiles/2.17.261/858a0e150ccf83201598f23f947908453ce0e537/profiles-2.17.261.jar
software.amazon.awssdk/protocol-core/2.17.261/a6cc846a3e1d082f738e81a7e64079750755463e/protocol-core-2.17.261.jar
software.amazon.awssdk/regions/2.17.261/5d60238fa52fe60f9975ec7db7613fbc57a09c24/regions-2.17.261.jar
software.amazon.awssdk/s3/2.17.261/f15c8923152e12a62ab8d9d8dc2a5dbb6f4a5599/s3-2.17.261.jar
software.amazon.awssdk/sdk-core/2.17.261/df3a59a5cb6fff0e2385ae699208636591f35c88/sdk-core-2.17.261.jar
software.amazon.awssdk/ssm/2.17.261/aeb8a323f97e34ccc0acdb417ff0b1bc0bb3afcc/ssm-2.17.261.jar
software.amazon.awssdk/sso/2.17.261/efb1cf941bd44ad3f926ecfa2e84117be6bf4791/sso-2.17.261.jar
software.amazon.awssdk/sts/2.17.261/e0dbda7de6d59ce0b7b3d0fd737813ad9b168dc5/sts-2.17.261.jar
software.amazon.awssdk/third-party-jackson-core/2.17.261/130b3b25c96ea4e058887cfa245afcf23da80e30/third-party-jackson-core-2.17.261.jar
software.amazon.awssdk/utils/2.17.261/44be242e7c2c209f86478a3bf2cd96fcb017c86f/utils-2.17.261.jar
```

```
java.lang.NoClassDefFoundError: software/amazon/awssdk/services/sqs/model/ReceiveMessageResponse
        at co.elastic.apm.agent.awssdk.v2.BaseSyncClientHandlerInstrumentation$AdviceClass.exitDoExecute(BaseSyncClientHandlerInstrumentation.java:122)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:167)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$0(BaseSyncClientHandler.java:68)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175)
        at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:62)
        at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:52)
        at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:63)
        at software.amazon.awssdk.services.s3.DefaultS3Client.getObject(DefaultS3Client.java:4483)
        at software.amazon.awssdk.services.s3.S3Client.getObjectAsBytes(S3Client.java:8373)
        at software.amazon.awssdk.services.s3.S3Client.getObjectAsBytes(S3Client.java:8617)
        at nz.co.sky.digital.hollow.consumer.s3.S3AnnouncementWatcher.readLatestVersion(S3AnnouncementWatcher.java:113)
        at nz.co.sky.digital.hollow.consumer.s3.S3AnnouncementWatcher.lambda$setupPollingThread$0(S3AnnouncementWatcher.java:70)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.services.sqs.model.ReceiveMessageResponse
        at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.findClass(ByteArrayClassLoader.java:403)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
        at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$ChildFirst.loadClass(ByteArrayClassLoader.java:1265)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
```

**Comment by AlexanderWert** [comment]
Hi @adrian-skybaker ,

thanks for reporting this! We were able to reproduce this and have a PR that should fix this bug.
Do you mind testing the [this SNAPSHOT of the agent](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-2800/1/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.34.1-SNAPSHOT.jar) to verify that it solved the problem for you as well?



Thanks!

**Comment by adrian-skybaker** [comment]
Thanks for such a quick follow up, I can confirm that with that snapshot we no longer see the error.
