### ISSUE TITLE
Potential race condition in webflux transaction naming

### ISSUE THREAD

**Issue by JonasKunz** [elastic/apm-agent-java#2835]
During the totally unrelated PR #2832 one of the webflux tests failed due to an invalid transaction name:

```
expected: "PUT /functional/hello-mapping"
 but was: "unnamedPUT /functional/hello-mapping" 
```

The fact that this failure hasn't come up before makes it look like there is some kind of race-condition within the webflux instrumentation. Maybe between ending the transaction and updating the transaction name, because `end()` will set the name of the transaction to `unnamed` in case no name is present.

Full error log with stacktrace:
```
[2022-10-06T15:18:16.750Z] [ERROR] Tests run: 29, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 23.603 s <<< FAILURE! - in co.elastic.apm.agent.springwebflux.ServerFunctionalInstrumentationTest
[2022-10-06T15:18:16.750Z] [ERROR] methodMapping{String}[3]  Time elapsed: 0.506 s  <<< FAILURE!
[2022-10-06T15:18:16.750Z] org.opentest4j.AssertionFailedError: 
[2022-10-06T15:18:16.750Z] 
[2022-10-06T15:18:16.750Z] expected: "PUT /functional/hello-mapping"
[2022-10-06T15:18:16.750Z]  but was: "unnamedPUT /functional/hello-mapping"
[2022-10-06T15:18:16.750Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2022-10-06T15:18:16.750Z] 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[2022-10-06T15:18:16.750Z] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2022-10-06T15:18:16.750Z] 	at co.elastic.apm.agent.springwebflux.AbstractServerInstrumentationTest.checkTransaction(AbstractServerInstrumentationTest.java:455)
[2022-10-06T15:18:16.751Z] 	at co.elastic.apm.agent.springwebflux.AbstractServerInstrumentationTest.methodMapping(AbstractServerInstrumentationTest.java:229)
[2022-10-06T15:18:16.751Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2022-10-06T15:18:16.751Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2022-10-06T15:18:16.751Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2022-10-06T15:18:16.751Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2022-10-06T15:18:16.751Z] 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestTemplateMethod(TimeoutExtension.java:94)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
[2022-10-06T15:18:16.751Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
[2022-10-06T15:18:16.751Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
[2022-10-06T15:18:16.751Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
[2022-10-06T15:18:16.751Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2022-10-06T15:18:16.751Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2022-10-06T15:18:16.751Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2022-10-06T15:18:16.751Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2022-10-06T15:18:16.751Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2022-10-06T15:18:16.752Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2022-10-06T15:18:16.752Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2022-10-06T15:18:16.752Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
[2022-10-06T15:18:16.752Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:226)
[2022-10-06T15:18:16.752Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask$DefaultDynamicTestExecutor.execute(NodeTestTask.java:204)
[2022-10-06T15:18:16.752Z] 	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:142)
[2022-10-06T15:18:16.752Z] 	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.lambda$execute$2(TestTemplateTestDescriptor.java:110)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[2022-10-06T15:18:16.752Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[2022-10-06T15:18:16.753Z] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[2022-10-06T15:18:16.753Z] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[2022-10-06T15:18:16.753Z] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[2022-10-06T15:18:16.753Z] 	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:110)
[2022-10-06T15:18:16.753Z] 	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:44)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2022-10-06T15:18:16.753Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2022-10-06T15:18:16.753Z] 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2022-10-06T15:18:16.753Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2022-10-06T15:18:16.754Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2022-10-06T15:18:16.754Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2022-10-06T15:18:16.754Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
[2022-10-06T15:18:16.754Z] 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
[2022-10-06T15:18:16.754Z] 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
[2022-10-06T15:18:16.754Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
[2022-10-06T15:18:16.754Z] 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
[2022-10-06T15:18:16.754Z] 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
[2022-10-06T15:18:16.754Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
[2022-10-06T15:18:16.754Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
[2022-10-06T15:18:16.754Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
[2022-10-06T15:18:16.754Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
[2022-10-06T15:18:16.754Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
[2022-10-06T15:18:16.754Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
[2022-10-06T15:18:16.754Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
[2022-10-06T15:18:16.754Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by eyalkoren** [comment]
May be fixed similarly to https://github.com/elastic/apm-agent-java/pull/2747, however I am not sure we need.
We may consider concurrency handling only for WebFlux, or we can check the transaction name and fill with the fallback value only during serialization, where the Disruptor memory barrier should guarantee a happens-before sequence.
