### ISSUE TITLE
Micrometer test flakyness

### ISSUE THREAD

**Issue by JonasKunz** [elastic/apm-agent-java#2887]
## Test method

`MicrometerInstrumentationStepTest.testStepVsCumulativeMultiple`

## Test logs

<details>
<summary>Click to expand</summary>

```
java.lang.RuntimeException: Condition not fulfilled within 5000 ms
	at co.elastic.apm.agent.MockReporter.awaitUntilAsserted(MockReporter.java:636)
	at co.elastic.apm.agent.micrometer.MicrometerInstrumentationStepTest.testStepVsCumulative(MicrometerInstrumentationStepTest.java:142)
	at co.elastic.apm.agent.micrometer.MicrometerInstrumentationStepTest.testStepVsCumulativeMultiple(MicrometerInstrumentationStepTest.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: org.opentest4j.AssertionFailedError: 
expected: FooBar{fooCount=0, barCount=21}
 but was: FooBar{fooCount=0, barCount=22}
	at jdk.internal.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at co.elastic.apm.agent.micrometer.MicrometerInstrumentationStepTest.lambda$testStepVsCumulative$0(MicrometerInstrumentationStepTest.java:143)
	at co.elastic.apm.agent.MockReporter.awaitUntilAsserted(MockReporter.java:629)
	... 40 more
```
</details>

**Comment by JonasKunz** [comment]
Error occured again, now the `bar` value is lower than expected:
```
java.lang.RuntimeException: Condition not fulfilled within 5000 ms
	at co.elastic.apm.agent.MockReporter.awaitUntilAsserted(MockReporter.java:636)
	at co.elastic.apm.agent.micrometer.MicrometerInstrumentationStepTest.testStepVsCumulative(MicrometerInstrumentationStepTest.java:142)
	at co.elastic.apm.agent.micrometer.MicrometerInstrumentationStepTest.testStepVsCumulativeMultiple(MicrometerInstrumentationStepTest.java:81)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
Caused by: org.opentest4j.AssertionFailedError: 
expected: FooBar{fooCount=0, barCount=21}
 but was: FooBar{fooCount=0, barCount=10}
	at jdk.internal.reflect.GeneratedConstructorAccessor60.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at co.elastic.apm.agent.micrometer.MicrometerInstrumentationStepTest.lambda$testStepVsCumulative$0(MicrometerInstrumentationStepTest.java:143)
	at co.elastic.apm.agent.MockReporter.awaitUntilAsserted(MockReporter.java:629)
	... 40 more
```

**Comment by jackshirazi** [comment]
Have increased the timeout https://github.com/elastic/apm-agent-java/pull/2897 but I'm going to again re-run the test several thousand times and analyse the failures and explain the exact failure conditions for completeness and future addressing

**Comment by JonasKunz** [comment]
Test seems to be still failing:
```
[2023-01-19T09:18:26.741Z] [ERROR] Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 28.068 s <<< FAILURE! - in co.elastic.apm.agent.micrometer.MicrometerInstrumentationStepTest

[2023-01-19T09:18:26.741Z] [ERROR] testStepVsCumulativeOnce  Time elapsed: 22.977 s  <<< ERROR!

[2023-01-19T09:18:26.741Z] java.lang.RuntimeException: Condition not fulfilled within 20000 ms

[2023-01-19T09:18:26.741Z] 	at co.elastic.apm.agent.MockReporter.awaitUntilAsserted(MockReporter.java:694)

[2023-01-19T09:18:26.741Z] 	at co.elastic.apm.agent.micrometer.MicrometerInstrumentationStepTest.testStepVsCumulative(MicrometerInstrumentationStepTest.java:142)

[2023-01-19T09:18:26.741Z] 	at co.elastic.apm.agent.micrometer.MicrometerInstrumentationStepTest.testStepVsCumulativeOnce(MicrometerInstrumentationStepTest.java:75)

[2023-01-19T09:18:26.741Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2023-01-19T09:18:26.741Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2023-01-19T09:18:26.741Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2023-01-19T09:18:26.742Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

[2023-01-19T09:18:26.742Z] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

[2023-01-19T09:18:26.742Z] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

[2023-01-19T09:18:26.742Z] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

[2023-01-19T09:18:26.742Z] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

[2023-01-19T09:18:26.742Z] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

[2023-01-19T09:18:26.742Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)

[2023-01-19T09:18:26.742Z] 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)

[2023-01-19T09:18:26.742Z] 	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)

[2023-01-19T09:18:26.742Z] 	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)

[2023-01-19T09:18:26.742Z] 	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)

[2023-01-19T09:18:26.742Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)

[2023-01-19T09:18:26.742Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)

[2023-01-19T09:18:26.742Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)

[2023-01-19T09:18:26.742Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)

[2023-01-19T09:18:26.742Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)

[2023-01-19T09:18:26.742Z] 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)

[2023-01-19T09:18:26.742Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)

[2023-01-19T09:18:26.742Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)

[2023-01-19T09:18:26.742Z] 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)

[2023-01-19T09:18:26.742Z] 	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)

[2023-01-19T09:18:26.742Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)

[2023-01-19T09:18:26.742Z] 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)

[2023-01-19T09:18:26.743Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)

[2023-01-19T09:18:26.743Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)

[2023-01-19T09:18:26.743Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)

[2023-01-19T09:18:26.743Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

[2023-01-19T09:18:26.743Z] Caused by: org.opentest4j.AssertionFailedError: 

[2023-01-19T09:18:26.743Z] expected: FooBar{fooCount=0, barCount=1}

[2023-01-19T09:18:26.743Z]  but was: FooBar{fooCount=0, barCount=0}

[2023-01-19T09:18:26.743Z] 	at jdk.internal.reflect.GeneratedConstructorAccessor62.newInstance(Unknown Source)

[2023-01-19T09:18:26.743Z] 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

[2023-01-19T09:18:26.743Z] 	at co.elastic.apm.agent.micrometer.MicrometerInstrumentationStepTest.lambda$testStepVsCumulative$0(MicrometerInstrumentationStepTest.java:143)

[2023-01-19T09:18:26.743Z] 	at co.elastic.apm.agent.MockReporter.awaitUntilAsserted(MockReporter.java:687)

[2023-01-19T09:18:26.743Z] 	... 45 more
```
