### ISSUE TITLE
[Flaky test] `AgentOverheadMetricsTest` 

### ISSUE THREAD

**Issue by eyalkoren** [elastic/apm-agent-java#2903]
## Test methods
[co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.checkCpuMetrics](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/main/479/testReport/junit/co.elastic.apm.agent.metrics.builtin/AgentOverheadMetricsTest/checkCpuMetrics/)
[co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.checkAllocationMetric](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/main/479/testReport/junit/co.elastic.apm.agent.metrics.builtin/AgentOverheadMetricsTest/checkAllocationMetric/)

## Test logs

<details>
<summary>checkCpuMetrics</summary>

```
org.assertj.core.error.AssertJMultipleFailuresError: 

Multiple Failures (1 failure)
-- failure 1 --
Expecting actual:
  0.14638835
to be greater than:
  0.14638835
at AgentOverheadMetricsTest.lambda$checkCpuMetrics$3(AgentOverheadMetricsTest.java:120)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.lambda$checkCpuMetrics$7(AgentOverheadMetricsTest.java:118)
	at co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.lambda$reportAndCheckMetrics$35(AgentOverheadMetricsTest.java:392)
	at co.elastic.apm.agent.metrics.MetricRegistry.flipPhaseAndReport(MetricRegistry.java:201)
	at co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.reportAndCheckMetrics(AgentOverheadMetricsTest.java:391)
	at co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.checkCpuMetrics(AgentOverheadMetricsTest.java:109)
```
</details>

<details>
<summary>checkAllocationMetric</summary>

```
Expecting empty but was: {"agent.background.threads.count"=1.0}
	at co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.lambda$checkAllocationMetric$24(AgentOverheadMetricsTest.java:239)
	at co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.lambda$reportAndCheckMetrics$35(AgentOverheadMetricsTest.java:392)
	at co.elastic.apm.agent.metrics.MetricRegistry.flipPhaseAndReport(MetricRegistry.java:201)
	at co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.reportAndCheckMetrics(AgentOverheadMetricsTest.java:391)
	at co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.checkAllocationMetric(AgentOverheadMetricsTest.java:238)
```
</details>

## Acceptance criteria
`AgentOverheadMetricsTest` should be reenabled

**Comment by JonasKunz** [comment]
Unfortunately the test still seems to be flaky:
```
[2023-01-23T04:07:12.745Z] [ERROR] Tests run: 8, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.925 s <<< FAILURE! - in co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest
[2023-01-23T04:07:12.745Z] [ERROR] checkCpuMetrics  Time elapsed: 0.14 s  <<< FAILURE!
[2023-01-23T04:07:12.745Z] java.lang.AssertionError: 
[2023-01-23T04:07:12.745Z] 
[2023-01-23T04:07:12.745Z] Expecting actual:
[2023-01-23T04:07:12.745Z]   {"agent.background.memory.allocation.bytes"=1128.0, "agent.background.threads.count"=1.0}
[2023-01-23T04:07:12.745Z] to contain key:
[2023-01-23T04:07:12.745Z]   "agent.background.cpu.overhead.pct"
[2023-01-23T04:07:12.745Z] 	at co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.lambda$checkCpuMetrics$8(AgentOverheadMetricsTest.java:116)
[2023-01-23T04:07:12.745Z] 	at co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.lambda$reportAndCheckMetrics$38(AgentOverheadMetricsTest.java:396)
[2023-01-23T04:07:12.745Z] 	at co.elastic.apm.agent.metrics.MetricRegistry.flipPhaseAndReport(MetricRegistry.java:201)
[2023-01-23T04:07:12.745Z] 	at co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.reportAndCheckMetrics(AgentOverheadMetricsTest.java:395)
[2023-01-23T04:07:12.745Z] 	at co.elastic.apm.agent.metrics.builtin.AgentOverheadMetricsTest.checkCpuMetrics(AgentOverheadMetricsTest.java:109)
```
