### ISSUE TITLE
Fix support for Spring boot 3.x

### ISSUE THREAD

**Issue by ghilainm** [elastic/apm-agent-java#2935]
Is your feature request related to a problem? Please describe.
Support for the moment is limited to Spring Boot 2.x

Describe the solution you'd like
The agent should support Spring Boot 3.x

Describe alternatives you've considered
Use another APM.

Additional context
```
2022-12-08 09:49:37.205 WARN 385599 --- [or-tcp-epoll-13] transaction.id=5b0c1281268dd31d, trace.id=a074b71f72622f22bb82fe8ccae7e6da reactor.core.Exceptions : throwIfFatal detected a jvm fatal exception, which is thrown and logged below:

java.lang.NoSuchMethodError: 'org.springframework.http.HttpStatus org.springframework.http.server.reactive.ServerHttpResponse.getStatusCode()'
at co.elastic.apm.agent.springwebflux.WebfluxHelper.fillResponse(WebfluxHelper.java:272)
at co.elastic.apm.agent.springwebflux.WebfluxHelper.endTransaction(WebfluxHelper.java:171)
at co.elastic.apm.agent.springwebflux.TransactionAwareSubscriber.onComplete(TransactionAwareSubscriber.java:177)
```

**Comment by JonasKunz** [comment]
Hi @ghilainm ,

Could you list your exact dependencies (e.g. via `mvn dependency:tree`)?
According to the [javadocs](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/server/reactive/ServerHttpResponse.html#getStatusCode()) the method `org.springframework.http.HttpStatus org.springframework.http.server.reactive.ServerHttpResponse.getStatusCode()` is supposed to still exist in spring 6. For this reason I assume that there must be some problems on your application classpath.

**Comment by ghilainm** [comment]
The problem arises when I migrated to Spring Boot 3.X.

Please find my dependencies attached :). I have added a screen shot of my project and the latest pull of apm java agent. The problem is the return type of the method.

![dependency-issues](https://user-images.githubusercontent.com/661772/209333097-4fd4d74a-2b74-4c99-8e38-3799905666b5.png)
[runtime-dependencies.txt](https://github.com/elastic/apm-agent-java/files/10294848/runtime-dependencies.txt)

**Comment by JonasKunz** [comment]
Ah I see, I missed that `HttpStatus` was changed to `HttpStatusCode`. Thanks for reporting this, we'll look into it!

**Comment by eyalkoren** [comment]
As far as I can see, [fixing](https://github.com/elastic/apm-agent-java/pull/2936) this [status-code API](https://github.com/elastic/apm-agent-java/issues/2935#issuecomment-1363905375) compatibility may be sufficient to restore functionality.
Please try [this snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-2936/10/artifacts/) and see if it improves things. 
If not, please set `log_level=debug` and share the log, for example as [gist](https://gist.github.com/).

**Comment by erescobar** [comment]
Hi! Any news here? Do you know when this will become available?

**Comment by eyalkoren** [comment]
@erescobar @ghilainm please try [this snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-2936/14/artifacts) and report back how this works for you. I hope the WebFlux issue is fixed with this. 
If you use Spring MVC, that is not expected to work with Spring 6 still though. That will be the next step.

Please share how it looks like with the new snapshot and any errors you see.
Also, if you can share a full `debug` log through [gist](https://gist.github.com/), one that starts with the startup of the application and continues until there are some traces being captured, that may be very helpful to make more progress.

**Comment by eyalkoren** [comment]
@erescobar @ghilainm any feedback on the provided snapshot would be extremely useful and can speed up our fix release. Thanks 🙏

**Comment by ghilainm** [comment]
I am currently having a look

**Comment by ghilainm** [comment]
@eyalkoren Works like a charm :). I don't have any issue anymore.

**Comment by ghilainm** [comment]
@eyalkoren Sorry Can't share debug logs too much sensitive information inside it. What are you searching for exactly?

**Comment by eyalkoren** [comment]
Awesome! If it works - no need for logs, thanks!
One question that can be useful to answer though - did you try out the [latest shared snapshot](https://github.com/elastic/apm-agent-java/issues/2935#issuecomment-1368365728) or the [former](https://github.com/elastic/apm-agent-java/issues/2935#issuecomment-1365867581)? Both contain the same fix, but I made a big structural change between the two, so I just wan to confirm that the latest one was packaged and worked as expected.

**Comment by ghilainm** [comment]
@eyalkoren I used that one -> https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/PR-2936/14/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/elastic-apm-agent-1.35.1-SNAPSHOT.jar

So the latest one if I am correct :)

**Comment by ghilainm** [comment]
@eyalkoren Just tested the snapshot from develop and got the following issue :(.

2023-01-25 13:32:55,140 [reactor-http-epoll-2] ERROR co.elastic.apm.agent.springwebflux.WebfluxHelper - Failed to get response code
java.lang.IllegalStateException: Spring-web 6.x+ identified, but failed to load related utility class
	at co.elastic.apm.agent.springwebflux.SpringWebVersionUtils.initialize(SpringWebVersionUtils.java:49) ~[elk-javaagent.jar:?]
	at co.elastic.apm.agent.springwebflux.SpringWebVersionUtils.getImplementation(SpringWebVersionUtils.java:67) ~[elk-javaagent.jar:?]
	at co.elastic.apm.agent.springwebflux.SpringWebVersionUtils.getStatusCode(SpringWebVersionUtils.java:81) ~[elk-javaagent.jar:?]
	at co.elastic.apm.agent.springwebflux.WebfluxHelper.fillResponse(WebfluxHelper.java:276) [elk-javaagent.jar:?]
	at co.elastic.apm.agent.springwebflux.WebfluxHelper.endTransaction(WebfluxHelper.java:173) [elk-javaagent.jar:?]
	at co.elastic.apm.agent.springwebflux.TransactionAwareSubscriber.onComplete(TransactionAwareSubscriber.java:177) [elk-javaagent.jar:?]
	at co.elastic.apm.agent.reactor.TracedSubscriber.onComplete(TracedSubscriber.java:140) [elk-javaagent.jar:?]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:250) [reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:324) [reactor-core-3.5.2.jar:3.5.2]
	at co.elastic.apm.agent.reactor.TracedSubscriber.onComplete(TracedSubscriber.java:140) [elk-javaagent.jar:?]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:250) [reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:324) [reactor-core-3.5.2.jar:3.5.2]
	at co.elastic.apm.agent.reactor.TracedSubscriber.onComplete(TracedSubscriber.java:140) [elk-javaagent.jar:?]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205) [reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onComplete(FluxOnAssembly.java:549) [reactor-core-3.5.2.jar:3.5.2]
	at co.elastic.apm.agent.reactor.TracedSubscriber.onComplete(TracedSubscriber.java:140) [elk-javaagent.jar:?]
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onComplete(FluxHide.java:147) [reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126) [reactor-core-3.5.2.jar:3.5.2]
	at co.elastic.apm.agent.reactor.TracedSubscriber.onComplete(TracedSubscriber.java:140) [elk-javaagent.jar:?]
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onComplete(FluxHide.java:147) [reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.secondComplete(MonoFlatMap.java:250) [reactor-core-3.5.2.jar:3.5.2]
	at reactor.core.publisher.MonoFlatMap$FlatMapInner.onComplete(MonoFlatMap.java:324) [reactor-core-3.5.2.jar:3.5.2]
	at co.elastic.apm.agent.reactor.TracedSubscriber.onComplete(TracedSubscriber.java:140) [elk-javaagent.jar:?]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:299) [reactor-core-3.5.2.jar:3.5.2]
	at org.springframework.http.server.reactive.ChannelSendOperator$WriteCompletionBarrier.onComplete(ChannelSendOperator.java:423) [spring-web-6.0.4.jar:6.0.4]
	at co.elastic.apm.agent.reactor.TracedSubscriber.onComplete(TracedSubscriber.java:140) [elk-javaagent.jar:?]
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89) [reactor-core-3.5.2.jar:3.5.2]
	at co.elastic.apm.agent.reactor.TracedSubscriber.onComplete(TracedSubscriber.java:140) [elk-javaagent.jar:?]
	at reactor.core.publisher.FluxConcatArray$ConcatArraySubscriber.onComplete(FluxConcatArray.java:230) [reactor-core-3.5.2.jar:3.5.2]
	at co.elastic.apm.agent.reactor.TracedSubscriber.onComplete(TracedSubscriber.java:140) [elk-javaagent.jar:?]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:209) [reactor-core-3.5.2.jar:3.5.2]
	at reactor.netty.channel.MonoSendMany$SendManyInner.run(MonoSendMany.java:349) [reactor-netty-core-1.1.2.jar:1.1.2]
	at reactor.netty.channel.MonoSendMany$SendManyInner.trySchedule(MonoSendMany.java:423) [reactor-netty-core-1.1.2.jar:1.1.2]
	at reactor.netty.channel.MonoSendMany$SendManyInner.trySuccess(MonoSendMany.java:587) [reactor-netty-core-1.1.2.jar:1.1.2]
	at reactor.netty.channel.MonoSendMany$SendManyInner.setSuccess(MonoSendMany.java:479) [reactor-netty-core-1.1.2.jar:1.1.2]
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.writeComplete(AbstractHttp2StreamChannel.java:991) [netty-codec-http2-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.access$2100(AbstractHttp2StreamChannel.java:579) [netty-codec-http2-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe$3.operationComplete(AbstractHttp2StreamChannel.java:968) [netty-codec-http2-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe$3.operationComplete(AbstractHttp2StreamChannel.java:962) [netty-codec-http2-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:557) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:52) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DelegatingChannelPromiseNotifier.operationComplete(DelegatingChannelPromiseNotifier.java:31) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryPromise(Http2CodecUtil.java:382) [netty-codec-http2-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.trySuccess(Http2CodecUtil.java:349) [netty-codec-http2-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.trySuccess(Http2CodecUtil.java:261) [netty-codec-http2-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.PromiseNotificationUtil.trySuccess(PromiseNotificationUtil.java:48) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.ChannelOutboundBuffer.safeSuccess(ChannelOutboundBuffer.java:717) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:272) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.ChannelOutboundBuffer.removeBytes(ChannelOutboundBuffer.java:352) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.writeBytesMultiple(AbstractEpollStreamChannel.java:305) [netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWriteMultiple(AbstractEpollStreamChannel.java:510) [netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel.doWrite(AbstractEpollStreamChannel.java:422) [netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:557) [netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:197) [netty-codec-http2-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel.flush0(AbstractHttp2StreamChannel.java:1094) [netty-codec-http2-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.flush(AbstractHttp2StreamChannel.java:1040) [netty-codec-http2-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:921) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893) [netty-transport-4.1.87.Final.jar:4.1.87.Final]
	at reactor.netty.channel.MonoSendMany$SendManyInner$AsyncFlush.run(MonoSendMany.java:789) [reactor-netty-core-1.1.2.jar:1.1.2]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) [netty-transport-classes-epoll-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.87.Final.jar:4.1.87.Final]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: co.elastic.apm.agent.springwebflux.SpringWeb6Utils
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.findClass(ByteArrayClassLoader.java:403) ~[elk-javaagent.jar:1.35.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$ChildFirst.loadClass(ByteArrayClassLoader.java:1265) ~[elk-javaagent.jar:1.35.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
Caused by: java.lang.ClassNotFoundException: co.elastic.apm.agent.springwebflux.SpringWeb6Utils

	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at co.elastic.apm.agent.springwebflux.SpringWebVersionUtils.initialize(SpringWebVersionUtils.java:47) ~[elk-javaagent.jar:?]
	... 91 more

**Comment by eyalkoren** [comment]
Ohh no, maybe it's because our release pipeline still uses Java 11 by default, let me check.
Just to be sure - 
> Just tested the snapshot from develop

You mean the latest snapshot from maven central? How did you obtain it?

**Comment by ghilainm** [comment]
@eyalkoren From Jenkins :). Here -> https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/main/547/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/

**Comment by eyalkoren** [comment]
Huh, that is odd, the first thing I did is check the latest build from main, which is now 548 and it looks good! 
That is troubling

**Comment by eyalkoren** [comment]
Indeed [547](https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-java/pipelines/apm-agent-java-mbp/branches/main/runs/547/nodes/90/steps/115/log/?start=0) was built with Java 11 and [548](https://apm-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/apm-agent-java/pipelines/apm-agent-java-mbp/branches/main/runs/548/nodes/90/steps/115/log/?start=0) was built with Java 17...
We'll look into that. 
Good thing you tested!! Thanks a lot for reporting, please let us know if you see this happens again.

**Comment by eyalkoren** [comment]
[547](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/main/547/changes) was the first one that included my change to `Jenkinsfile` as well, I wonder if it was still using the former version of it

**Comment by eyalkoren** [comment]
@ghilainm please just confirm that 548 works as expected

**Comment by eyalkoren** [comment]
@ghilainm ping - looking forward to hear how [the 548 build](https://apm-ci.elastic.co/job/apm-agent-java/job/apm-agent-java-mbp/job/main/548/artifact/src/github.com/elastic/apm-agent-java/elastic-apm-agent/target/) worked for you.
I was assured that what you experienced was indeed only related to the first build after merge, so your verification can be useful for us to know our next release provides a fix for this issue.

**Comment by ghilainm** [comment]
@eyalkoren Works like a charm :D.

By the way, it would be nice if the trace could be started earlier :). Currently, it is only begun at the controller level, but it would be nice if the instrumentation could be done directly at Netty level.

**Comment by eyalkoren** [comment]
IIRC we preferred that as well, but it turned out to be problematic, though I don't remember the details.
