### ISSUE TITLE
apm-server not work with jboss 7

### ISSUE THREAD

**Issue by mehrdad2000** [elastic/apm-agent-java#2939]
Hi
setup apm-agent java for jboss server

-jboss 7
-elastic-apm-agent-1.35.0.jar
-elasticsearch-8.5.3

here is the apm-server.yml

vi /etc/apm-server/apm-server.yml

output.elasticsearch:
  hosts: ["localhost:9200"]
  username: $MYUSER
  password: $MYPASS

#APM Server
  host: ":8200"

on apm server listen to 8200:
netstat -tpuln

tcp        0      0 0.0.0.0:8200            0.0.0.0:*               LISTEN      738822/apm-server
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN      128891/java

here is the jboss:

        <jvm>
            <jvm-options>
                <option value="-javaagent:/use/app/elastic-apm-agent-1.35.0.jar"/>
                <option value="-Delastic.apm.service_name=myapp"/>
                <option value="-Delastic.apm.server_urls=http://$ELASTICSERVERIP:8200"/>
                <option value="-Delastic.apm.secret_token=$MYTOKEN"/>
                <option value="-Delastic.apm.environment=development"/>
                <option value="-Delastic.apm.application_packages=$MYPACKAGE"/>
            </jvm-options>
        </jvm>

on elastic server doesn't show anything from apm-agent!

FYI: I run tcptump on ELASTIC but noting send from apm-agent!

also enable debug mode, here is the log:
```

[Server:main-server] 2022-12-28 16:10:03,888 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Receiving METRICSET_JSON_WRITER event (sequence 28)
[Server:main-server] 2022-12-28 16:10:03,889 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.util.UrlConnectionUtils - Opening http://ELASTICKSERVER:8200/intake/v2/events without proxy
[Server:main-server] 2022-12-28 16:10:03,889 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Starting new request to http://ELASTICSERVER:8200/intake/v2/events
[Server:main-server] 2022-12-28 16:10:03,892 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Scheduling request timeout in 10s
[Server:main-server] 2022-12-28 16:10:03,892 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Receiving METRICSET_JSON_WRITER event (sequence 29)
[Server:main-server] 2022-12-28 16:10:03,892 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Receiving METRICSET_JSON_WRITER event (sequence 30)
[Server:main-server] 2022-12-28 16:10:03,892 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Receiving METRICSET_JSON_WRITER event (sequence 31)
[Server:main-server] 2022-12-28 16:10:03,892 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Receiving METRICSET_JSON_WRITER event (sequence 32)
[Server:main-server] 2022-12-28 16:10:03,893 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Receiving METRICSET_JSON_WRITER event (sequence 33)
[Server:main-server] 2022-12-28 16:10:12,278 [elastic-apm-configuration-reloader] DEBUG co.elastic.apm.agent.impl.ElasticApmTracerBuilder - Beginning scheduled configuration reload (interval is 30 sec)...
[Server:main-server] 2022-12-28 16:10:12,280 [elastic-apm-configuration-reloader] DEBUG co.elastic.apm.agent.impl.ElasticApmTracerBuilder - Finished scheduled configuration reload
[Server:main-server] 2022-12-28 16:10:13,896 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Receiving WAKEUP event (sequence 34)
[Server:main-server] 2022-12-28 16:10:13,896 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Request flush because the request timeout occurred
[Server:main-server] 2022-12-28 16:10:13,896 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Flushing 2257 uncompressed 786 compressed bytes
[Server:main-server] 2022-12-28 16:10:18,901 [elastic-apm-server-reporter] WARN  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - null
[Server:main-server] 2022-12-28 16:10:18,901 [elastic-apm-server-reporter] INFO  co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Backing off for 16 seconds (+/-10%)
[Server:main-server] 2022-12-28 16:10:33,555 [elastic-apm-server-reporter] ERROR co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Error sending data to APM server: Read timed out, response code is -1
[Server:main-server] 2022-12-28 16:10:33,556 [elastic-apm-server-reporter] DEBUG co.elastic.apm.agent.report.IntakeV2ReportingEventHandler - Sending payload to APM server failed
[Server:main-server]        at co.elastic.apm.agent.report.AbstractIntakeApiHandler.endRequest(AbstractIntakeApiHandler.java:187) [elastic-apm-agent-1.35.0.jar:1.35.0]
[Server:main-server]        at co.elastic.apm.agent.report.AbstractIntakeApiHandler.endRequest(AbstractIntakeApiHandler.java:163) [elastic-apm-agent-1.35.0.jar:1.35.0]
[Server:main-server]        at co.elastic.apm.agent.report.IntakeV2ReportingEventHandler.onEvent(IntakeV2ReportingEventHandler.java:85) [elastic-apm-agent-1.35.0.jar:1.35.0]
[Server:main-server]        at co.elastic.apm.agent.report.IntakeV2ReportingEventHandler.onEvent(IntakeV2ReportingEventHandler.java:38) [elastic-apm-agent-1.35.0.jar:1.35.0]
[Server:main-server]        at com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168) [elastic-apm-agent-1.35.0.jar:1.35.0]
[Server:main-server]        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125) [elastic-apm-agent-1.35.0.jar:1.35.0]
[Server:main-server]        at co.elastic.apm.agent.util.ExecutorUtils$2.run(ExecutorUtils.java:99) [elastic-apm-agent-1.35.0.jar:1.35.0]
```

Any idea?
Thanks

**Comment by eyalkoren** [comment]
Generally speaking, the agent DOES work on JBoss 7, otherwise our [tests](https://github.com/elastic/apm-agent-java/blob/58cf9f3abcc1257e18a9869bb101588fc5361dbd/integration-tests/application-server-integration-tests/src/test/java/co/elastic/apm/servlet/JBossIT.java#L52-L53) would have fail.
Therefore, most likely there is something wrong with your setup.

Assuming that `http://ELASTICKSERVER:8200` is not the right URL to reach your APM Server, you should fix your `-Delastic.apm.server_urls` setting.

Either way, we typically use GitHub issues for verified bugs, enhancement requests etc. Assuming that this is a setup problem, I will close this issue now. If this turns out to be a verified issue with the agent functionality - feel free to reopen.
For general questions or request for assistance, please use our [forum](https://discuss.elastic.co/c/observability/apm/58) instead.

**Comment by mehrdad2000** [comment]
@eyalkoren URL correct.
Any other idea?

**Comment by eyalkoren** [comment]
I found your [Discuss topic](https://discuss.elastic.co/t/apm-server-not-work-with-jboss-7/322097) and replied there
