### ISSUE TITLE
Enabling `trace_method` results in NPE for code calling Elasticsearch

### ISSUE THREAD

**Issue by ajpahl1008** [elastic/apm-agent-java#2952]
## Describe the bug
Java application that writes documents and publishes to either the index or bulk API.  The stack trace captured below is generated only when trace_methods option is enabled on Elastic APM agent (v 1.35.0)

```
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:233)
        at co.elastic.apm.agent.impl.transaction.DroppedSpanStats$StatsKey.init(DroppedSpanStats.java:64)
        at co.elastic.apm.agent.impl.transaction.DroppedSpanStats.getOrCreateStats(DroppedSpanStats.java:190)
        at co.elastic.apm.agent.impl.transaction.DroppedSpanStats.captureDroppedSpan(DroppedSpanStats.java:179)
        at co.elastic.apm.agent.impl.transaction.Transaction.captureDroppedSpan(Transaction.java:281)
        at co.elastic.apm.agent.impl.ElasticApmTracer.endSpan(ElasticApmTracer.java:404)
        at co.elastic.apm.agent.impl.transaction.Span.afterEnd(Span.java:274)
        at co.elastic.apm.agent.impl.transaction.AbstractSpan.end(AbstractSpan.java:606)
        at co.elastic.apm.agent.impl.transaction.AbstractSpan.end(AbstractSpan.java:588)
        at co.elastic.apm.agent.esrestclient.ElasticsearchRestClientInstrumentationHelper.finishClientSpan(ElasticsearchRestClientInstrumentationHelper.java:154)
        at co.elastic.apm.agent.esrestclient.v6_4.ElasticsearchClientSyncInstrumentation$ElasticsearchRestClientSyncAdvice.onAfterExecute(ElasticsearchClientSyncInstrumentation.java:73)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
        at co.elastic.clients.transport.rest_client.RestClientTransport.performRequest(RestClientTransport.java:147)
        at co.elastic.clients.elasticsearch.ElasticsearchClient.bulk(ElasticsearchClient.java:319)
        at com.psoft.simpledata.engine.ElasticsearchWorkloadGeneratorEngine.run(ElasticsearchWorkloadGeneratorEngine.java:79)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

I rolled back Elastic Java Agent to 1.33.0 and it stoped the NPEs.

**Configuration Specifics:**
Agent 1.35.0
Java 17
Elasticsearch Client 8.5.3
Elasticsearch (ESS) 8.5.3

## Steps to reproduce
Added following to Java command line ``` -Delastic.apm.trace_methods="public com.psoft.simpledata.engine.*"```

**Comment by eyalkoren** [comment]
Once you add such a package-level-wildcard [`trace_methods`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-trace-methods) configuration, you are likely to hit the [`transaction_max_spans`](https://www.elastic.co/guide/en/apm/agent/java/current/config-core.html#config-transaction-max-spans) limit, which is why we don't recommend doing so. You should see an indication for that in your logs.

This probably triggers a bug that was added when we started collecting and sending metrics for dropped spans, as this code expects the context target type field to be set, but the ES instrumentation [does not set it for non sampled spans](https://github.com/elastic/apm-agent-java/blob/14919fe320dbaf88518d990b548ddd41d4b4ef97/apm-agent-plugins/apm-es-restclient-plugin/apm-es-restclient-plugin-common/src/main/java/co/elastic/apm/agent/esrestclient/ElasticsearchRestClientInstrumentationHelper.java#L111).

It should be fixed with #2959.
@ajpahl1008 please try [this snapshot](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-java%2Fapm-agent-java-mbp/detail/PR-2959/1/artifacts) and see if you can verify the fix.
Thanks!

**Comment by ajpahl1008** [comment]
@eyalkoren 👍 Fix works. No more NPEs.  

Thanks for the guidance on package-level-wildcards.  I will make sure to avoid them later. In this particular package at the wildcard level, there's only one class with a few public methods.  But thanks for the guidance, I'll be more restrictive on the use of "*" in the trace_methods config.

**Comment by eyalkoren** [comment]
Thanks for the confirmation!! 🙏 

There is no strict rule about wildcards, they are supported by this config, but in general it is best practice to be very restrictive and accurate with this setting. It could even be one method that is invoked >1K times within each transaction that will cause a lot of overhead and reduced readability. 
It's just that when crossing the threshold of allowed spans per transactions (500 by default), most likely you get less value with more overhead.
