### ISSUE TITLE
ES Async Client Instrumentation not recycling correctly

### ISSUE THREAD

**Issue by JonasKunz** [elastic/apm-agent-java#3255]
We regularly have flaky tests due to recycling issues in the elasticsearch client instrumentation:

<details>
<summary>Test Logs</summary>

```
2023-07-18T13:55:07.2394462Z 2023-07-18 13:55:07,214 [main] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'Elasticsearch: DELETE /my-index/_doc/38uhjds8s4g' 00-20008147d4d0f6ce1f834b62c421217a-84776d2d431c5429-01 (5c486c5a) (0)
2023-07-18T13:55:07.2395289Z 2023-07-18 13:55:07,214 [main] DEBUG co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool - recycling pooled object: 'Elasticsearch: DELETE /my-index/_doc/38uhjds8s4g' 00-20008147d4d0f6ce1f834b62c421217a-84776d2d431c5429-01 (5c486c5a)
2023-07-18T13:55:07.2395929Z 2023-07-18 13:55:07,215 [I/O dispatcher 1] DEBUG co.elastic.apm.agent.impl.ActiveStack - Deactivating 'ES Transaction' 00-20008147d4d0f6ce1f834b62c421217a-637f7e5a85cb4e4b-01 (6845895c) on thread 36
2023-07-18T13:55:07.2396675Z 2023-07-18 13:55:07,215 [I/O dispatcher 1] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to 'ES Transaction' 00-20008147d4d0f6ce1f834b62c421217a-637f7e5a85cb4e4b-01 (6845895c) (0)
2023-07-18T13:55:07.2397412Z 2023-07-18 13:55:07,215 [I/O dispatcher 1] DEBUG co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool - recycling pooled object: 'ES Transaction' 00-20008147d4d0f6ce1f834b62c421217a-637f7e5a85cb4e4b-01 (6845895c)
2023-07-18T13:55:07.2422689Z 2023-07-18 13:55:07,215 [I/O dispatcher 1] DEBUG co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool - recycling pooled object: co.elastic.apm.agent.esrestclient.ResponseListenerWrapper@278758da
2023-07-18T13:55:07.3746503Z 5840 [main] DEBUG org.apache.http.impl.nio.client.MainClientExec  - [exchange: 58] start execution
2023-07-18T13:55:07.3747746Z 5840 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies  - CookieSpec selected: default
2023-07-18T13:55:07.3748449Z 5840 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache  - Re-using cached 'basic' auth scheme for http://localhost:32786
2023-07-18T13:55:07.3749073Z 5840 [main] DEBUG org.apache.http.impl.nio.client.InternalHttpAsyncClient  - [exchange: 58] Request connection for {}->http://localhost:32786
2023-07-18T13:55:07.3749868Z 5840 [main] DEBUG org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager  - Connection request: [route: {}->http://localhost:32786][total kept alive: 1; route allocated: 1 of 10; total allocated: 1 of 30]
2023-07-18T13:55:07.3750499Z 5841 [main] DEBUG org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionImpl  - http-outgoing-0 127.0.0.1:42448<->127.0.0.1:32786[ACTIVE][r:r]: Set timeout 0
2023-07-18T13:55:07.3751486Z 5841 [main] DEBUG org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager  - Connection leased: [id: http-outgoing-0][route: {}->http://localhost:32786][total kept alive: 0; route allocated: 1 of 10; total allocated: 1 of 30]
2023-07-18T13:55:07.3752084Z 5841 [main] DEBUG org.apache.http.impl.nio.client.InternalHttpAsyncClient  - [exchange: 58] Connection allocated: CPoolProxy{http-outgoing-0 [ACTIVE]}
2023-07-18T13:55:07.3752765Z 5841 [main] DEBUG org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionImpl  - http-outgoing-0 127.0.0.1:42448<->127.0.0.1:32786[ACTIVE][r:r]: Set attribute http.nio.exchange-handler
2023-07-18T13:55:07.3753562Z 5841 [main] DEBUG org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionImpl  - http-outgoing-0 127.0.0.1:42448<->127.0.0.1:32786[ACTIVE][rw:r]: Event set [w]
2023-07-18T13:55:07.3754262Z 2023-07-18 13:55:07,242 [I/O dispatcher 1] DEBUG co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool - creating pooled object: co.elastic.apm.agent.impl.error.ErrorCapture@12ce5274
2023-07-18T13:55:07.3754814Z 2023-07-18 13:55:07,242 [I/O dispatcher 1] DEBUG co.elastic.apm.agent.impl.error.ErrorCapture - Creating an Error as child of unnamed with a null trace_id
2023-07-18T13:55:07.3755445Z 2023-07-18 13:55:07,245 [I/O dispatcher 1] WARN  co.elastic.apm.agent.impl.transaction.AbstractSpan - End has already been called: '' 00-00000000000000000000000000000000-0000000000000000-00 (5c486c5a)
2023-07-18T13:55:07.3755646Z java.lang.Throwable: null
2023-07-18T13:55:07.3756199Z 	at co.elastic.apm.agent.impl.transaction.AbstractSpan.end(AbstractSpan.java:580) [apm-agent-core-1.39.1-SNAPSHOT.jar:?]
2023-07-18T13:55:07.3756743Z 	at co.elastic.apm.agent.impl.transaction.AbstractSpan.end(AbstractSpan.java:555) [apm-agent-core-1.39.1-SNAPSHOT.jar:?]
2023-07-18T13:55:07.3757431Z 	at co.elastic.apm.agent.esrestclient.ElasticsearchRestClientInstrumentationHelper.finishClientSpan(ElasticsearchRestClientInstrumentationHelper.java:151) [?:?]
2023-07-18T13:55:07.3757918Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.finishClientSpan(ResponseListenerWrapper.java:148) [?:?]
2023-07-18T13:55:07.3758397Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailureClient(ResponseListenerWrapper.java:117) [?:?]
2023-07-18T13:55:07.3758845Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailure(ResponseListenerWrapper.java:109) [?:?]
2023-07-18T13:55:07.3759513Z 	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:686) [elasticsearch-rest-client-7.17.11.jar:7.17.11]
2023-07-18T13:55:07.3760049Z 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:409) [elasticsearch-rest-client-7.17.11.jar:7.17.11]
2023-07-18T13:55:07.3760551Z 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:393) [elasticsearch-rest-client-7.17.11.jar:7.17.11]
2023-07-18T13:55:07.3761027Z 	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122) [httpcore-4.4.12.jar:4.4.12]
2023-07-18T13:55:07.3761789Z 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181) [httpasyncclient-4.1.4.jar:4.1.4]
2023-07-18T13:55:07.3762497Z 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448) [httpcore-nio-4.4.12.jar:4.4.12]
2023-07-18T13:55:07.3763189Z 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338) [httpcore-nio-4.4.12.jar:4.4.12]
2023-07-18T13:55:07.3763828Z 	at org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83) [httpasyncclient-4.1.4.jar:4.1.4]
2023-07-18T13:55:07.3764589Z 	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265) [httpcore-nio-4.4.12.jar:4.4.12]
2023-07-18T13:55:07.3765176Z 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81) [httpasyncclient-4.1.4.jar:4.1.4]
2023-07-18T13:55:07.3766030Z 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39) [httpasyncclient-4.1.4.jar:4.1.4]
2023-07-18T13:55:07.3766622Z 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114) [httpcore-nio-4.4.12.jar:4.4.12]
2023-07-18T13:55:07.3767150Z 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162) [httpcore-nio-4.4.12.jar:4.4.12]
2023-07-18T13:55:07.3767882Z 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337) [httpcore-nio-4.4.12.jar:4.4.12]
2023-07-18T13:55:07.3768467Z 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315) [httpcore-nio-4.4.12.jar:4.4.12]
2023-07-18T13:55:07.3769023Z 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276) [httpcore-nio-4.4.12.jar:4.4.12]
2023-07-18T13:55:07.3769535Z 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104) [httpcore-nio-4.4.12.jar:4.4.12]
2023-07-18T13:55:07.3770542Z 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591) [httpcore-nio-4.4.12.jar:4.4.12]
2023-07-18T13:55:07.3771793Z 	at java.lang.Thread.run(Thread.java:833) [?:?]
2023-07-18T13:55:07.3772284Z 2023-07-18 13:55:07,253 [I/O dispatcher 1] DEBUG co.elastic.apm.agent.impl.ActiveStack - Activating '' 00-00000000000000000000000000000000-0000000000000000-00 (6845895c) on thread 36
2023-07-18T13:55:07.3772838Z 2023-07-18 13:55:07,253 [I/O dispatcher 1] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - increment references to '' 00-00000000000000000000000000000000-0000000000000000-00 (6845895c) (1)
2023-07-18T13:55:07.3773313Z 2023-07-18 13:55:07,253 [I/O dispatcher 1] DEBUG co.elastic.apm.agent.impl.ActiveStack - Deactivating '' 00-00000000000000000000000000000000-0000000000000000-00 (6845895c) on thread 36
2023-07-18T13:55:07.3773855Z 2023-07-18 13:55:07,253 [I/O dispatcher 1] DEBUG co.elastic.apm.agent.impl.transaction.AbstractSpan - decrement references to '' 00-00000000000000000000000000000000-0000000000000000-00 (6845895c) (0)
2023-07-18T13:55:07.3774429Z 2023-07-18 13:55:07,253 [I/O dispatcher 1] DEBUG co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool - recycling pooled object: '' 00-00000000000000000000000000000000-0000000000000000-00 (6845895c)
2023-07-18T13:55:07.3774852Z 5853 [I/O dispatcher 1] DEBUG org.apache.http.impl.nio.client.InternalIODispatch  - http-outgoing-0 [ACTIVE] Exception
2023-07-18T13:55:07.3775378Z java.lang.IllegalStateException: trying to recycle object that has not been taken from this pool or has already been returned '' 00-00000000000000000000000000000000-0000000000000000-00 (6845895c)
2023-07-18T13:55:07.3775723Z 	at co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool.recycle(BookkeeperObjectPool.java:68)
2023-07-18T13:55:07.3775979Z 	at co.elastic.apm.agent.impl.ElasticApmTracer.recycle(ElasticApmTracer.java:559)
2023-07-18T13:55:07.3776258Z 	at co.elastic.apm.agent.impl.transaction.Transaction.recycle(Transaction.java:378)
2023-07-18T13:55:07.3776690Z 	at co.elastic.apm.agent.impl.transaction.AbstractSpan.decrementReferences(AbstractSpan.java:677)
2023-07-18T13:55:07.3776936Z 	at co.elastic.apm.agent.impl.ActiveStack.deactivate(ActiveStack.java:136)
2023-07-18T13:55:07.3777287Z 	at co.elastic.apm.agent.impl.ElasticApmTracer.deactivate(ElasticApmTracer.java:855)
2023-07-18T13:55:07.3777610Z 	at co.elastic.apm.agent.impl.transaction.ElasticContext.deactivate(ElasticContext.java:60)
2023-07-18T13:55:07.3777928Z 	at co.elastic.apm.agent.impl.transaction.ElasticContext.deactivate(ElasticContext.java:30)
2023-07-18T13:55:07.3778398Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailureContextPropagation(ResponseListenerWrapper.java:138)
2023-07-18T13:55:07.3778769Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailure(ResponseListenerWrapper.java:111)
2023-07-18T13:55:07.3779169Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailureClient(ResponseListenerWrapper.java:120)
2023-07-18T13:55:07.3779537Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailure(ResponseListenerWrapper.java:109)
2023-07-18T13:55:07.3779889Z 	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:686)
2023-07-18T13:55:07.3780107Z 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:409)
2023-07-18T13:55:07.3780421Z 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:393)
2023-07-18T13:55:07.3780668Z 	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
2023-07-18T13:55:07.3781146Z 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
2023-07-18T13:55:07.3781527Z 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
2023-07-18T13:55:07.3781881Z 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)
2023-07-18T13:55:07.3782238Z 	at org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
2023-07-18T13:55:07.3782614Z 	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
2023-07-18T13:55:07.3782929Z 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
2023-07-18T13:55:07.3783253Z 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
2023-07-18T13:55:07.3783572Z 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
2023-07-18T13:55:07.3783849Z 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
2023-07-18T13:55:07.3784172Z 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
2023-07-18T13:55:07.3784500Z 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
2023-07-18T13:55:07.3784803Z 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
2023-07-18T13:55:07.3785077Z 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
2023-07-18T13:55:07.3785446Z 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
2023-07-18T13:55:07.3785603Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-07-18T13:55:07.3786169Z 5855 [I/O dispatcher 1] DEBUG org.apache.http.impl.nio.conn.ManagedNHttpClientConnectionImpl  - http-outgoing-0 127.0.0.1:42448<->127.0.0.1:32786[ACTIVE][rw:r]: Shutdown
2023-07-18T13:55:07.3786629Z 5856 [main] DEBUG org.elasticsearch.client.RestClient  - request [DELETE http://localhost:32786/my-index?master_timeout=30s&timeout=30s] failed
2023-07-18T13:55:07.3787270Z java.util.concurrent.ExecutionException: java.lang.IllegalStateException: trying to recycle object that has not been taken from this pool or has already been returned '' 00-00000000000000000000000000000000-0000000000000000-00 (6845895c)
2023-07-18T13:55:07.3787583Z 	at org.apache.http.concurrent.BasicFuture.getResult(BasicFuture.java:71)
2023-07-18T13:55:07.3787808Z 	at org.apache.http.concurrent.BasicFuture.get(BasicFuture.java:84)
2023-07-18T13:55:07.3788162Z 	at org.apache.http.impl.nio.client.FutureWrapper.get(FutureWrapper.java:70)
2023-07-18T13:55:07.3788422Z 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296)
2023-07-18T13:55:07.3788687Z 	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
2023-07-18T13:55:07.3789056Z 	at org.elasticsearch.client.RestHighLevelClient.performClientRequest(RestHighLevelClient.java:2699)
2023-07-18T13:55:07.3789418Z 	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:2171)
2023-07-18T13:55:07.3789742Z 	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:2137)
2023-07-18T13:55:07.3790134Z 	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:2105)
2023-07-18T13:55:07.3790366Z 	at org.elasticsearch.client.IndicesClient.delete(IndicesClient.java:109)
2023-07-18T13:55:07.3790948Z 	at co.elastic.apm.agent.esrestclient.v7_x.ElasticsearchRestClientInstrumentationIT.stopElasticsearchContainerAndClient(ElasticsearchRestClientInstrumentationIT.java:110)
2023-07-18T13:55:07.3791329Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-07-18T13:55:07.3791645Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-07-18T13:55:07.3791995Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-07-18T13:55:07.3792184Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-07-18T13:55:07.3792440Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2023-07-18T13:55:07.3792729Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2023-07-18T13:55:07.3793023Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2023-07-18T13:55:07.3793309Z 	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
2023-07-18T13:55:07.3793585Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
2023-07-18T13:55:07.3793796Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2023-07-18T13:55:07.3793996Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2023-07-18T13:55:07.3794172Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
2023-07-18T13:55:07.3794345Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
2023-07-18T13:55:07.3794633Z 	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
2023-07-18T13:55:07.3795493Z 	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
2023-07-18T13:55:07.3795832Z 	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
2023-07-18T13:55:07.3796226Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
2023-07-18T13:55:07.3796594Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
2023-07-18T13:55:07.3797010Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
2023-07-18T13:55:07.3797405Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
2023-07-18T13:55:07.3797872Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
2023-07-18T13:55:07.3798249Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
2023-07-18T13:55:07.3798540Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
2023-07-18T13:55:07.3798904Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
2023-07-18T13:55:07.3799270Z 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
2023-07-18T13:55:07.3799618Z 	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
2023-07-18T13:55:07.3800003Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
2023-07-18T13:55:07.3800418Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
2023-07-18T13:55:07.3800786Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
2023-07-18T13:55:07.3801109Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
2023-07-18T13:55:07.3801378Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
2023-07-18T13:55:07.3801633Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
2023-07-18T13:55:07.3801887Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
2023-07-18T13:55:07.3802507Z Caused by: java.lang.IllegalStateException: trying to recycle object that has not been taken from this pool or has already been returned '' 00-00000000000000000000000000000000-0000000000000000-00 (6845895c)
2023-07-18T13:55:07.3802977Z 	at co.elastic.apm.agent.objectpool.impl.BookkeeperObjectPool.recycle(BookkeeperObjectPool.java:68)
2023-07-18T13:55:07.3803246Z 	at co.elastic.apm.agent.impl.ElasticApmTracer.recycle(ElasticApmTracer.java:559)
2023-07-18T13:55:07.3803526Z 	at co.elastic.apm.agent.impl.transaction.Transaction.recycle(Transaction.java:378)
2023-07-18T13:55:07.3803872Z 	at co.elastic.apm.agent.impl.transaction.AbstractSpan.decrementReferences(AbstractSpan.java:677)
2023-07-18T13:55:07.3804114Z 	at co.elastic.apm.agent.impl.ActiveStack.deactivate(ActiveStack.java:136)
2023-07-18T13:55:07.3804382Z 	at co.elastic.apm.agent.impl.ElasticApmTracer.deactivate(ElasticApmTracer.java:855)
2023-07-18T13:55:07.3804698Z 	at co.elastic.apm.agent.impl.transaction.ElasticContext.deactivate(ElasticContext.java:60)
2023-07-18T13:55:07.3805012Z 	at co.elastic.apm.agent.impl.transaction.ElasticContext.deactivate(ElasticContext.java:30)
2023-07-18T13:55:07.3805599Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailureContextPropagation(ResponseListenerWrapper.java:138)
2023-07-18T13:55:07.3805971Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailure(ResponseListenerWrapper.java:111)
2023-07-18T13:55:07.3806370Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailureClient(ResponseListenerWrapper.java:120)
2023-07-18T13:55:07.3806734Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailure(ResponseListenerWrapper.java:109)
2023-07-18T13:55:07.3807090Z 	at org.elasticsearch.client.RestClient$FailureTrackingResponseListener.onDefinitiveFailure(RestClient.java:686)
2023-07-18T13:55:07.3807311Z 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:409)
2023-07-18T13:55:07.3807780Z 	at org.elasticsearch.client.RestClient$1.completed(RestClient.java:393)
2023-07-18T13:55:07.3808050Z 	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
2023-07-18T13:55:07.3808537Z 	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:181)
2023-07-18T13:55:07.3808921Z 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:448)
2023-07-18T13:55:07.3809278Z 	at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:338)
2023-07-18T13:55:07.3809635Z 	at org.apache.http.impl.nio.client.InternalRequestExecutor.inputReady(InternalRequestExecutor.java:83)
2023-07-18T13:55:07.3810010Z 	at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
2023-07-18T13:55:07.3810422Z 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
2023-07-18T13:55:07.3810809Z 	at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
2023-07-18T13:55:07.3811137Z 	at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
2023-07-18T13:55:07.3811419Z 	at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
2023-07-18T13:55:07.3811737Z 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
2023-07-18T13:55:07.3812051Z 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
2023-07-18T13:55:07.3812350Z 	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
2023-07-18T13:55:07.3812620Z 	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
2023-07-18T13:55:07.3812988Z 	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
2023-07-18T13:55:07.3813149Z 	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

My guess on how this can happen:
 * `ResponseListenerWrapper` holds a reference to the span **without** incrementing references. The `ResponseListenerWrapper` relies on the span not being ended and reported for it to not become invalid.
 * In the test the span is already ended and recycled by someone else before `ResponseListenerWrapper.onFailure` is executed.
 * when `ResponseListenerWrapper.onFailure` is executed, it tries to end and therefore recycle an already ended span.
 
 As visible in the logs based on the object-identity, the `ResponseListenerWrapper` was created for the `Elasticsearch: DELETE /my-index/_doc/38uhjds8s4g` span.

**Comment by JonasKunz** [comment]
I've been able to identify why the span is ended twice with further analysis of the stacktrace from the test logs:

```
2023-07-18T13:55:07.3778398Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailureContextPropagation(ResponseListenerWrapper.java:138)
2023-07-18T13:55:07.3778769Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailure(ResponseListenerWrapper.java:111)
2023-07-18T13:55:07.3779169Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailureClient(ResponseListenerWrapper.java:120)
2023-07-18T13:55:07.3779537Z 	at co.elastic.apm.agent.esrestclient.ResponseListenerWrapper.onFailure(ResponseListenerWrapper.java:109)
```

`ResponseListenerWrapper.java:120` is the call to the delegate of the wrapped `ResponseListener`. This means that we somehow double-wrap the `ResponseListener`, causing the span to be ended twice.
