### ISSUE TITLE
java.lang.IllegalStateException: InteliJ debug agent detected, disable it to prevent unexpected instrumentation errors

### ISSUE THREAD

**Issue by EvgeniGordeev** [elastic/apm-agent-java#3314]
Even though https://github.com/elastic/apm-agent-java/issues/1673 got fixed a while ago in the latest IntelliJ IDEA 2023.2.1 (Ultimate Edition) with latest agent 1.42.0 we can see : 

```
[elastic-apm-agent] ERROR Failed to start agent
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at co.elastic.apm.agent.premain.AgentMain.loadAndInitializeAgent(AgentMain.java:157)
	at co.elastic.apm.agent.premain.AgentMain.init(AgentMain.java:98)
	at co.elastic.apm.agent.premain.AgentMain.agentmain(AgentMain.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:491)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:513)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at co.elastic.apm.agent.util.DependencyInjectingServiceLoader.instantiate(DependencyInjectingServiceLoader.java:129)
	at co.elastic.apm.agent.util.DependencyInjectingServiceLoader.instantiate(DependencyInjectingServiceLoader.java:119)
	at co.elastic.apm.agent.util.DependencyInjectingServiceLoader.<init>(DependencyInjectingServiceLoader.java:70)
	at co.elastic.apm.agent.util.DependencyInjectingServiceLoader.load(DependencyInjectingServiceLoader.java:90)
	at co.elastic.apm.agent.bci.ElasticApmAgent.loadInstrumentations(ElasticApmAgent.java:188)
	at co.elastic.apm.agent.bci.ElasticApmAgent.initInstrumentation(ElasticApmAgent.java:180)
	at co.elastic.apm.agent.bci.ElasticApmAgent.initialize(ElasticApmAgent.java:166)
	... 13 more
Caused by: java.lang.IllegalStateException: IntelliJ debug agent detected, disable it to prevent unexpected instrumentation errors. See https://github.com/elastic/apm-agent-java/issues/1673
	at co.elastic.apm.agent.concurrent.ForkJoinTaskInstrumentation.<clinit>(ForkJoinTaskInstrumentation.java:52)
	... 22 more
```

## Describe the bug
Intellij: 2023.2.1
Elastic APM agent: 1.42.0
JDK: openjdk 17.0.8 or 20.0.2

Instrumentation doesn't work in debug mode in Intellij IDE. 

## Expected behavior
Elastic APM agent can start without errors

**Comment by JonasKunz** [comment]
The issue should indeed be fixed in IntelliJ, so we should be able to remove the check causing that exception.
I've created a PR (#3315) for it. But before we merge that we want to make sure that everything actually works correctly.

@EvgeniGordeev could you try with [this snapshot](https://github.com/elastic/apm-agent-java/suites/15953552213/artifacts/910805260) agent and see if it works correctly on your project with the IntelliJ debugging agent activated?

**Comment by EvgeniGordeev** [comment]
@JonasKunz Tried the new version in a maven project and it works with debugger on: 

```xml
        <dependency>
            <groupId>co.elastic.apm</groupId>
            <artifactId>elastic-apm-agent</artifactId>
            <version>1.42.1-SNAPSHOT</version>
            <scope>system</scope>
            <systemPath>${basedir}/elastic-apm-agent-1.42.1-SNAPSHOT.jar</systemPath>
            <optional>true</optional>
        </dependency>
```

Thanks!
