### ISSUE TITLE
Spring Boot 3.2 - WebClientSubscriber - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by NicklasWallgren** [elastic/apm-agent-java#3439]
The latest version of the agent does not support Spring Boot 3.2

The `ClientResponse#rawStatusCode` was removed in Spring Framework 6.1

![image](https://github.com/elastic/apm-agent-java/assets/1784879/d0ee45ef-2ae5-459b-bf84-01b0783b9b02)

```
WARN  reactor.core.Exceptions - throwIfFatal detected a jvm fatal exception, which is thrown and logged below:
java.lang.NoSuchMethodError: 'int org.springframework.web.reactive.function.client.ClientResponse.rawStatusCode()'
	at co.elastic.apm.agent.springwebclient.WebClientSubscriber.onNext(WebClientSubscriber.java:77)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:106)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:106)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:106)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:106)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:106)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:106)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:106)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onNext(MonoFlatMapMany.java:250)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:106)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:106)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onNext(FluxHide.java:137)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2571)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.request(FluxHide.java:152)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.request(FluxContextWrite.java:136)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onSubscribeInner(MonoFlatMapMany.java:150)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyInner.onSubscribe(MonoFlatMapMany.java:245)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onSubscribe(TracedSubscriber.java:85)
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onSubscribe(FluxContextWrite.java:101)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onSubscribe(TracedSubscriber.java:85)
	at reactor.core.publisher.FluxHide$SuppressFuseableSubscriber.onSubscribe(FluxHide.java:122)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:68)
	at reactor.core.publisher.MonoFlatMapMany$FlatMapManyMain.onNext(MonoFlatMapMany.java:195)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:106)
	at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
	at reactor.core.publisher.FluxRetryWhen$RetryWhenMainSubscriber.onNext(FluxRetryWhen.java:177)
	at co.elastic.apm.agent.reactor.TracedSubscriber.onNext(TracedSubscriber.java:106)
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.success(MonoCreate.java:176)
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:435)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:710)
	at reactor.netty.resources.DefaultPooledConnectionProvider$DisposableAcquire.onStateChange(DefaultPooledConnectionProvider.java:195)
	at reactor.netty.resources.DefaultPooledConnectionProvider$PooledConnection.onStateChange(DefaultPooledConnectionProvider.java:456)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:703)
```

**Comment by kumlien** [comment]
Great job @NicklasWallgren , a release with this fix will be highly appreciated!

**Comment by NicklasWallgren** [comment]
@jackshirazi Any ETA on support for Spring Framework 6.1 and Spring Boot 3.2?

**Comment by KaVeKa** [comment]
There is a pull request https://github.com/elastic/apm-agent-java/pull/3440 which resolves this issue. Don't know anything about an ETA for release, but yesterday @JonasKunz fixed this PR.

**Comment by JonasKunz** [comment]
#3440 should indeed fix the issue. We have no new release scheduled yet, but we'll likely do one in the first half of december. If you need the fix earlier, you can use the snapshot-build after #3440 is merged.

**Comment by NicklasWallgren** [comment]
> #3440 should indeed fix the issue. We have no new release scheduled yet, but we'll likely do one in the first half of december. If you need the fix earlier, you can use the snapshot-build after #3440 is merged.

Do you have a release schedule yet? 🙂
