### ISSUE TITLE
NPE in ApacheHttpClientApiAdapter#getHostName - Spring 6.1 RestClient

### ISSUE THREAD

**Issue by NicklasWallgren** [elastic/apm-agent-java#3478]
The new `RestClient` that is part of Spring 6.1 sends the `HttpHost` target as [null](https://github.com/spring-projects/spring-framework/blob/a155a6b3e21ba01abc9d207d8e1225755adb7d11/spring-web/src/main/java/org/springframework/http/client/HttpComponentsClientHttpRequest.java#L95) which isn't handled by the `ApacheHttpClient5ApiAdapter#getHostName` method. The [interface](https://github.com/apache/httpcomponents-client/blob/master/httpclient5/src/main/java/org/apache/hc/client5/http/classic/HttpClient.java#L162)  for the `HttpClient` allows the target to be `null`.

**Stacktrace**
```
java.lang.NullPointerException: Cannot invoke "org.apache.hc.core5.http.HttpHost.getHostName()" because "httpHost" is null
	at co.elastic.apm.agent.httpclient.v5.helper.ApacheHttpClient5ApiAdapter.getHostName(ApacheHttpClient5ApiAdapter.java:53) ~[elastic-apm-agent-c0c4fc57bb13f1eb30fc0769cc96e7ab-ac8d1c4ecac81aabe5e989b93c598194.jar:1.45.0]
	at co.elastic.apm.agent.httpclient.v5.helper.ApacheHttpClient5ApiAdapter.getHostName(ApacheHttpClient5ApiAdapter.java:31) ~[elastic-apm-agent-c0c4fc57bb13f1eb30fc0769cc96e7ab-ac8d1c4ecac81aabe5e989b93c598194.jar:1.45.0]
	at co.elastic.apm.agent.httpclient.common.AbstractApacheHttpClientAdvice.startSpan(AbstractApacheHttpClientAdvice.java:44) ~[elastic-apm-agent-c0c4fc57bb13f1eb30fc0769cc96e7ab-ac8d1c4ecac81aabe5e989b93c598194.jar:1.45.0]
	at co.elastic.apm.agent.httpclient.v5.ApacheHttpClient5Instrumentation$ApacheHttpClient5Advice.onBeforeExecute(ApacheHttpClient5Instrumentation.java:53) ~[elastic-apm-agent-c0c4fc57bb13f1eb30fc0769cc96e7ab-ac8d1c4ecac81aabe5e989b93c598194.jar:1.45.0]
	at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:146) ~[httpclient5-5.2.1.jar:5.2.1]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:87) ~[httpclient5-5.2.1.jar:5.2.1]
	at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[httpclient5-5.2.1.jar:5.2.1]
	at org.apache.hc.client5.http.classic.HttpClient.executeOpen(HttpClient.java:183) ~[httpclient5-5.2.1.jar:5.2.1]
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:95) ~[spring-web-6.1.1.jar:6.1.1]
	at org.springframework.http.client.AbstractStreamingClientHttpRequest.executeInternal(AbstractStreamingClientHttpRequest.java:70) ~[spring-web-6.1.1.jar:6.1.1]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-6.1.1.jar:6.1.1]
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.exchangeInternal(DefaultRestClient.java:453) ~[spring-web-6.1.1.jar:6.1.1]
	at org.springframework.web.client.DefaultRestClient$DefaultRequestBodyUriSpec.retrieve(DefaultRestClient.java:424) ~[spring-web-6.1.1.jar:6.1.1]

```

**Comment by jackshirazi** [comment]
Thanks for raising this, we'll schedule a bugfix
