### ISSUE TITLE
1.50.0 agent fails to start on Java 7

### ISSUE THREAD

**Issue by jackshirazi** [elastic/apm-agent-java#3655]
## Describe the bug
Wrong version of jctools

## Steps to reproduce
Start the agent using java 7

## Expected behavior
Should start

## Debug logs

<details>
<summary>Click to expand</summary>

```
[elastic-apm-agent] WARN Java 7 support is deprecated and will be removed in a future version
[elastic-apm-agent] INFO Delaying Elastic APM Agent initialization by 3000 milliseconds.
[elastic-apm-agent] ERROR Failed to start agent
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at co.elastic.apm.agent.premain.AgentMain.loadAndInitializeAgent(AgentMain.java:157)
        at co.elastic.apm.agent.premain.AgentMain.access$000(AgentMain.java:35)
        at co.elastic.apm.agent.premain.AgentMain$1.run(AgentMain.java:131)
Caused by: java.lang.UnsupportedClassVersionError: org/jctools/queues/atomic/MpmcAtomicArrayQueue : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at co.elastic.apm.agent.premain.ShadedClassLoader.defineClass(ShadedClassLoader.java:171)
        at co.elastic.apm.agent.premain.ShadedClassLoader.findClass(ShadedClassLoader.java:149)
        at co.elastic.apm.agent.premain.ShadedClassLoader.loadClass(ShadedClassLoader.java:133)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at co.elastic.apm.agent.objectpool.ObjectPoolFactory.createRecyclableObjectPool(ObjectPoolFactory.java:43)
        at co.elastic.apm.agent.report.PartialTransactionReporter.<init>(PartialTransactionReporter.java:46)
        at co.elastic.apm.agent.report.ApmServerReporter.<init>(ApmServerReporter.java:161)
        at co.elastic.apm.agent.report.ReporterFactory.createReporter(ReporterFactory.java:40)
        at co.elastic.apm.agent.impl.ElasticApmTracerBuilder.build(ElasticApmTracerBuilder.java:186)
        at co.elastic.apm.agent.impl.ElasticApmTracerBuilder.build(ElasticApmTracerBuilder.java:134)
        at co.elastic.apm.agent.bci.ElasticApmAgent.initialize(ElasticApmAgent.java:165)
        ... 7 more

```
</details>

**Comment by SylvainJuge** [comment]
What is surprising is that we recently had a PR to update to 4.0.3 that was expected to fix compatibility with older versions: https://github.com/elastic/apm-agent-java/pull/3618

Unfortunately the 4.0.3 version has been compiled for Java 8 as target even if it was expected to be java6 compliant. I have opened https://github.com/JCTools/JCTools/issues/392 to report that.

I will revert to 4.0.1 in the mean time until it's fixed.

**Comment by jackshirazi** [comment]
Okay, I remember that one, I reported it last time. I thought I had checked it worked when he published it. Maybe we should double check our dependency

**Comment by jackshirazi** [comment]
hah, no definitely it's not java 7 compatible. I must have checked with the wrong jvm!
