### ISSUE TITLE
WebSphere Application Server 9

### ISSUE THREAD

**Issue by adriellcardoso** [elastic/apm-agent-java#370]
Hello,

I use WebSphere Application Server 9 and Java 1.8.
When i put the argument -javaagent, the JVM don't starting, occur the following error:
`[12/4/18 9:17:51:251 BRST] 00000001 ChannelFramew E   CHFW0017E: Failed to load transport channel: com.ibm.wsspi.channel.framework.exception.InvalidChannelFactoryException: com.ibm.ws.webcontainer.channel.WCChannelFactory cannot be loaded
        at com.ibm.ws.channel.framework.impl.WSChannelFrameworkImpl.addChannelFromFactory(WSChannelFrameworkImpl.java:567)
        at com.ibm.ws.channel.framework.impl.WSChannelFrameworkImpl.addChannel(WSChannelFrameworkImpl.java:420)
        at com.ibm.ws.runtime.component.ChannelFrameworkServiceImpl.addChannel(ChannelFrameworkServiceImpl.java:821)
        at com.ibm.ws.runtime.component.ChannelFrameworkServiceImpl.initialize(ChannelFrameworkServiceImpl.java:369)
        at com.ibm.ws.runtime.component.ContainerHelper.initWsComponent(ContainerHelper.java:1193)
        at com.ibm.ws.runtime.component.ContainerHelper.initializeComponent(ContainerHelper.java:1100)
        at com.ibm.ws.runtime.component.ContainerHelper.initializeComponents(ContainerHelper.java:902)
        at com.ibm.ws.runtime.component.ContainerImpl.initializeComponents(ContainerImpl.java:776)
        at com.ibm.ws.runtime.component.ContainerImpl.initializeComponents(ContainerImpl.java:750)
        at com.ibm.ws.runtime.component.ServerImpl.initialize(ServerImpl.java:377)
        at com.ibm.ws.runtime.WsServerImpl.bootServerContainer(WsServerImpl.java:293)
        at com.ibm.ws.runtime.WsServerImpl.start(WsServerImpl.java:224)
        at com.ibm.ws.runtime.WsServerImpl.main(WsServerImpl.java:697)
        at com.ibm.ws.runtime.WsServer.main(WsServer.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at com.ibm.wsspi.bootstrap.WSLauncher.launchMain(WSLauncher.java:234)
        at com.ibm.wsspi.bootstrap.WSLauncher.main(WSLauncher.java:101)
        at com.ibm.wsspi.bootstrap.WSLauncher.run(WSLauncher.java:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:354)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.eclipse.core.launcher.Main.invokeFramework(Main.java:340)
        at org.eclipse.core.launcher.Main.basicRun(Main.java:282)
        at org.eclipse.core.launcher.Main.run(Main.java:981)
        at com.ibm.wsspi.bootstrap.WSPreLauncher.launchEclipse(WSPreLauncher.java:413)
        at com.ibm.wsspi.bootstrap.WSPreLauncher.main(WSPreLauncher.java:174)
Caused by: java.lang.NoClassDefFoundError: com.ibm.wsspi.channel.base.ApplicationChannelFactory
        at java.lang.ClassLoader.defineClassImpl(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:379)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.defineClass(DefaultClassLoader.java:188)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClassHoldingLock(ClasspathManager.java:638)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.defineClass(ClasspathManager.java:613)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findClassImpl(ClasspathManager.java:574)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClassImpl(ClasspathManager.java:492)
        at org.eclipse.osgi.baseadaptor.loader.ClasspathManager.findLocalClass(ClasspathManager.java:465)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.findLocalClass(DefaultClassLoader.java:216)
        at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:395)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:464)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:854)
        at org.eclipse.osgi.internal.loader.BundleLoader.loadClass(BundleLoader.java:340)
        at org.eclipse.osgi.framework.internal.core.BundleHost.loadClass(BundleHost.java:229)
        at org.eclipse.osgi.framework.internal.core.AbstractBundle.loadClass(AbstractBundle.java:1212)
        at com.ibm.ws.channel.framework.ctm.BaseChannelTypeManager$OSGiChannelMetaDataImpl$1.run(BaseChannelTypeManager.java:392)
        at com.ibm.ws.channel.framework.ctm.BaseChannelTypeManager$OSGiChannelMetaDataImpl$1.run(BaseChannelTypeManager.java:390)
        at com.ibm.ws.security.util.AccessController.doPrivileged(AccessController.java:118)
        at com.ibm.ws.channel.framework.ctm.BaseChannelTypeManager$OSGiChannelMetaDataImpl.getClass(BaseChannelTypeManager.java:390)
        at com.ibm.ws.channel.framework.impl.WSChannelFrameworkImpl.addChannelFromFactory(WSChannelFrameworkImpl.java:557)
        ... 39 more
Caused by: java.lang.ClassNotFoundException: com.ibm.wsspi.channel.base.ApplicationChannelFactory cannot be found by com.ibm.ws.webcontainer_8.1.0
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:455)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
        at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:854)
        ... 62 more` 

Please, somebody help me?

Tks

**Comment by adriellcardoso** [comment]
Are you forecast for WebSphere Application Server?

**Comment by eyalkoren** [comment]
It is certainly on our list of interests, but there is no concrete plan. You can register for notifications about releases through GitHub.
