### ISSUE TITLE
NOFOLLOW_LINKS causes issues on Z/OS

### ISSUE THREAD

**Issue by Mekebra** [elastic/apm-agent-java#3721]
Long short is that this line 

https://github.com/elastic/apm-agent-java/blob/a6219bd1d078822e93c714e6258bdd9f8d5ca1fb/apm-agent-common/src/main/java/co/elastic/apm/agent/common/util/ResourceExtractionUtil.java#L102

When run on IBM Z/OS a Second time, causes this:

`Caused by: java.lang.UnsupportedOperationException: NOFOLLOW_LINKS not supported
	at java.base/sun.nio.fs.UnixChannelFactory$Flags.toFlags(UnixChannelFactory.java:100)
	at java.base/sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:126)
	at java.base/sun.nio.fs.UnixChannelFactory.newFileChannel(UnixChannelFactory.java:156)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:185)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:292)
	at java.base/java.nio.channels.FileChannel.open(FileChannel.java:345)
	at co.elastic.apm.agent.common.util.ResourceExtractionUtil.extractResourceToDirectory(ResourceExtractionUtil.java:102)
	at co.elastic.apm.agent.common.util.ResourceExtractionUtil.extractResourceToTempDirectory(ResourceExtractionUtil.java:58)
	at co.elastic.apm.attach.ElasticApmAttacher$AgentJarFileHolder.getAgentJarFile(ElasticApmAttacher.java:213)
	at co.elastic.apm.attach.ElasticApmAttacher$AgentJarFileHolder.<init>(ElasticApmAttacher.java:208)
	at co.elastic.apm.attach.ElasticApmAttacher$AgentJarFileHolder.<clinit>(ElasticApmAttacher.java:205)`

It'd be nice if that could be caught, and resolved. At worst, deleting the file and retrying.
Or at least provide a public method that returns the filename with the added hash, so it can be handled by us...

**Comment by jackshirazi** [comment]
Thanks, we'll need assistance on this as we don't have access to Z/OS. Does the JVM have some specific identifier or property that identifies it's running on Z/OS? I think an easy fix here would be to simply drop the NOFOLLOW_LINKS option when running there

**Comment by Mekebra** [comment]
System property "os.name" is "z/OS" - So that might be the easiest approach.

Also already tested, and just dropping NOFOLLOW_LINKS works.

**Comment by jackshirazi** [comment]
Thanks, that's excellent info. Could you try the snapshot on the linked PR (quick link https://github.com/elastic/apm-agent-java/actions/runs/9959890038/artifacts/1707006314 ) and check it is good for your z/OS test?

**Comment by Mekebra** [comment]
Can confirm it starts up every time now.
