### ISSUE TITLE
Application deployment fails when setting trace_methods

### ISSUE THREAD

**Issue by TeroPihlaja** [elastic/apm-agent-java#474]
**Describe the bug**
Application deployment fails when setting trace_methods to "all"

```trace_methods=com.vilant.*#*```

Payara 5.183
Oracle java version "1.8.0_172"

**Debug logs**
Attach your debug logs.
See the [documentation](https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html#trouble-shooting-logging)
about how to enable debug logging.

<details>
<summary>Click to expand</summary>

```
[2019-02-04T11:39:47.785+0200] [Payara 5.183] [SEVERE] [] [javax.enterprise.system.tools.deployment.common] [tid: _ThreadID=27 _ThreadName=RunLevelControllerThread-1549273153767] [timeMillis: 1549273187785] [levelValue: 1000] [[
  Exception while invoking class org.glassfish.ejb.startup.EjbDeployer load method
java.lang.RuntimeException: EJB Container initialization error
        at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:237)
        at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:293)
        at org.glassfish.ejb.startup.EjbDeployer.load(EjbDeployer.java:103)
        at org.glassfish.internal.data.ModuleInfo.load(ModuleInfo.java:209)
        at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:318)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.prepare(ApplicationLifecycle.java:496)
        at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:418)
        at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:248)
        at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:327)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
        at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:89)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
        at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
        at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$UpOneLevel.run(CurrentTaskFuture.java:786)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.VerifyError: Stack map does not match the one at exception handler 95
Exception Details:
  Location:
    com/vilant/integration/db/Point._persistence_post_clone()Ljava/lang/Object; @95: astore_3
  Reason:
    Type 'com/vilant/integration/db/Point' (current frame, locals[1]) is not assignable to 'co/elastic/apm/agent/impl/transaction/AbstractSpan' (stack map, locals[1])
  Current Frame:
    bci: @84
    flags: { }
    locals: { 'com/vilant/integration/db/Point', 'com/vilant/integration/db/Point', 'com/vilant/integration/db/Point' }
    stack: { 'java/lang/Throwable' }
  Stackmap Frame:
    bci: @95
    flags: { }
    locals: { 'com/vilant/integration/db/Point', 'co/elastic/apm/agent/impl/transaction/AbstractSpan' }
    stack: { 'java/lang/Throwable' }
  Bytecode:
    0x0000000: 014c b200 6ec6 002d b200 6eb6 0074 4d2c
    0x0000010: c700 15b2 006e b600 7812 9eb6 0080 b600
    0x0000020: 834c a700 102c b600 8712 9eb6 008c b600
    0x0000030: 8d4c a700 06b6 0090 2a4d 2cb7 0030 2c01
    0x0000040: b500 342c 01b5 0038 2c01 b500 3c2c 01b5
    0x0000050: 0040 2c4c 572b a700 034d 014e a700 064e
    0x0000060: 014d 2bc6 000e 2b2d b600 94b6 0097 b600
    0x0000070: 9aa7 0006 b600 902d c600 052d bf2c b0
  Exception Handler Table:
    bci [2, 53] => handler: 53
    bci [58, 89] => handler: 95
    bci [98, 116] => handler: 116
  Stackmap Table:
    append_frame(@2,Object[#104])
    append_frame(@37,Object[#104])
    chop_frame(@50,1)
    same_locals_1_stack_item_frame(@53,Object[#102])
    same_frame(@56)
    append_frame(@58,Object[#2])
    full_frame(@89,{Object[#2],Object[#104]},{Object[#160]})
    same_locals_1_stack_item_frame(@95,Object[#102])
    append_frame(@98,Object[#160],Object[#102])
    same_frame(@113)
    same_locals_1_stack_item_frame(@116,Object[#102])
    same_frame(@119)
    same_frame(@125)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.sun.proxy.$Proxy333.<clinit>(Unknown Source)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.sun.ejb.containers.BaseContainer.instantiateEJBLocalBusinessObjectImpl(BaseContainer.java:3875)
        at com.sun.ejb.containers.StatelessSessionContainer.initializeHome(StatelessSessionContainer.java:236)
        at com.sun.ejb.containers.StatelessContainerFactory.createContainer(StatelessContainerFactory.java:63)
        at org.glassfish.ejb.startup.EjbApplication.loadContainers(EjbApplication.java:225)
        ... 21 more
]]

```
</details>

**Comment by eyalkoren** [comment]
Should be fixed with https://github.com/elastic/apm-agent-java/pull/432.
Please try this snapshot: https://github.com/elastic/apm-agent-java/files/2825540/elastic-apm-agent-1.3.1-SNAPSHOT.jar.zip

**Comment by eyalkoren** [comment]
@TeroPihlaja Also, please be very aware to what you define to be traced using this configuration. Such a wide wildcard would probably be OK of debugging, but not so for production. It's advisable to be (much) more specific in what you choose to instrument. The instrumentation overhead may still remain negligible, but sending and storing spans for ALL methods may be way too much.

**Comment by felixbarny** [comment]
We believe this is a problem with the byte code EclipseLink generates for the generated `_persistence_post_clone` method. We will add an option to ignore certain methods and add `_persistence*` by default. Are you using the latest version of EclipseLink?

**Comment by TeroPihlaja** [comment]
This project is using ```EclipseLink, version: Eclipse Persistence Services - 2.7.3.v20180807-4be1041```

**Comment by TeroPihlaja** [comment]
Seems to work!

**Comment by eyalkoren** [comment]
That's great to hear! You can continue using this snapshot for evaluation and the next release will include the fix.
