### ISSUE TITLE
Problem starting agent java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by pablogus** [elastic/apm-agent-java#504]
I'm running a quite old application server JBoss 4.2.3 GA with JDK 7.

When I try to start my server with the APM agent configured, it periodically logs the following exception:

`java.lang.AbstractMethodError: org.apache.catalina.connector.RequestFacade.getDispatcherType()Ljavax/servlet/DispatcherType;
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:782)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:230)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:175)
	at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:182)
	at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:84)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:157)
	at org.apache.catalina.authenticator.SingleSignOn.invoke(SingleSignOn.java:393)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:562)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:262)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:844)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:583)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:446)
	at java.lang.Thread.run(Thread.java:745)
`

Is this a dependency issue? What jars do I need to run the elastic APM agent?

Thanks. Regards,
Pablo.

**Comment by eyalkoren** [comment]
This JBoss version is not supported. You can see more details [in this forum comment](https://discuss.elastic.co/t/jboss-5-2-0-receives-jvm-memory-events-but-services-arent-identified-java-lang-nosuchmethoderror/170019).
