### ISSUE TITLE
Unexpectedly high amount span activations WebSphere 8.5.5 JSF integration tests

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#586]
The `JSF Render` span is activated and deactivated 760 times. Is that a general problem with WebSphere and JSF or are we causing that?

```
[websphere] 2019-04-16 07:20:51.919 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
[websphere] 2019-04-16 07:20:51.919 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
[websphere] 2019-04-16 07:20:51.920 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
[websphere] 2019-04-16 07:20:51.920 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
[websphere] 2019-04-16 07:20:51.921 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
[websphere] 2019-04-16 07:20:51.922 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
[websphere] 2019-04-16 07:20:51.922 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
[websphere] 2019-04-16 07:20:51.922 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
[websphere] 2019-04-16 07:20:51.923 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
[websphere] 2019-04-16 07:20:51.924 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
[websphere] 2019-04-16 07:20:51.925 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
[websphere] 2019-04-16 07:20:51.926 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
[websphere] 2019-04-16 07:20:51.926 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
[websphere] 2019-04-16 07:20:51.927 [LargeThreadPool-thread-56] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating 00-d45f6925380a9e29ea4cb32a1f77721b-f57da50a052ab59c-01 on thread 136
```

**Comment by felixbarny** [comment]
Here are some stack traces from the (de)activation events:

```
[websphere] 2019-04-16 07:30:36.043 [LargeThreadPool-thread-50] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Activating 00-e2e8ab52cdfa0333a12b015e17fe7266-3300226fb31c5070-01 on thread 129
[websphere] [err] java.lang.Exception
[websphere] [err] 	at co.elastic.apm.agent.impl.ElasticApmTracer.activate(ElasticApmTracer.java:488)
[websphere] [err] 	at co.elastic.apm.agent.impl.transaction.TraceContextHolder.activate(TraceContextHolder.java:78)
[websphere] [err] 	at co.elastic.apm.agent.impl.transaction.AbstractSpan.activate(AbstractSpan.java:251)
[websphere] [err] 	at co.elastic.apm.agent.impl.async.SpanInScopeRunnableWrapper.run(SpanInScopeRunnableWrapper.java:61)
[websphere] [err] 	at org.apache.felix.resolver.ResolverImpl$DumbExecutor.execute(ResolverImpl.java:2506)
[websphere] [err] 	at [internal classes]
[websphere] [err] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:805)
[websphere] [err] 	at com.ibm.ws.classloading.internal.GatewayClassLoader$Delegation.loadClass(GatewayClassLoader.java:45)
[websphere] [err] 	at [internal classes]
[websphere] [err] 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:838)
[websphere] [err] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:825)
[websphere] [err] 	at com.ibm.ws.classloading.internal.UnifiedClassLoader.loadClass0(UnifiedClassLoader.java:108)
[websphere] [err] 	at [internal classes]
[websphere] [err] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:805)
[websphere] [err] 	at java.lang.Class.forNameImpl(Native Method)
[websphere] [err] 	at java.lang.Class.forName(Class.java:348)
[websphere] [err] 	at org.apache.myfaces.shared.util.ClassUtils.classForName(ClassUtils.java:191)
[websphere] [err] 	at [internal classes]
[websphere] [err] 	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:198)
[websphere] [err] 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1290)
[websphere] [err] 	at [internal classes]
[websphere] [err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
[websphere] [err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[websphere] [err] 	at java.lang.Thread.run(Thread.java:785)
[websphere] 2019-04-16 07:30:36.060 [LargeThreadPool-thread-50] DEBUG co.elastic.apm.agent.impl.ElasticApmTracer - Deactivating 00-e2e8ab52cdfa0333a12b015e17fe7266-3300226fb31c5070-01 on thread 129
[websphere] [err] java.lang.Exception
[websphere] [err] 	at co.elastic.apm.agent.impl.ElasticApmTracer.deactivate(ElasticApmTracer.java:496)
[websphere] [err] 	at co.elastic.apm.agent.impl.transaction.TraceContextHolder.deactivate(TraceContextHolder.java:83)
[websphere] [err] 	at co.elastic.apm.agent.impl.transaction.AbstractSpan.deactivate(AbstractSpan.java:257)
[websphere] [err] 	at co.elastic.apm.agent.impl.async.SpanInScopeRunnableWrapper.run(SpanInScopeRunnableWrapper.java:76)
[websphere] [err] 	at org.apache.felix.resolver.ResolverImpl$DumbExecutor.execute(ResolverImpl.java:2506)
[websphere] [err] 	at [internal classes]
[websphere] [err] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:805)
[websphere] [err] 	at com.ibm.ws.classloading.internal.GatewayClassLoader$Delegation.loadClass(GatewayClassLoader.java:45)
[websphere] [err] 	at [internal classes]
[websphere] [err] 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:838)
[websphere] [err] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:825)
[websphere] [err] 	at com.ibm.ws.classloading.internal.UnifiedClassLoader.loadClass0(UnifiedClassLoader.java:108)
[websphere] [err] 	at [internal classes]
[websphere] [err] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:805)
[websphere] [err] 	at java.lang.Class.forNameImpl(Native Method)
[websphere] [err] 	at java.lang.Class.forName(Class.java:348)
[websphere] [err] 	at org.apache.myfaces.shared.util.ClassUtils.classForName(ClassUtils.java:191)
[websphere] [err] 	at [internal classes]
[websphere] [err] 	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:198)
[websphere] [err] 	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1290)
[websphere] [err] 	at [internal classes]
[websphere] [err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
[websphere] [err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[websphere] [err] 	at java.lang.Thread.run(Thread.java:785)
```

Seems to have to do with our Executor instrumentation.

I guess we should exclude [`org.apache.felix.resolver.ResolverImpl$DumbExecutor`](https://github.com/snefru/org.apache.felix.resolver/blob/bf988263bc231bca7d939492fa3eea356673426d/src/main/java/org/apache/felix/resolver/ResolverImpl.java#L2502)
