### ISSUE TITLE
Agent doesn't support tagged versions

### ISSUE THREAD

**Issue by s-nel** [elastic/apm-agent-java#680]
**Describe the bug**

When there are dependencies with tagged versions (e.g. `1.0.0-SNAPSHOT`) APM throws this exception

```
java.lang.NumberFormatException: For input string: "0-SNAPSHOT"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at co.elastic.apm.agent.bci.bytebuddy.CustomElementMatchers$Version.<init>(CustomElementMatchers.java:190)
        at co.elastic.apm.agent.bci.bytebuddy.CustomElementMatchers.readImplementationVersionFromManifest(CustomElementMatchers.java:158)
        at co.elastic.apm.agent.bci.bytebuddy.CustomElementMatchers.access$100(CustomElementMatchers.java:44)
        at co.elastic.apm.agent.bci.bytebuddy.CustomElementMatchers$2.matches(CustomElementMatchers.java:128)
        at co.elastic.apm.agent.bci.bytebuddy.CustomElementMatchers$2.matches(CustomElementMatchers.java:125)
        at co.elastic.apm.agent.bci.ElasticApmAgent$4.matches(ElasticApmAgent.java:187)
```

https://github.com/elastic/apm-agent-java/blob/2289d4143d1e0ed965f5c0e04098d6ed6a26c202/apm-agent-core/src/main/java/co/elastic/apm/agent/bci/bytebuddy/CustomElementMatchers.java#L195-L201

It's worth mentioning that [the gist](https://gist.github.com/brianguertin/ada4b65c6d1c4f6d3eee3c12b6ce021b) the code was taken from does support tagged versions

**To Reproduce**
I don't have steps readily available

**Expected behavior**
I expect tagged versions to be supported 

**Debug logs**
I don't have debug logs readily available. LMK if they're needed

**Comment by eyalkoren** [comment]
@s-nel Thanks for reporting- fixing now.
Please note that you this should not affect agent's functionality. Will reduce its log level.

**Comment by eyalkoren** [comment]
Clarification- parsing failure should not affect functionality, but currently it will as the matching itself fails. The related PR that fixes this issue also ensures matching itself returns `true` and not throws Exception.

**Comment by s-nel** [comment]
Thanks for the quick turnaround! Legend 🙇
