### ISSUE TITLE
Exception while trying to create SQL span on Lucee server

### ISSUE THREAD

**Issue by jeremiej-q** [elastic/apm-agent-java#885]
**Describe the bug**
Got an exception while trying to create an SQL span on our [Lucee](https://github.com/lucee/Lucee) servers. 
It happens on every [Lucee](https://github.com/lucee/Lucee) servers (using v5.3) running in Tomcat. 

**To Reproduce**

<details>
<summary>Config of the APM agent</summary>

```
CATALINA_OPTS="$CATALINA_OPTS -javaagent:/opt/lucee/tomcat/lib/elastic-apm-agent-1.10.0.jar"
CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.service_name=service"
CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.environment=environment"
CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.disable_instrumentations=''"
CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.trace_methods='lucee.runtime.type.QueryImpl.*,lucee.runtime.PageContextImpl.*'"
CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.application_packages=lucee.runtime.*"
CATALINA_OPTS="$CATALINA_OPTS -Delastic.apm.server_urls=server.url"
```
</details>

**Expected behavior**
We should see SQL span on the APM viewer but it is not showed there as an error occur when the agent try to create them. 

**Debug logs**

<details>
<summary>Exception stack trace</summary>

```
java.lang.NoClassDefFoundError: co/elastic/apm/agent/jdbc/helper/JdbcHelper
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareStatement(SQLServerConnection.java:2169)
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareStatement(SQLServerConnection.java:1853)
    at lucee.runtime.db.DatasourceConnectionImpl.getPreparedStatement(DatasourceConnectionImpl.java:187)
    at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:265)
    at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:215)
    at lucee.runtime.tag.Query.executeDatasoure(Query.java:1055)
    at lucee.runtime.tag.Query._doEndTag(Query.java:655)
    at lucee.runtime.tag.Query.doEndTag(Query.java:537)
    at quizzdao_cfc$cf.udfCall1(/dao/QuizzDao.cfc:73)
    at quizzdao_cfc$cf.udfCall(/dao/QuizzDao.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:342)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:215)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:682)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:570)
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:768)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1707)
    at quizz_cfc$cf.udfCalla(/business/Quizz.cfc:557)
    at quizz_cfc$cf.udfCall(/business/Quizz.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:342)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:215)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:682)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:570)
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:768)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1707)
    at campagnesdao_cfc$cf.udfCall5(/dao/CampagnesDao.cfc:1143)
    at campagnesdao_cfc$cf.udfCall(/dao/CampagnesDao.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:342)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:215)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:682)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:570)
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:768)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1707)
    at campagnes_cfc$cf.udfCall5(/business/Campagnes.cfc:224)
    at campagnes_cfc$cf.udfCall(/business/Campagnes.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:342)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:215)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:682)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:570)
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:768)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1707)
    at v1._inc_loader_initgame_cfm$cf.call(/v1/_inc_loader_initgame.cfm:140)
    at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:942)
    at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:834)
    at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:816)
    at v1_cfm$cf.call(/v1.cfm:4)
    at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:942)
    at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:834)
    at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:816)
    at application_cfc$cf.udfCall(/Application.cfc:78)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:342)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:215)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:682)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:570)
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
    at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:436)
    at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:215)
    at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:42)
    at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2409)
    at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2399)
    at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2374)
    at lucee.runtime.engine.Request.exe(Request.java:43)
    at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1037)
    at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:983)
    at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:102)
    at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
    at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
    at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
    at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
    at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
    at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: co/elastic/apm/agent/jdbc/helper/JdbcHelper
    at com.microsoft.sqlserver.jdbc.SQLServerConnection.prepareStatement(SQLServerConnection.java:1855)
    at lucee.runtime.db.DatasourceConnectionImpl.getPreparedStatement(DatasourceConnectionImpl.java:187)
    at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:265)
    at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:215)
    at lucee.runtime.tag.Query.executeDatasoure(Query.java:1055)
    at lucee.runtime.tag.Query._doEndTag(Query.java:655)
    at lucee.runtime.tag.Query.doEndTag(Query.java:537)
    at quizzdao_cfc$cf.udfCall1(/dao/QuizzDao.cfc:73)
    at quizzdao_cfc$cf.udfCall(/dao/QuizzDao.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:342)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:215)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:682)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:570)
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:768)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1707)
    at quizz_cfc$cf.udfCalla(/business/Quizz.cfc:557)
    at quizz_cfc$cf.udfCall(/business/Quizz.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:342)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:215)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:682)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:570)
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:768)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1707)
    at campagnesdao_cfc$cf.udfCall5(/dao/CampagnesDao.cfc:1143)
    at campagnesdao_cfc$cf.udfCall(/dao/CampagnesDao.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:342)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:215)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:682)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:570)
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:768)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1707)
    at campagnes_cfc$cf.udfCall5(/business/Campagnes.cfc:224)
    at campagnes_cfc$cf.udfCall(/business/Campagnes.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:342)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:215)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:682)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:570)
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:768)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1707)
    at v1._inc_loader_initgame_cfm$cf.call(/v1/_inc_loader_initgame.cfm:140)
    at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:942)
    at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:834)
    at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:816)
    at v1_cfm$cf.call(/v1.cfm:4)
    at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:942)
    at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:834)
    at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:816)
    at application_cfc$cf.udfCall(/Application.cfc:78)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:342)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:215)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:682)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:570)
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
    at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:436)
```
</details>

**Comment by eyalkoren** [comment]
Please try to append `co.elastic.apm.agent.*` to the `org.osgi.framework.bootdelegation` property in [your configuration file](https://github.com/lucee/Lucee/blob/6c17c2ee7d4e2b37c4a14cb24ead91626eae2add/core/src/main/java/default.properties) and see what happens

**Comment by eyalkoren** [comment]
How do you install the agent? Is it through `-javaagent` or attaching?

**Comment by xdecock** [comment]
-javaagent

currently searching for the config file, but seems to be in the jar directly

**Comment by eyalkoren** [comment]
Based on [this code](https://github.com/lucee/Lucee/blob/dbb220d72027fea68f927654388456515289867a/core/src/main/java/lucee/runtime/osgi/OSGiUtil.java#L1733) it seems like you need to modify the actual file.

**Comment by xdecock** [comment]
Hi, the issue seems to be solved by modifying the actual file indeed, 
i'll propose a PR to the project thanks for your support, i'll now ensure what timing we get, and list what classes we need to instrument

**Comment by eyalkoren** [comment]
Thanks for verifying. 
If you get something generic and useful out of it that can be used by others and want to contribute to the community- let us know.
Closing the issue.

**Comment by mbandizzle** [comment]
@jeremiej-q @xdecock could you please post an example of the java system properties you used to get this working?

I'm using:

```
-javaagent:lib/elastic-apm-agent-1.24.0/elastic-apm-agent-1.24.0.jar
-Delastic.apm.service_name=server_name_here
-Delastic.apm.server_url=http://path/to/server:8200
-Delastic.apm.environment=development
-Delastic.apm.use_path_as_transaction_name=true
```

which is working well with APM except for the logging of SQL/JDBC spans.
